declare const styles: {
  readonly actionButton: string;
  readonly actionIcon: string;
  readonly actionLabel: string;
  readonly actions: string;
  readonly bookmarked: string;
  readonly bookmarkedIcon: string;
  readonly checkmark: string;
  readonly closeButton: string;
  readonly colorButton: string;
  readonly colorGrid: string;
  readonly container: string;
  readonly disabled: string;
  readonly divider: string;
  readonly "fade-in": string;
  readonly header: string;
  readonly section: string;
  readonly sectionTitle: string;
  readonly selected: string;
  readonly title: string;
};
export = styles;
