kind: pipeline
type: docker
name: push-pull-main

clone:
  depth: 100

# Trigger CICD

steps:
  - name: compile
    image: oven/bun:1.1.36
    commands:
      - bun install --ignore-scripts

  - name: tsc
    failure: ignore
    image: oven/bun:1.1.36
    commands:
      - bun tsc
    depends_on:
      - compile

  - name: lint
    failure: ignore
    image: oven/bun:1.1.36
    commands:
      - bun run lint
    depends_on:
      - compile

  - name: stylelint
    failure: ignore
    image: oven/bun:1.1.36
    commands:
      - bun stylelint
    depends_on:
      - compile

  - name: test
    failure: ignore
    image: oven/bun:1.1.36
    commands:
      - cp apps/backend/.env.example .env
      - cp apps/backend/.env.example packages/database/.env
      - cd packages/database && bun migrate:deploy && bun db:seed
      - cd ../../
      - bun test
      # This is required to fix a bug where the envs are set on buildtime
      - rm -rf .env packages/database/.env
    environment:
      POSTGRES_URL: postgresql://postgres_user:postgres_password@postgres-server:5432/postgres_db
      REDIS_URL: redis://:abcd1234@redis-server:6379/0
      OBJECT_STORAGE_ACCESS_KEY_ID:
        from_secret: OBJECT_STORAGE_ACCESS_KEY_ID
      OBJECT_STORAGE_SECRET_ACCESS_KEY:
        from_secret: OBJECT_STORAGE_SECRET_ACCESS_KEY
      OBJECT_STORAGE_ENDPOINT:
        from_secret: OBJECT_STORAGE_ENDPOINT
      OBJECT_STORAGE_BUCKET:
        from_secret: OBJECT_STORAGE_BUCKET
      OBJECT_STORAGE_REGION:
        from_secret: OBJECT_STORAGE_REGION
      ENVIRONMENT: test
    depends_on:
      - tsc
      - lint
      - stylelint

  - name: build-frontend-next
    image: oven/bun:1.1.36
    commands:
      - cd apps/frontend-next && bun run build
    environment:
      NEXT_PUBLIC_API_URL:
        from_secret: NEXT_PUBLIC_API_URL
    depends_on:
      - test

  - name: build-backend
    image: oven/bun:1.1.36
    commands:
      - cd apps/backend && bun run build && cd ../../
      - cd packages/database && bun run build
    depends_on:
      - test

  - name: build-frontend-base
    image: node:18.15.0
    commands:
      - cd packages/frontend-base && npm run build
    environment:
      VITE_API_URL:
        from_secret: VITE_API_URL
    depends_on:
      - test

  - name: docker-build-frontend-next
    image: docker:24.0.6-dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      # Docker config
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      # Frontend
      - docker pull $CI_REGISTRY/$CI_REGISTRY_IMAGE-frontend-next:$DRONE_BRANCH || true
      - docker build -t $CI_REGISTRY/$CI_REGISTRY_IMAGE-frontend-next:$DRONE_BRANCH -f apps/frontend-next/Dockerfile . --cache-from $CI_REGISTRY/$CI_REGISTRY_IMAGE-frontend-next:$DRONE_BRANCH
      - docker push $CI_REGISTRY/$CI_REGISTRY_IMAGE-frontend-next:$DRONE_BRANCH
    environment:
      CI_REGISTRY_IMAGE:
        from_secret: CI_REGISTRY_IMAGE
      CI_REGISTRY:
        from_secret: CI_REGISTRY
      CI_REGISTRY_USER:
        from_secret: CI_REGISTRY_USER
      CI_REGISTRY_PASSWORD:
        from_secret: CI_REGISTRY_PASSWORD
    depends_on:
      - build-frontend-next
    when:
      event:
        - push

  - name: docker-build-backend
    image: docker:24.0.6-dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      # Docker config
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      # Backend
      - docker pull $CI_REGISTRY/$CI_REGISTRY_IMAGE-backend:$DRONE_BRANCH || true
      - docker build -t $CI_REGISTRY/$CI_REGISTRY_IMAGE-backend:$DRONE_BRANCH -f apps/backend/Dockerfile . --cache-from $CI_REGISTRY/$CI_REGISTRY_IMAGE-backend:$DRONE_BRANCH
      - docker push $CI_REGISTRY/$CI_REGISTRY_IMAGE-backend:$DRONE_BRANCH
    environment:
      CI_REGISTRY_IMAGE:
        from_secret: CI_REGISTRY_IMAGE
      CI_REGISTRY:
        from_secret: CI_REGISTRY
      CI_REGISTRY_USER:
        from_secret: CI_REGISTRY_USER
      CI_REGISTRY_PASSWORD:
        from_secret: CI_REGISTRY_PASSWORD
      OBJECT_STORAGE_ACCESS_KEY_ID:
        from_secret: OBJECT_STORAGE_ACCESS_KEY_ID
      OBJECT_STORAGE_SECRET_ACCESS_KEY:
        from_secret: OBJECT_STORAGE_SECRET_ACCESS_KEY
      OBJECT_STORAGE_ENDPOINT:
        from_secret: OBJECT_STORAGE_ENDPOINT
      OBJECT_STORAGE_BUCKET:
        from_secret: OBJECT_STORAGE_BUCKET
      OBJECT_STORAGE_REGION:
        from_secret: OBJECT_STORAGE_REGION
    depends_on:
      - build-backend
    when:
      event:
        - push

  - name: deploy
    image: alpine:latest
    commands:
      - apk add openssh
      - mkdir -p ~/.ssh
      - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      # Deploy
      - ssh root@verse-mate.apegro.dev "cd ~/verse-mate && docker compose pull && docker compose up -d && docker system prune -a -f"
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    depends_on:
      - docker-build-frontend-next
      - docker-build-backend
    when:
      event:
        - push

services:
  - name: postgres-server
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db

  - name: redis-server
    image: redis:7.0-alpine
    commands:
      - redis-server --requirepass abcd1234

  - name: docker
    image: docker:24.0.6-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request
