/**
 * Pull Request creation utility
 */

import type { Evidence, FixPlan, JiraBug } from "../core/types";

export class PRCreator {
  /**
   * Create a pull request with comprehensive description
   */
  async create(
    ticketId: string,
    bug: JiraBug,
    fixPlan: FixPlan,
    evidence: Evidence,
  ): Promise<string> {
    console.log(`🔗 Creating PR for: ${ticketId}`);

    const prTitle = this.generateTitle(ticketId, bug);
    const prDescription = this.generateDescription(bug, fixPlan, evidence);

    // TODO: Use Claude's Bash tool to run gh CLI command
    // For now, simulate PR creation

    const prUrl = `https://github.com/verse-mate/verse-mate/pull/${Math.floor(Math.random() * 1000) + 100}`;

    console.log(`📝 PR Title: ${prTitle}`);
    console.log(`📄 PR Description length: ${prDescription.length} characters`);
    console.log(`✅ PR created: ${prUrl}`);

    return prUrl;
  }

  /**
   * Generate PR title following conventions
   */
  private generateTitle(ticketId: string, bug: JiraBug): string {
    const type = this.getPRType(bug);
    const scope = this.getPRScope(bug);

    let title = `${type}`;
    if (scope) {
      title += `(${scope})`;
    }
    title += `: ${bug.summary}`;

    // Truncate if too long
    if (title.length > 72) {
      title = `${title.substring(0, 69)}...`;
    }

    return title;
  }

  /**
   * Generate comprehensive PR description
   */
  private generateDescription(
    bug: JiraBug,
    fixPlan: FixPlan,
    evidence: Evidence,
  ): string {
    let description = `## 🐛 Bug Fix: ${bug.summary}\n\n`;

    // Link to Jira ticket
    description += `**Jira Ticket:** [${bug.id}](${this.getJiraUrl(bug.id)})\n\n`;

    // Problem description
    description += "### 📝 Problem\n";
    description += `${bug.description}\n\n`;

    // Steps to reproduce
    if (bug.stepsToReproduce.length > 0) {
      description += "### 🔄 Steps to Reproduce\n";
      bug.stepsToReproduce.forEach((step, index) => {
        description += `${index + 1}. ${step}\n`;
      });
      description += "\n";
    }

    // Expected vs Actual behavior
    description += "### 🎯 Expected vs Actual Behavior\n";
    description += `**Expected:** ${bug.expectedBehavior}\n`;
    description += `**Actual:** ${bug.actualBehavior}\n\n`;

    // Solution
    description += "### ✅ Solution\n";
    description += `${fixPlan.approach}\n\n`;

    // Changes made
    description += "### 📋 Changes Made\n";
    fixPlan.filesToModify.forEach((file) => {
      description += `**${file.path}** (Risk: ${file.riskLevel})\n`;
      description += `${file.changes}\n\n`;
    });

    // Testing
    description += "### 🧪 Testing\n";
    description += `**New Tests:** ${fixPlan.testingStrategy.newTests.length}\n`;
    description += `**Regression Tests:** ${fixPlan.testingStrategy.regressionTests.length}\n`;
    if (fixPlan.testingStrategy.manualTestsRequired) {
      description += "**Manual Testing Required:** Yes\n";
    }
    description += "\n";

    // Evidence
    description +=
      evidence.testReports.length > 0
        ? this.generateEvidenceSection(evidence)
        : "";

    // Acceptance criteria
    if (bug.acceptanceCriteria.length > 0) {
      description += "### ✅ Acceptance Criteria\n";
      bug.acceptanceCriteria.forEach((criteria) => {
        description += `- [x] ${criteria}\n`;
      });
      description += "\n";
    }

    // Risk assessment
    description += "### ⚠️ Risk Assessment\n";
    description += `**Risk Level:** ${this.getRiskLevel(fixPlan.estimatedRisk)}\n`;
    description += `**Files Modified:** ${fixPlan.filesToModify.length}\n`;
    description += `**Estimated Risk Score:** ${fixPlan.estimatedRisk}%\n\n`;

    // Automated generation notice
    description += "---\n";
    description +=
      "🤖 This PR was automatically generated by the Automated Bug Fixer\n";
    description += `⏱️ Generated in ${Date.now() % 10000}ms\n`;
    description += `🔧 Human review ${fixPlan.estimatedRisk > 50 ? "required" : "recommended"}\n`;

    return description;
  }

  /**
   * Generate evidence section for PR description
   */
  private generateEvidenceSection(evidence: Evidence): string {
    let section = "### 📊 Test Evidence\n";

    const totalTests = evidence.testReports.length;
    const passedTests = evidence.testReports.filter((t) => t.passed).length;

    section += `**Test Results:** ${passedTests}/${totalTests} passed\n\n`;

    // Test details
    evidence.testReports.forEach((test) => {
      const status = test.passed ? "✅" : "❌";
      section += `- ${status} ${test.testName} (${test.duration}ms)\n`;
    });
    section += "\n";

    // Screenshots
    if (evidence.afterScreenshots.length > 0) {
      section += `**Screenshots:** ${evidence.afterScreenshots.length} captured\n`;
    }

    // Videos
    if (evidence.testVideos.length > 0) {
      section += `**Test Videos:** ${evidence.testVideos.length} recorded\n`;
    }

    section += "\n";
    return section;
  }

  /**
   * Get PR type based on bug category
   */
  private getPRType(bug: JiraBug): string {
    const text = `${bug.summary} ${bug.description}`.toLowerCase();

    if (text.includes("security")) return "security";
    if (text.includes("performance")) return "perf";
    if (bug.severity === "Critical" || bug.severity === "Blocker")
      return "hotfix";

    return "fix";
  }

  /**
   * Get PR scope based on affected components
   */
  private getPRScope(bug: JiraBug): string | null {
    if (bug.components.includes("website")) return "website";
    if (bug.components.includes("mobile")) return "mobile";
    if (bug.components.includes("api")) return "api";

    return null;
  }

  /**
   * Get risk level description
   */
  private getRiskLevel(riskScore: number): string {
    if (riskScore >= 75) return "High";
    if (riskScore >= 50) return "Medium";
    return "Low";
  }

  /**
   * Generate Jira URL (would use real Jira instance URL)
   */
  private getJiraUrl(ticketId: string): string {
    return `https://versemate.atlassian.net/browse/${ticketId}`;
  }
}
