declare const styles: {
  readonly contentBox: string;
  readonly title: string;
  readonly textBox: string;
  readonly subtitleBox: string;
  readonly subtitle: string;
  readonly description: string;
  readonly paragraphNumber: string;
  readonly versesContainer: string;
  readonly verse: string;
  readonly verseNumber: string;
  readonly verseText: string;
  readonly text: string;
  readonly titleContainer: string;
  readonly actionButtons: string;
  readonly bookmarkButton: string;
  readonly notesButton: string;
  readonly copyLinkButton: string;
};
export = styles;
