// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type AutoHighlightSettingsSettingKey = string;

/** Represents the table public.auto_highlight_settings */
export default interface AutoHighlightSettingsTable {
  setting_key: ColumnType<
    AutoHighlightSettingsSettingKey,
    AutoHighlightSettingsSettingKey,
    AutoHighlightSettingsSettingKey
  >;

  setting_value: ColumnType<string, string, string>;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type AutoHighlightSettings = Selectable<AutoHighlightSettingsTable>;

export type NewAutoHighlightSettings = Insertable<AutoHighlightSettingsTable>;

export type AutoHighlightSettingsUpdate =
  Updateable<AutoHighlightSettingsTable>;
