// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";
import type { HighlightThemesThemeId } from "./HighlightThemes";

export type AutoHighlightsAutoHighlightId = number;

/** Represents the table public.auto_highlights */
export default interface AutoHighlightsTable {
  auto_highlight_id: ColumnType<
    AutoHighlightsAutoHighlightId,
    AutoHighlightsAutoHighlightId | undefined,
    AutoHighlightsAutoHighlightId
  >;

  theme_id: ColumnType<
    HighlightThemesThemeId,
    HighlightThemesThemeId,
    HighlightThemesThemeId
  >;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  chapter_number: ColumnType<number, number, number>;

  start_verse: ColumnType<number, number, number>;

  end_verse: ColumnType<number, number, number>;

  relevance_score: ColumnType<number, number, number>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type AutoHighlights = Selectable<AutoHighlightsTable>;

export type NewAutoHighlights = Insertable<AutoHighlightsTable>;

export type AutoHighlightsUpdate = Updateable<AutoHighlightsTable>;
