// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";

export type BookIntroductionsIntroductionId = string;

/** Represents the table public.book_introductions */
export default interface BookIntroductionsTable {
  introduction_id: ColumnType<
    BookIntroductionsIntroductionId,
    BookIntroductionsIntroductionId | undefined,
    BookIntroductionsIntroductionId
  >;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  author: ColumnType<string | null, string | null, string | null>;

  date_written: ColumnType<string | null, string | null, string | null>;

  biblical_role: ColumnType<string | null, string | null, string | null>;

  key_themes: ColumnType<string[] | null, string[] | null, string[] | null>;

  related_books: ColumnType<string | null, string | null, string | null>;

  literary_style: ColumnType<string | null, string | null, string | null>;

  full_intro_text: ColumnType<string, string, string>;

  language_code: ColumnType<string, string | undefined, string>;

  version: ColumnType<number, number | undefined, number>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  created_by_admin: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type BookIntroductions = Selectable<BookIntroductionsTable>;

export type NewBookIntroductions = Insertable<BookIntroductionsTable>;

export type BookIntroductionsUpdate = Updateable<BookIntroductionsTable>;
