// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { GenresGenreId } from "./Genres";
import type { default as TestamentEnum } from "./TestamentEnum";

export type BooksBookId = number;

/** Represents the table public.books */
export default interface BooksTable {
  book_id: ColumnType<BooksBookId, BooksBookId | undefined, BooksBookId>;

  name: ColumnType<string, string, string>;

  testament: ColumnType<TestamentEnum, TestamentEnum, TestamentEnum>;

  genre_id: ColumnType<GenresGenreId, GenresGenreId, GenresGenreId>;
}

export type Books = Selectable<BooksTable>;

export type NewBooks = Insertable<BooksTable>;

export type BooksUpdate = Updateable<BooksTable>;
