// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";

export type ChaptersChapterId = number;

/** Represents the table public.chapters */
export default interface ChaptersTable {
  chapter_id: ColumnType<
    ChaptersChapterId,
    ChaptersChapterId | undefined,
    ChaptersChapterId
  >;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  chapter_number: ColumnType<number, number, number>;
}

export type Chapters = Selectable<ChaptersTable>;

export type NewChapters = Insertable<ChaptersTable>;

export type ChaptersUpdate = Updateable<ChaptersTable>;
