// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type CoachMonthlyReportsId = number;

/** Represents the table public.coach_monthly_reports */
export default interface CoachMonthlyReportsTable {
  id: ColumnType<
    CoachMonthlyReportsId,
    CoachMonthlyReportsId | undefined,
    CoachMonthlyReportsId
  >;

  kind: ColumnType<string, string, string>;

  coach_id: ColumnType<string | null, string | null | undefined, string | null>;

  month: ColumnType<string, string, string>;

  summary: ColumnType<unknown, unknown, unknown>;

  state: ColumnType<string, string, string>;

  hold_reason: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  sent_to: ColumnType<string[], string[] | undefined, string[]>;

  skipped: ColumnType<string[], string[] | undefined, string[]>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  released_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;

  sent_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;
}

export type CoachMonthlyReports = Selectable<CoachMonthlyReportsTable>;

export type NewCoachMonthlyReports = Insertable<CoachMonthlyReportsTable>;

export type CoachMonthlyReportsUpdate = Updateable<CoachMonthlyReportsTable>;
