// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type CoachMondayRemindersId = number;

/** Represents the table public.coach_monday_reminders */
export default interface CoachMondayRemindersTable {
  id: ColumnType<
    CoachMondayRemindersId,
    CoachMondayRemindersId | undefined,
    CoachMondayRemindersId
  >;

  run_date: ColumnType<Date, Date | string, Date | string>;

  kind: ColumnType<string, string, string>;

  coach_id: ColumnType<string | null, string | null | undefined, string | null>;

  rotating_class_id: ColumnType<
    number | null,
    number | null | undefined,
    number | null
  >;

  found: ColumnType<boolean, boolean, boolean>;

  outcome: ColumnType<string, string, string>;

  email: ColumnType<string | null, string | null | undefined, string | null>;

  reason: ColumnType<string | null, string | null | undefined, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachMondayReminders = Selectable<CoachMondayRemindersTable>;

export type NewCoachMondayReminders = Insertable<CoachMondayRemindersTable>;

export type CoachMondayRemindersUpdate = Updateable<CoachMondayRemindersTable>;
