// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { UserId } from "./User";

export type CoachLeaderEmailChangesId = number;

/** Represents the table public.coach_leader_email_changes */
export default interface CoachLeaderEmailChangesTable {
  id: ColumnType<
    CoachLeaderEmailChangesId,
    CoachLeaderEmailChangesId | undefined,
    CoachLeaderEmailChangesId
  >;

  slug: ColumnType<string, string, string>;

  previous_email: ColumnType<string, string, string>;

  new_email: ColumnType<string, string, string>;

  changed_by: ColumnType<
    UserId | null,
    UserId | null | undefined,
    UserId | null
  >;

  changed_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachLeaderEmailChanges = Selectable<CoachLeaderEmailChangesTable>;

export type NewCoachLeaderEmailChanges =
  Insertable<CoachLeaderEmailChangesTable>;

export type CoachLeaderEmailChangesUpdate =
  Updateable<CoachLeaderEmailChangesTable>;
