// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type CoachMonthlyNarrativesMonth = string;

/** Represents the table public.coach_monthly_narratives */
export default interface CoachMonthlyNarrativesTable {
  month: ColumnType<
    CoachMonthlyNarrativesMonth,
    CoachMonthlyNarrativesMonth,
    CoachMonthlyNarrativesMonth
  >;

  executive_summary: ColumnType<unknown, unknown | undefined, unknown>;

  trends: ColumnType<unknown, unknown | undefined, unknown>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachMonthlyNarratives = Selectable<CoachMonthlyNarrativesTable>;

export type NewCoachMonthlyNarratives = Insertable<CoachMonthlyNarrativesTable>;

export type CoachMonthlyNarrativesUpdate =
  Updateable<CoachMonthlyNarrativesTable>;
