// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type CoachCalibrationRunsId = number;

/** Represents the table public.coach_calibration_runs */
export default interface CoachCalibrationRunsTable {
  id: ColumnType<
    CoachCalibrationRunsId,
    CoachCalibrationRunsId | undefined,
    CoachCalibrationRunsId
  >;

  model_version: ColumnType<string, string, string>;

  composite_mae: ColumnType<number, number, number>;

  dimensions_within_one: ColumnType<number, number, number>;

  comparisons: ColumnType<number, number, number>;

  reports: ColumnType<number, number, number>;

  measured_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachCalibrationRuns = Selectable<CoachCalibrationRunsTable>;

export type NewCoachCalibrationRuns = Insertable<CoachCalibrationRunsTable>;

export type CoachCalibrationRunsUpdate = Updateable<CoachCalibrationRunsTable>;
