// @generated
// This file is automatically generated by Kanel. Do not modify manually.
//
// NOTE: hand-authored to match Kanel's output for the coach_notes table
// created in migration 20260721000003-create-coach-notes.ts. Re-run
// `bun model:generate` after applying the migration to regenerate in place.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { UserId } from "./User";

export type CoachNotesId = string;

/** Represents the table public.coach_notes */
export default interface CoachNotesTable {
  id: ColumnType<CoachNotesId, CoachNotesId | undefined, CoachNotesId>;

  coach_id: ColumnType<string, string, string>;

  report_id: ColumnType<string, string, string>;

  author_user_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  body: ColumnType<string, string, string>;

  emailed: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachNotes = Selectable<CoachNotesTable>;

export type NewCoachNotes = Insertable<CoachNotesTable>;

export type CoachNotesUpdate = Updateable<CoachNotesTable>;
