// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { CoachReportsId } from "./CoachReports";

export type CoachSessionAssetsId = string;

/** Represents the table public.coach_session_assets */
export default interface CoachSessionAssetsTable {
  id: ColumnType<
    CoachSessionAssetsId,
    CoachSessionAssetsId | undefined,
    CoachSessionAssetsId
  >;

  coach_id: ColumnType<string, string, string>;

  source_session_id: ColumnType<string, string, string>;

  report_id: ColumnType<
    CoachReportsId | null,
    CoachReportsId | null | undefined,
    CoachReportsId | null
  >;

  kind: ColumnType<string, string, string>;

  storage_key: ColumnType<string, string, string>;

  byte_size: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  content_type: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  retained_until: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachSessionAssets = Selectable<CoachSessionAssetsTable>;

export type NewCoachSessionAssets = Insertable<CoachSessionAssetsTable>;

export type CoachSessionAssetsUpdate = Updateable<CoachSessionAssetsTable>;
