// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { CoachReportsId } from "./CoachReports";

/** Represents the table public.coach_intake_sessions */
export default interface CoachIntakeSessionsTable {
  source_session_id: ColumnType<string, string, string>;

  coach_id: ColumnType<string | null, string | null | undefined, string | null>;

  matched_by: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  title: ColumnType<string, string | undefined, string>;

  host_email: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  session_date: ColumnType<Date, Date | string, Date | string>;

  duration_minutes: ColumnType<
    string | null,
    string | number | null | undefined,
    string | number | null
  >;

  observed_at: ColumnType<Date, Date | string | undefined, Date | string>;

  state: ColumnType<string, string | undefined, string>;

  retry_count: ColumnType<number, number | undefined, number>;

  reshare_requested_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;

  reshare_sent_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;

  reshare_resolved_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;

  report_id: ColumnType<
    CoachReportsId | null,
    CoachReportsId | null | undefined,
    CoachReportsId | null
  >;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  hold_reason: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  delivered_to: ColumnType<string[], string[] | undefined, string[]>;

  skipped_recipients: ColumnType<string[], string[] | undefined, string[]>;

  release_required: ColumnType<boolean, boolean | undefined, boolean>;
}

export type CoachIntakeSessions = Selectable<CoachIntakeSessionsTable>;

export type NewCoachIntakeSessions = Insertable<CoachIntakeSessionsTable>;

export type CoachIntakeSessionsUpdate = Updateable<CoachIntakeSessionsTable>;
