// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { UserId } from "./User";

export type CoachUploadsId = string & { __brand: "CoachUploadsId" };

/** Represents the table public.coach_uploads */
export default interface CoachUploadsTable {
  id: ColumnType<CoachUploadsId, CoachUploadsId | undefined, CoachUploadsId>;

  coach_id: ColumnType<string, string, string>;

  class_key: ColumnType<string, string, string>;

  class_name: ColumnType<string, string, string>;

  session_date: ColumnType<Date, Date | string, Date | string>;

  title: ColumnType<string | null, string | null | undefined, string | null>;

  file_name: ColumnType<string, string, string>;

  file_bytes: ColumnType<
    string,
    string | number | bigint,
    string | number | bigint
  >;

  content_type: ColumnType<string, string, string>;

  parts: ColumnType<number, number, number>;

  uploaded_by: ColumnType<
    UserId | null,
    UserId | null | undefined,
    UserId | null
  >;

  by_admin: ColumnType<boolean, boolean | undefined, boolean>;

  state: ColumnType<string, string | undefined, string>;

  failure: ColumnType<string | null, string | null | undefined, string | null>;

  source_session_id: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  received_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;
}

export type CoachUploads = Selectable<CoachUploadsTable>;

export type NewCoachUploads = Insertable<CoachUploadsTable>;

export type CoachUploadsUpdate = Updateable<CoachUploadsTable>;
