// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type CoachRotatingClassesId = number;

/** Represents the table public.coach_rotating_classes */
export default interface CoachRotatingClassesTable {
  id: ColumnType<
    CoachRotatingClassesId,
    CoachRotatingClassesId | undefined,
    CoachRotatingClassesId
  >;

  name: ColumnType<string, string, string>;

  group_email: ColumnType<string, string, string>;

  title_match: ColumnType<string[], string[] | undefined, string[]>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachRotatingClasses = Selectable<CoachRotatingClassesTable>;

export type NewCoachRotatingClasses = Insertable<CoachRotatingClassesTable>;

export type CoachRotatingClassesUpdate = Updateable<CoachRotatingClassesTable>;
