// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

/** Represents the table public.coach_reminder_sends */
export default interface CoachReminderSendsTable {
  coach_id: ColumnType<string, string, string>;

  reminder_date: ColumnType<Date, Date | string, Date | string>;

  report_id: ColumnType<string, string, string>;

  email: ColumnType<string, string, string>;

  sent_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;

  claimed_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachReminderSends = Selectable<CoachReminderSendsTable>;

export type NewCoachReminderSends = Insertable<CoachReminderSendsTable>;

export type CoachReminderSendsUpdate = Updateable<CoachReminderSendsTable>;
