// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

/** Represents the table public.coach_monthly_leader_summaries */
export default interface CoachMonthlyLeaderSummariesTable {
  coach_id: ColumnType<string, string, string>;

  month: ColumnType<string, string, string>;

  summary: ColumnType<unknown, unknown, unknown>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachMonthlyLeaderSummaries =
  Selectable<CoachMonthlyLeaderSummariesTable>;

export type NewCoachMonthlyLeaderSummaries =
  Insertable<CoachMonthlyLeaderSummariesTable>;

export type CoachMonthlyLeaderSummariesUpdate =
  Updateable<CoachMonthlyLeaderSummariesTable>;
