// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type CoachDatasetMetaId = boolean;

/** Represents the table public.coach_dataset_meta */
export default interface CoachDatasetMetaTable {
  id: ColumnType<
    CoachDatasetMetaId,
    CoachDatasetMetaId | undefined,
    CoachDatasetMetaId
  >;

  version: ColumnType<string, string | undefined, string>;

  report_count: ColumnType<number, number | undefined, number>;

  generated_at: ColumnType<string | null, string | null, string | null>;

  schema_version: ColumnType<number | null, number | null, number | null>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachDatasetMeta = Selectable<CoachDatasetMetaTable>;

export type NewCoachDatasetMeta = Insertable<CoachDatasetMetaTable>;

export type CoachDatasetMetaUpdate = Updateable<CoachDatasetMetaTable>;
