// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { CoachRotatingClassesId } from "./CoachRotatingClasses";

/** Represents the table public.coach_rotating_class_leaders */
export default interface CoachRotatingClassLeadersTable {
  class_id: ColumnType<
    CoachRotatingClassesId,
    CoachRotatingClassesId,
    CoachRotatingClassesId
  >;

  leader_slug: ColumnType<string, string, string>;
}

export type CoachRotatingClassLeaders =
  Selectable<CoachRotatingClassLeadersTable>;

export type NewCoachRotatingClassLeaders =
  Insertable<CoachRotatingClassLeadersTable>;

export type CoachRotatingClassLeadersUpdate =
  Updateable<CoachRotatingClassLeadersTable>;
