// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { CoachReportsId } from "./CoachReports";
import type { UserId } from "./User";

export type CoachReportEditsId = number;

/** Represents the table public.coach_report_edits */
export default interface CoachReportEditsTable {
  id: ColumnType<
    CoachReportEditsId,
    CoachReportEditsId | undefined,
    CoachReportEditsId
  >;

  report_id: ColumnType<CoachReportsId, CoachReportsId, CoachReportsId>;

  changes: ColumnType<unknown, unknown, unknown>;

  edited_by: ColumnType<
    UserId | null,
    UserId | null | undefined,
    UserId | null
  >;

  edited_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachReportEdits = Selectable<CoachReportEditsTable>;

export type NewCoachReportEdits = Insertable<CoachReportEditsTable>;

export type CoachReportEditsUpdate = Updateable<CoachReportEditsTable>;
