// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { CoachReportsId } from "./CoachReports";
import type { UserId } from "./User";

/** Represents the table public.coach_report_amendments */
export default interface CoachReportAmendmentsTable {
  report_id: ColumnType<CoachReportsId, CoachReportsId, CoachReportsId>;

  revision: ColumnType<number, number, number>;

  previous: ColumnType<unknown, unknown, unknown>;

  changes: ColumnType<unknown, unknown, unknown>;

  amended_by: ColumnType<
    UserId | null,
    UserId | null | undefined,
    UserId | null
  >;

  amended_at: ColumnType<Date, Date | string | undefined, Date | string>;

  sent_to: ColumnType<string[], string[] | undefined, string[]>;

  skipped_recipients: ColumnType<string[], string[] | undefined, string[]>;

  sent_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;

  sending_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;
  coach_id: ColumnType<string, string, string>;

  attempted_to: ColumnType<string[], string[] | undefined, string[]>;
}

export type CoachReportAmendments = Selectable<CoachReportAmendmentsTable>;

export type NewCoachReportAmendments = Insertable<CoachReportAmendmentsTable>;

export type CoachReportAmendmentsUpdate =
  Updateable<CoachReportAmendmentsTable>;
