// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

/** Represents the table public.coach_reminder_summaries */
export default interface CoachReminderSummariesTable {
  reminder_date: ColumnType<Date, Date | string, Date | string>;

  sent_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachReminderSummaries = Selectable<CoachReminderSummariesTable>;

export type NewCoachReminderSummaries = Insertable<CoachReminderSummariesTable>;

export type CoachReminderSummariesUpdate =
  Updateable<CoachReminderSummariesTable>;
