// @generated
// This file is automatically generated by Kanel. Do not modify manually.
//
// NOTE: hand-authored to match Kanel's output for the coach_recording_links
// table created in migration 20260721000002-create-coach-recording-links.ts.
// Re-run `bun model:generate` after applying the migration to regenerate.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

/** Represents the table public.coach_recording_links */
export default interface CoachRecordingLinksTable {
  coach_id: ColumnType<string, string, string>;

  report_id: ColumnType<string, string, string>;

  recording_url: ColumnType<string, string | undefined, string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachRecordingLinks = Selectable<CoachRecordingLinksTable>;

export type NewCoachRecordingLinks = Insertable<CoachRecordingLinksTable>;

export type CoachRecordingLinksUpdate = Updateable<CoachRecordingLinksTable>;
