// @generated
// This file is automatically generated by Kanel. Do not modify manually.
//
// NOTE: hand-authored to match Kanel's output for the coach_classes table
// created in migration 20260721000000-create-coach-classes.ts. Re-run
// `bun model:generate` after applying the migration to regenerate in place.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { UserId } from "./User";

/** Identifier type for public.coach_classes */
export type CoachClassId = string;

/** Represents the table public.coach_classes */
export default interface CoachClassesTable {
  id: ColumnType<CoachClassId, CoachClassId | undefined, CoachClassId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  name: ColumnType<string, string, string>;

  class_date: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  recurrence: ColumnType<string, string | undefined, string>;

  zoom_link: ColumnType<string, string | undefined, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachClasses = Selectable<CoachClassesTable>;

export type NewCoachClasses = Insertable<CoachClassesTable>;

export type CoachClassesUpdate = Updateable<CoachClassesTable>;
