// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { CoachReportsId } from "./CoachReports";
import type { UserId } from "./User";

/** Represents the table public.coach_report_dimension_scores */
export default interface CoachReportDimensionScoresTable {
  report_id: ColumnType<CoachReportsId, CoachReportsId, CoachReportsId>;

  dimension_n: ColumnType<number, number, number>;

  score: ColumnType<number | null, number | null | undefined, number | null>;

  rationale: ColumnType<string, string | undefined, string>;

  provenance: ColumnType<string, string, string>;

  model_version: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  corrected_by: ColumnType<
    UserId | null,
    UserId | null | undefined,
    UserId | null
  >;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachReportDimensionScores =
  Selectable<CoachReportDimensionScoresTable>;

export type NewCoachReportDimensionScores =
  Insertable<CoachReportDimensionScoresTable>;

export type CoachReportDimensionScoresUpdate =
  Updateable<CoachReportDimensionScoresTable>;
