// @generated
// This file is automatically generated by Kanel. Do not modify manually.
//
// NOTE: hand-authored to match Kanel's output for the coach_zoom_links table
// created in migration 20260719000000-create-coach-zoom-links.ts. Re-run
// `bun model:generate` after applying the migration to regenerate in place.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { UserId } from "./User";

/** Represents the table public.coach_zoom_links */
export default interface CoachZoomLinksTable {
  user_id: ColumnType<UserId, UserId, UserId>;

  zoom_link: ColumnType<string, string | undefined, string>;

  affiliated_church: ColumnType<string, string | undefined, string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachZoomLinks = Selectable<CoachZoomLinksTable>;

export type NewCoachZoomLinks = Insertable<CoachZoomLinksTable>;

export type CoachZoomLinksUpdate = Updateable<CoachZoomLinksTable>;
