// @generated
// This file is automatically generated by Kanel. Do not modify manually.
//
// NOTE: hand-authored to match Kanel's output for the coach_leaders table
// created in migration 20260721011000-create-coach-leaders.ts. Re-run
// `bun model:generate` after applying the migration to regenerate in place.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { UserId } from "./User";

export type CoachLeadersId = string;

/** Represents the table public.coach_leaders */
export default interface CoachLeadersTable {
  id: ColumnType<CoachLeadersId, CoachLeadersId | undefined, CoachLeadersId>;

  email: ColumnType<string, string, string>;

  name: ColumnType<string, string | undefined, string>;

  group_name: ColumnType<string, string | undefined, string>;

  coach_name: ColumnType<string, string | undefined, string>;

  slug: ColumnType<string | null, string | null | undefined, string | null>;

  is_coach: ColumnType<boolean, boolean | undefined, boolean>;

  zoom_link: ColumnType<string, string | undefined, string>;

  is_benchmark: ColumnType<boolean, boolean | undefined, boolean>;

  title_match: ColumnType<string[], string[] | undefined, string[]>;

  alt_emails: ColumnType<string[], string[] | undefined, string[]>;

  not_teaching_attested_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;

  not_teaching_attested_by: ColumnType<
    UserId | null,
    UserId | null | undefined,
    UserId | null
  >;

  invited_by: ColumnType<UserId | null, UserId | null, UserId | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachLeaders = Selectable<CoachLeadersTable>;

export type NewCoachLeaders = Insertable<CoachLeadersTable>;

export type CoachLeadersUpdate = Updateable<CoachLeadersTable>;
