// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type CoachReportsId = string;

/** Represents the table public.coach_reports */
export default interface CoachReportsTable {
  id: ColumnType<CoachReportsId, CoachReportsId, CoachReportsId>;

  coach_id: ColumnType<string, string, string>;

  session_date: ColumnType<Date, Date | string, Date | string>;

  source_session_id: ColumnType<string, string, string>;

  legacy_ids: ColumnType<string[], string[] | undefined, string[]>;

  summary: ColumnType<unknown, unknown, unknown>;

  metrics: ColumnType<unknown, unknown, unknown>;

  body: ColumnType<unknown, unknown, unknown>;

  evidence: ColumnType<
    unknown | null,
    unknown | null | undefined,
    unknown | null
  >;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachReports = Selectable<CoachReportsTable>;

export type NewCoachReports = Insertable<CoachReportsTable>;

export type CoachReportsUpdate = Updateable<CoachReportsTable>;
