// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { UserId } from "./User";

/** Represents the table public.coach_admins */
export default interface CoachAdminsTable {
  email: ColumnType<string, string, string>;

  granted_by: ColumnType<
    UserId | null,
    UserId | null | undefined,
    UserId | null
  >;

  granted_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type CoachAdmins = Selectable<CoachAdminsTable>;

export type NewCoachAdmins = Insertable<CoachAdminsTable>;

export type CoachAdminsUpdate = Updateable<CoachAdminsTable>;
