// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

import type { UserId } from "./User";

export type CoachLeaderEmailRequestsId = number;

/** Represents the table public.coach_leader_email_requests */
export default interface CoachLeaderEmailRequestsTable {
  id: ColumnType<
    CoachLeaderEmailRequestsId,
    CoachLeaderEmailRequestsId | undefined,
    CoachLeaderEmailRequestsId
  >;

  slug: ColumnType<string, string, string>;

  new_email: ColumnType<string, string, string>;

  requested_by: ColumnType<
    UserId | null,
    UserId | null | undefined,
    UserId | null
  >;

  token_hash: ColumnType<string, string, string>;

  status: ColumnType<string, string | undefined, string>;

  refusal: ColumnType<string | null, string | null | undefined, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  expires_at: ColumnType<Date, Date | string, Date | string>;

  resolved_at: ColumnType<
    Date | null,
    Date | string | null | undefined,
    Date | string | null
  >;
}

export type CoachLeaderEmailRequests =
  Selectable<CoachLeaderEmailRequestsTable>;

export type NewCoachLeaderEmailRequests =
  Insertable<CoachLeaderEmailRequestsTable>;

export type CoachLeaderEmailRequestsUpdate =
  Updateable<CoachLeaderEmailRequestsTable>;
