// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { DailyVerseTagsId } from "./DailyVerseTags";
import type { DailyVersesId } from "./DailyVerses";

/** Represents the table public.daily_verse_to_tag */
export default interface DailyVerseToTagTable {
  daily_verse_id: ColumnType<DailyVersesId, DailyVersesId, DailyVersesId>;

  tag_id: ColumnType<DailyVerseTagsId, DailyVerseTagsId, DailyVerseTagsId>;
}

export type DailyVerseToTag = Selectable<DailyVerseToTagTable>;

export type NewDailyVerseToTag = Insertable<DailyVerseToTagTable>;

export type DailyVerseToTagUpdate = Updateable<DailyVerseToTagTable>;
