// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type DailyVerseTagsId = string;

/** Represents the table public.daily_verse_tags */
export default interface DailyVerseTagsTable {
  id: ColumnType<DailyVerseTagsId, DailyVerseTagsId | undefined, DailyVerseTagsId>;

  slug: ColumnType<string, string, string>;

  label: ColumnType<string, string, string>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type DailyVerseTags = Selectable<DailyVerseTagsTable>;

export type NewDailyVerseTags = Insertable<DailyVerseTagsTable>;

export type DailyVerseTagsUpdate = Updateable<DailyVerseTagsTable>;
