// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { DailyVersesId } from "./DailyVerses";
import type { UserId } from "./User";

export type DailyVerseHistoryId = string;

/** Represents the table public.daily_verse_history */
export default interface DailyVerseHistoryTable {
  id: ColumnType<
    DailyVerseHistoryId,
    DailyVerseHistoryId | undefined,
    DailyVerseHistoryId
  >;

  pick_date: ColumnType<Date, Date | string, Date | string>;

  daily_verse_id: ColumnType<DailyVersesId, DailyVersesId, DailyVersesId>;

  user_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type DailyVerseHistory = Selectable<DailyVerseHistoryTable>;

export type NewDailyVerseHistory = Insertable<DailyVerseHistoryTable>;

export type DailyVerseHistoryUpdate = Updateable<DailyVerseHistoryTable>;
