// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";

export type DailyVersesId = string;

/** Represents the table public.daily_verses */
export default interface DailyVersesTable {
  id: ColumnType<DailyVersesId, DailyVersesId | undefined, DailyVersesId>;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  chapter_number: ColumnType<number, number, number>;

  verse_start: ColumnType<number, number, number>;

  verse_end: ColumnType<number | null, number | null, number | null>;

  note: ColumnType<string | null, string | null, string | null>;

  is_active: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type DailyVerses = Selectable<DailyVersesTable>;

export type NewDailyVerses = Insertable<DailyVersesTable>;

export type DailyVersesUpdate = Updateable<DailyVersesTable>;
