// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { UserId } from "./User";

export type DeviceTokensId = string;

/** Represents the table public.device_tokens */
export default interface DeviceTokensTable {
  id: ColumnType<DeviceTokensId, DeviceTokensId | undefined, DeviceTokensId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  token: ColumnType<string, string, string>;

  platform: ColumnType<string, string, string>;

  last_notified_on: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type DeviceTokens = Selectable<DeviceTokensTable>;

export type NewDeviceTokens = Insertable<DeviceTokensTable>;

export type DeviceTokensUpdate = Updateable<DeviceTokensTable>;
