// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { ExplanationsExplanationId } from "./Explanations";

export type ExplanationAudiosAudioId = string;

/** Represents the table public.explanation_audios */
export default interface ExplanationAudiosTable {
  audio_id: ColumnType<
    ExplanationAudiosAudioId,
    ExplanationAudiosAudioId | undefined,
    ExplanationAudiosAudioId
  >;

  explanation_id: ColumnType<
    ExplanationsExplanationId,
    ExplanationsExplanationId,
    ExplanationsExplanationId
  >;

  voice: ColumnType<string, string, string>;

  language_code: ColumnType<string, string, string>;

  storage_key: ColumnType<string, string, string>;

  duration_seconds: ColumnType<number, number, number>;

  character_count: ColumnType<number, number, number>;

  content_hash: ColumnType<string, string, string>;

  tts_provider: ColumnType<string, string, string>;

  tts_model: ColumnType<string, string, string>;

  is_stale: ColumnType<boolean, boolean | undefined, boolean>;

  generated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ExplanationAudios = Selectable<ExplanationAudiosTable>;

export type NewExplanationAudios = Insertable<ExplanationAudiosTable>;

export type ExplanationAudiosUpdate = Updateable<ExplanationAudiosTable>;
