// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type ExplanationLanguagesLanguageCode = string;

/** Represents the table public.explanation_languages */
export default interface ExplanationLanguagesTable {
  language_code: ColumnType<
    ExplanationLanguagesLanguageCode,
    ExplanationLanguagesLanguageCode,
    ExplanationLanguagesLanguageCode
  >;

  name: ColumnType<string, string, string>;

  native_name: ColumnType<string, string, string>;

  explanation_count: ColumnType<number, number | undefined, number>;

  user_preference_count: ColumnType<number, number | undefined, number>;

  is_enabled: ColumnType<boolean, boolean | undefined, boolean>;

  is_default: ColumnType<boolean, boolean | undefined, boolean>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ExplanationLanguages = Selectable<ExplanationLanguagesTable>;

export type NewExplanationLanguages = Insertable<ExplanationLanguagesTable>;

export type ExplanationLanguagesUpdate = Updateable<ExplanationLanguagesTable>;
