// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { ExplanationsExplanationId } from "./Explanations";
import type { UserId } from "./User";

export type ExplanationAudioProgressProgressId = string;

/** Represents the table public.explanation_audio_progress */
export default interface ExplanationAudioProgressTable {
  progress_id: ColumnType<
    ExplanationAudioProgressProgressId,
    ExplanationAudioProgressProgressId | undefined,
    ExplanationAudioProgressProgressId
  >;

  user_id: ColumnType<UserId, UserId, UserId>;

  explanation_id: ColumnType<
    ExplanationsExplanationId,
    ExplanationsExplanationId,
    ExplanationsExplanationId
  >;

  position_seconds: ColumnType<number, number, number>;

  duration_seconds: ColumnType<number, number, number>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ExplanationAudioProgress =
  Selectable<ExplanationAudioProgressTable>;

export type NewExplanationAudioProgress =
  Insertable<ExplanationAudioProgressTable>;

export type ExplanationAudioProgressUpdate =
  Updateable<ExplanationAudioProgressTable>;
