// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.explanation_type_enum */
enum ExplanationTypeEnum {
  summary = "summary",
  byline = "byline",
  detailed = "detailed",
}

export default ExplanationTypeEnum;
