// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { ChaptersChapterId } from "./Chapters";
import type { default as ExplanationTypeEnum } from "./ExplanationTypeEnum";

export type ExplanationsExplanationId = number;

/** Represents the table public.explanations */
export default interface ExplanationsTable {
  explanation_id: ColumnType<
    ExplanationsExplanationId,
    ExplanationsExplanationId | undefined,
    ExplanationsExplanationId
  >;

  type: ColumnType<
    ExplanationTypeEnum,
    ExplanationTypeEnum,
    ExplanationTypeEnum
  >;

  explanation: ColumnType<string, string, string>;

  chapter_id: ColumnType<
    ChaptersChapterId,
    ChaptersChapterId,
    ChaptersChapterId
  >;
}

export type Explanations = Selectable<ExplanationsTable>;

export type NewExplanations = Insertable<ExplanationsTable>;

export type ExplanationsUpdate = Updateable<ExplanationsTable>;
