// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.favorite_type_enum */
enum FavoriteTypeEnum {
  chapter = "chapter",
  insight = "insight",
}

export default FavoriteTypeEnum;
