// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type GenresGenreId = number;

/** Represents the table public.genres */
export default interface GenresTable {
  genre_id: ColumnType<GenresGenreId, GenresGenreId | undefined, GenresGenreId>;

  name: ColumnType<string, string, string>;
}

export type Genres = Selectable<GenresTable>;

export type NewGenres = Insertable<GenresTable>;

export type GenresUpdate = Updateable<GenresTable>;
