// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { default as HighlightColorEnum } from "./HighlightColorEnum";

export type HighlightThemesThemeId = number;

/** Represents the table public.highlight_themes */
export default interface HighlightThemesTable {
  theme_id: ColumnType<
    HighlightThemesThemeId,
    HighlightThemesThemeId | undefined,
    HighlightThemesThemeId
  >;

  name: ColumnType<string, string, string>;

  color: ColumnType<HighlightColorEnum, HighlightColorEnum, HighlightColorEnum>;

  description: ColumnType<string | null, string | null, string | null>;

  is_system: ColumnType<boolean | null, boolean | null, boolean | null>;

  priority: ColumnType<number | null, number | null, number | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type HighlightThemes = Selectable<HighlightThemesTable>;

export type NewHighlightThemes = Insertable<HighlightThemesTable>;

export type HighlightThemesUpdate = Updateable<HighlightThemesTable>;
