// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.highlight_color_enum */
enum HighlightColorEnum {
  yellow = "yellow",
  green = "green",
  blue = "blue",
  pink = "pink",
  purple = "purple",
  orange = "orange",
  red = "red",
  teal = "teal",
  brown = "brown",
}

export default HighlightColorEnum;
