// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusCollectionsCollectionId } from "./JesusCollections";
import type { JesusEventsEventId } from "./JesusEvents";

/** Represents the table public.jesus_collection_events */
export default interface JesusCollectionEventsTable {
  collection_id: ColumnType<
    JesusCollectionsCollectionId,
    JesusCollectionsCollectionId,
    JesusCollectionsCollectionId
  >;
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId,
    JesusEventsEventId
  >;
  sort_order: ColumnType<number | null, number | null, number | null>;
}

export type JesusCollectionEvents = Selectable<JesusCollectionEventsTable>;
export type NewJesusCollectionEvents = Insertable<JesusCollectionEventsTable>;
export type JesusCollectionEventsUpdate =
  Updateable<JesusCollectionEventsTable>;
