// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type JesusThemesThemeId = string;

/** Represents the table public.jesus_themes */
export default interface JesusThemesTable {
  theme_id: ColumnType<
    JesusThemesThemeId,
    JesusThemesThemeId | undefined,
    JesusThemesThemeId
  >;

  slug: ColumnType<string, string, string>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  sort_order: ColumnType<number, number, number>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusThemes = Selectable<JesusThemesTable>;

export type NewJesusThemes = Insertable<JesusThemesTable>;

export type JesusThemesUpdate = Updateable<JesusThemesTable>;
