// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusThemesThemeId } from "./JesusThemes";

export type JesusTopicBriefsBriefId = string;

/** Represents the table public.jesus_topic_briefs */
export default interface JesusTopicBriefsTable {
  brief_id: ColumnType<
    JesusTopicBriefsBriefId,
    JesusTopicBriefsBriefId | undefined,
    JesusTopicBriefsBriefId
  >;

  facet_type: ColumnType<string, string, string>;

  theme_id: ColumnType<
    JesusThemesThemeId,
    JesusThemesThemeId,
    JesusThemesThemeId
  >;

  content: ColumnType<string, string, string>;

  language_code: ColumnType<string, string, string>;

  provenance: ColumnType<number, number | undefined, number>;

  prompt_id: ColumnType<number | null, number | null, number | null>;

  model: ColumnType<string | null, string | null, string | null>;

  version: ColumnType<number | null, number | null, number | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  reviewed_by: ColumnType<string | null, string | null, string | null>;

  reviewed_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusTopicBriefs = Selectable<JesusTopicBriefsTable>;
export type NewJesusTopicBriefs = Insertable<JesusTopicBriefsTable>;
export type JesusTopicBriefsUpdate = Updateable<JesusTopicBriefsTable>;
