// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusPeriodsPeriodId } from "./JesusPeriods";

export type JesusEntriesEntryId = string;

/** Represents the table public.jesus_entries */
export default interface JesusEntriesTable {
  entry_id: ColumnType<
    JesusEntriesEntryId,
    JesusEntriesEntryId | undefined,
    JesusEntriesEntryId
  >;

  slug: ColumnType<string, string, string>;

  kind: ColumnType<string, string, string>;

  title: ColumnType<string, string, string>;

  summary: ColumnType<string | null, string | null, string | null>;

  quote: ColumnType<string | null, string | null, string | null>;

  quote_reference: ColumnType<string | null, string | null, string | null>;

  period_id: ColumnType<
    JesusPeriodsPeriodId | null,
    JesusPeriodsPeriodId | null,
    JesusPeriodsPeriodId | null
  >;

  chronology_order: ColumnType<number | null, number | null, number | null>;

  harmony_key: ColumnType<string | null, string | null, string | null>;

  sort_order: ColumnType<number | null, number | null, number | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusEntries = Selectable<JesusEntriesTable>;

export type NewJesusEntries = Insertable<JesusEntriesTable>;

export type JesusEntriesUpdate = Updateable<JesusEntriesTable>;
