// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type JesusCollectionsCollectionId = string;

/** Represents the table public.jesus_collections */
export default interface JesusCollectionsTable {
  collection_id: ColumnType<
    JesusCollectionsCollectionId,
    JesusCollectionsCollectionId | undefined,
    JesusCollectionsCollectionId
  >;

  slug: ColumnType<string, string, string>;

  name: ColumnType<string, string, string>;

  subtitle: ColumnType<string | null, string | null, string | null>;

  description: ColumnType<string | null, string | null, string | null>;

  filter: ColumnType<unknown | null, unknown | null, unknown | null>;

  is_featured: ColumnType<boolean | null, boolean | null, boolean | null>;

  sort_order: ColumnType<number | null, number | null, number | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusCollections = Selectable<JesusCollectionsTable>;

export type NewJesusCollections = Insertable<JesusCollectionsTable>;

export type JesusCollectionsUpdate = Updateable<JesusCollectionsTable>;
