// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusEntriesEntryId } from "./JesusEntries";

export type JesusEntryTranslationsTranslationId = string;

/** Represents the table public.jesus_entry_translations */
export default interface JesusEntryTranslationsTable {
  translation_id: ColumnType<
    JesusEntryTranslationsTranslationId,
    JesusEntryTranslationsTranslationId | undefined,
    JesusEntryTranslationsTranslationId
  >;

  entry_id: ColumnType<
    JesusEntriesEntryId,
    JesusEntriesEntryId,
    JesusEntriesEntryId
  >;

  language_code: ColumnType<string, string, string>;

  translated_title: ColumnType<string, string, string>;

  translated_summary: ColumnType<string | null, string | null, string | null>;

  translated_quote: ColumnType<string | null, string | null, string | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusEntryTranslations = Selectable<JesusEntryTranslationsTable>;

export type NewJesusEntryTranslations = Insertable<JesusEntryTranslationsTable>;

export type JesusEntryTranslationsUpdate =
  Updateable<JesusEntryTranslationsTable>;
