// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusEventsEventId } from "./JesusEvents";

export type JesusEventRevealsRevealId = string;

/** Represents the table public.jesus_event_reveals */
export default interface JesusEventRevealsTable {
  reveal_id: ColumnType<
    JesusEventRevealsRevealId,
    JesusEventRevealsRevealId | undefined,
    JesusEventRevealsRevealId
  >;
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId,
    JesusEventsEventId
  >;
  channel: ColumnType<string, string, string>;
  content: ColumnType<string, string, string>;
  source_ref: ColumnType<string | null, string | null, string | null>;
  provenance: ColumnType<number, number | undefined, number>;
  language_code: ColumnType<string, string | undefined, string>;
  sort_order: ColumnType<number | null, number | null, number | null>;
  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;
}

export type JesusEventReveals = Selectable<JesusEventRevealsTable>;
export type NewJesusEventReveals = Insertable<JesusEventRevealsTable>;
export type JesusEventRevealsUpdate = Updateable<JesusEventRevealsTable>;
