// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type JesusPeriodsPeriodId = string;

/** Represents the table public.jesus_periods */
export default interface JesusPeriodsTable {
  period_id: ColumnType<
    JesusPeriodsPeriodId,
    JesusPeriodsPeriodId | undefined,
    JesusPeriodsPeriodId
  >;

  slug: ColumnType<string, string, string>;

  name: ColumnType<string, string, string>;

  subtitle: ColumnType<string | null, string | null, string | null>;

  description: ColumnType<string | null, string | null, string | null>;

  sort_order: ColumnType<number, number, number>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusPeriods = Selectable<JesusPeriodsTable>;

export type NewJesusPeriods = Insertable<JesusPeriodsTable>;

export type JesusPeriodsUpdate = Updateable<JesusPeriodsTable>;
