// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusPeriodsPeriodId } from "./JesusPeriods";

export type JesusEventsEventId = string;

/** Represents the table public.jesus_events */
export default interface JesusEventsTable {
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId | undefined,
    JesusEventsEventId
  >;
  slug: ColumnType<string, string, string>;
  title: ColumnType<string, string, string>;
  summary: ColumnType<string | null, string | null, string | null>;
  period_id: ColumnType<
    JesusPeriodsPeriodId | null,
    JesusPeriodsPeriodId | null,
    JesusPeriodsPeriodId | null
  >;
  sequence: ColumnType<number | null, number | null, number | null>;
  chronology_confidence: ColumnType<string, string | undefined, string>;
  parallel_confidence: ColumnType<string, string | undefined, string>;
  location: ColumnType<string | null, string | null, string | null>;
  approximate_date: ColumnType<string | null, string | null, string | null>;
  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;
  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusEvents = Selectable<JesusEventsTable>;
export type NewJesusEvents = Insertable<JesusEventsTable>;
export type JesusEventsUpdate = Updateable<JesusEventsTable>;
