// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";
import type { JesusEventsEventId } from "./JesusEvents";

export type JesusFacetsFacetId = string;

/** Represents the table public.jesus_facets */
export default interface JesusFacetsTable {
  facet_id: ColumnType<
    JesusFacetsFacetId,
    JesusFacetsFacetId | undefined,
    JesusFacetsFacetId
  >;
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId,
    JesusEventsEventId
  >;
  slug: ColumnType<string, string, string>;
  mode: ColumnType<string, string, string>;
  type: ColumnType<string, string, string>;
  speaker: ColumnType<string | null, string | null, string | null>;
  actor: ColumnType<string | null, string | null, string | null>;
  title: ColumnType<string, string, string>;
  text: ColumnType<string | null, string | null, string | null>;
  summary: ColumnType<string | null, string | null, string | null>;
  book_id: ColumnType<
    BooksBookId | null,
    BooksBookId | null,
    BooksBookId | null
  >;
  chapter: ColumnType<number | null, number | null, number | null>;
  verse_start: ColumnType<number | null, number | null, number | null>;
  verse_end: ColumnType<number | null, number | null, number | null>;
  provenance: ColumnType<number, number | undefined, number>;
  sort_order: ColumnType<number | null, number | null, number | null>;
  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;
  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusFacets = Selectable<JesusFacetsTable>;
export type NewJesusFacets = Insertable<JesusFacetsTable>;
export type JesusFacetsUpdate = Updateable<JesusFacetsTable>;
