// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusEventsEventId } from "./JesusEvents";

export type JesusEventReactionsReactionId = string;

/** Represents the table public.jesus_event_reactions */
export default interface JesusEventReactionsTable {
  reaction_id: ColumnType<
    JesusEventReactionsReactionId,
    JesusEventReactionsReactionId | undefined,
    JesusEventReactionsReactionId
  >;
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId,
    JesusEventsEventId
  >;
  who: ColumnType<string, string, string>;
  what: ColumnType<string, string, string>;
  source_ref: ColumnType<string | null, string | null, string | null>;
  provenance: ColumnType<number, number | undefined, number>;
  language_code: ColumnType<string, string | undefined, string>;
  sort_order: ColumnType<number | null, number | null, number | null>;
}

export type JesusEventReactions = Selectable<JesusEventReactionsTable>;
export type NewJesusEventReactions = Insertable<JesusEventReactionsTable>;
export type JesusEventReactionsUpdate = Updateable<JesusEventReactionsTable>;
