// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusEventsEventId } from "./JesusEvents";

export type JesusEventExplanationsExplanationId = string;

/** Represents the table public.jesus_event_explanations */
export default interface JesusEventExplanationsTable {
  explanation_id: ColumnType<
    JesusEventExplanationsExplanationId,
    JesusEventExplanationsExplanationId | undefined,
    JesusEventExplanationsExplanationId
  >;
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId,
    JesusEventsEventId
  >;
  type: ColumnType<string, string, string>;
  content: ColumnType<string, string, string>;
  language_code: ColumnType<string, string, string>;
  provenance: ColumnType<number, number | undefined, number>;
  prompt_id: ColumnType<number | null, number | null, number | null>;
  model: ColumnType<string | null, string | null, string | null>;
  version: ColumnType<number | null, number | null, number | null>;
  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;
  reviewed_by: ColumnType<string | null, string | null, string | null>;
  reviewed_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusEventExplanations = Selectable<JesusEventExplanationsTable>;
export type NewJesusEventExplanations = Insertable<JesusEventExplanationsTable>;
export type JesusEventExplanationsUpdate =
  Updateable<JesusEventExplanationsTable>;
