// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusEventsEventId } from "./JesusEvents";

/** Represents the table public.jesus_event_people */
export default interface JesusEventPeopleTable {
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId,
    JesusEventsEventId
  >;
  person: ColumnType<string, string, string>;
  role: ColumnType<string | null, string | null, string | null>;
}

export type JesusEventPeople = Selectable<JesusEventPeopleTable>;
export type NewJesusEventPeople = Insertable<JesusEventPeopleTable>;
export type JesusEventPeopleUpdate = Updateable<JesusEventPeopleTable>;
