// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusEntriesEntryId } from "./JesusEntries";

export type JesusEntryExplanationsExplanationId = string;

/** Represents the table public.jesus_entry_explanations */
export default interface JesusEntryExplanationsTable {
  explanation_id: ColumnType<
    JesusEntryExplanationsExplanationId,
    JesusEntryExplanationsExplanationId | undefined,
    JesusEntryExplanationsExplanationId
  >;

  entry_id: ColumnType<
    JesusEntriesEntryId,
    JesusEntriesEntryId,
    JesusEntriesEntryId
  >;

  type: ColumnType<string, string, string>;

  explanation: ColumnType<string, string, string>;

  language_code: ColumnType<string, string, string>;

  version: ColumnType<number | null, number | null, number | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusEntryExplanations = Selectable<JesusEntryExplanationsTable>;

export type NewJesusEntryExplanations = Insertable<JesusEntryExplanationsTable>;

export type JesusEntryExplanationsUpdate =
  Updateable<JesusEntryExplanationsTable>;
