// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";
import type { JesusEntriesEntryId } from "./JesusEntries";

export type JesusEntryReferencesReferenceId = string;

/** Represents the table public.jesus_entry_references */
export default interface JesusEntryReferencesTable {
  reference_id: ColumnType<
    JesusEntryReferencesReferenceId,
    JesusEntryReferencesReferenceId | undefined,
    JesusEntryReferencesReferenceId
  >;

  entry_id: ColumnType<
    JesusEntriesEntryId,
    JesusEntriesEntryId,
    JesusEntriesEntryId
  >;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  chapter: ColumnType<number, number, number>;

  verse_start: ColumnType<number | null, number | null, number | null>;

  verse_end: ColumnType<number | null, number | null, number | null>;

  is_primary: ColumnType<boolean | null, boolean | null, boolean | null>;

  sort_order: ColumnType<number | null, number | null, number | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusEntryReferences = Selectable<JesusEntryReferencesTable>;

export type NewJesusEntryReferences = Insertable<JesusEntryReferencesTable>;

export type JesusEntryReferencesUpdate = Updateable<JesusEntryReferencesTable>;
