// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusCollectionsCollectionId } from "./JesusCollections";
import type { JesusEntriesEntryId } from "./JesusEntries";

/** Represents the table public.jesus_collection_entries */
export default interface JesusCollectionEntriesTable {
  collection_id: ColumnType<
    JesusCollectionsCollectionId,
    JesusCollectionsCollectionId,
    JesusCollectionsCollectionId
  >;

  entry_id: ColumnType<
    JesusEntriesEntryId,
    JesusEntriesEntryId,
    JesusEntriesEntryId
  >;

  sort_order: ColumnType<number | null, number | null, number | null>;
}

export type JesusCollectionEntries = Selectable<JesusCollectionEntriesTable>;

export type NewJesusCollectionEntries = Insertable<JesusCollectionEntriesTable>;

export type JesusCollectionEntriesUpdate =
  Updateable<JesusCollectionEntriesTable>;
