// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type JesusLabelTranslationsLabelTranslationId = string;

/** Represents the table public.jesus_label_translations */
export default interface JesusLabelTranslationsTable {
  label_translation_id: ColumnType<
    JesusLabelTranslationsLabelTranslationId,
    JesusLabelTranslationsLabelTranslationId | undefined,
    JesusLabelTranslationsLabelTranslationId
  >;

  entity_type: ColumnType<string, string, string>;

  entity_id: ColumnType<string, string, string>;

  language_code: ColumnType<string, string, string>;

  translated_name: ColumnType<string, string, string>;

  translated_description: ColumnType<
    string | null,
    string | null,
    string | null
  >;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusLabelTranslations = Selectable<JesusLabelTranslationsTable>;

export type NewJesusLabelTranslations = Insertable<JesusLabelTranslationsTable>;

export type JesusLabelTranslationsUpdate =
  Updateable<JesusLabelTranslationsTable>;
