// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusEntriesEntryId } from "./JesusEntries";
import type { JesusThemesThemeId } from "./JesusThemes";

/** Represents the table public.jesus_entry_themes */
export default interface JesusEntryThemesTable {
  entry_id: ColumnType<
    JesusEntriesEntryId,
    JesusEntriesEntryId,
    JesusEntriesEntryId
  >;

  theme_id: ColumnType<
    JesusThemesThemeId,
    JesusThemesThemeId,
    JesusThemesThemeId
  >;
}

export type JesusEntryThemes = Selectable<JesusEntryThemesTable>;

export type NewJesusEntryThemes = Insertable<JesusEntryThemesTable>;

export type JesusEntryThemesUpdate = Updateable<JesusEntryThemesTable>;
