// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";
import type { JesusEventsEventId } from "./JesusEvents";

export type JesusEventPassagesPassageId = string;

/** Represents the table public.jesus_event_passages */
export default interface JesusEventPassagesTable {
  passage_id: ColumnType<
    JesusEventPassagesPassageId,
    JesusEventPassagesPassageId | undefined,
    JesusEventPassagesPassageId
  >;
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId,
    JesusEventsEventId
  >;
  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;
  chapter: ColumnType<number, number, number>;
  verse_start: ColumnType<number | null, number | null, number | null>;
  verse_end: ColumnType<number | null, number | null, number | null>;
  canonical_order: ColumnType<number | null, number | null, number | null>;
  is_primary: ColumnType<boolean | null, boolean | null, boolean | null>;
  emphasis: ColumnType<string | null, string | null, string | null>;
  unique_to_account: ColumnType<string | null, string | null, string | null>;
  sort_order: ColumnType<number | null, number | null, number | null>;
  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type JesusEventPassages = Selectable<JesusEventPassagesTable>;
export type NewJesusEventPassages = Insertable<JesusEventPassagesTable>;
export type JesusEventPassagesUpdate = Updateable<JesusEventPassagesTable>;
