// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { JesusEventsEventId } from "./JesusEvents";
import type { JesusThemesThemeId } from "./JesusThemes";

/** Represents the table public.jesus_event_themes */
export default interface JesusEventThemesTable {
  event_id: ColumnType<
    JesusEventsEventId,
    JesusEventsEventId,
    JesusEventsEventId
  >;
  theme_id: ColumnType<
    JesusThemesThemeId,
    JesusThemesThemeId,
    JesusThemesThemeId
  >;
}

export type JesusEventThemes = Selectable<JesusEventThemesTable>;
export type NewJesusEventThemes = Insertable<JesusEventThemesTable>;
export type JesusEventThemesUpdate = Updateable<JesusEventThemesTable>;
