// @generated
// This file is automatically generated by Kanel. Do not modify manually.
// (Added by 20260527000000-add-lemmas-and-translations.ts; rerun
// `bun run model:generate` after deploy to confirm.)

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { LemmasStrongs } from "./Lemmas";

/**
 * One related-lemma cross-reference attached to a lemma's `related` array.
 * Always shown alongside the parent lemma's card, so its `note` needs to
 * follow the same translation as the parent.
 */
export interface RelatedWord {
  /** Transliteration slug of the related lemma (lookup key into lemmas). */
  translit: string;
  /** Translator-supplied note explaining the relationship. */
  note: string;
}

export default interface LemmaTranslationsTable {
  strongs: ColumnType<LemmasStrongs, LemmasStrongs, LemmasStrongs>;

  /** ISO 639-1 (e.g. "en", "es") or language-region ("en-US", "pt-BR"). */
  language_code: ColumnType<string, string, string>;

  /** "Noun (masc.)", "Verb", etc. — translated. */
  pos: ColumnType<string | null, string | null, string | null>;

  /** Short 1-10 word gloss for the popover header. */
  basic_gloss: ColumnType<string | null, string | null, string | null>;

  /** Ordered list of senses, broadest to narrowest. Stored as JSONB array. */
  semantic_range: ColumnType<string[] | null, string[] | null, string[] | null>;

  /** Long-form lexicon note shown in the expanded card view. */
  notes: ColumnType<string | null, string | null, string | null>;

  /** Cross-references to related lemmas. */
  related: ColumnType<
    RelatedWord[] | null,
    RelatedWord[] | null,
    RelatedWord[] | null
  >;

  /**
   * Origin of this translation row — "hand" (lexicon team), "generated"
   * (production _lemmas.json baseline), "llm:<model>" (LLM-translated),
   * "uw" (unfoldingWord overlay). Lets us prioritize hand entries on
   * collision and audit LLM-translated coverage later.
   */
  source: ColumnType<string | null, string | null, string | null>;
}

export type LemmaTranslations = Selectable<LemmaTranslationsTable>;
export type NewLemmaTranslations = Insertable<LemmaTranslationsTable>;
export type LemmaTranslationsUpdate = Updateable<LemmaTranslationsTable>;
