// @generated
// This file is automatically generated by Kanel. Do not modify manually.
// (Added by 20260527000000-add-lemmas-and-translations.ts; rerun
// `bun run model:generate` after deploy to confirm.)

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { LemmasStrongs, RelatedWord } from "./Lemmas";

export type LemmaTranslationsTranslationId = string;

/**
 * `lemma_translations` holds per-language renderings of the translatable
 * fields. Mirrors `topic_translations`: English is NOT stored here (it's
 * on the `lemmas` row directly). One row per (lemma, language) for every
 * non-English language we serve.
 *
 * Field-name convention follows `topic_translations`'s `translated_*`
 * prefix so query code reads identically across both tables:
 *
 *   SELECT translated_basic_gloss FROM lemma_translations WHERE ...
 *   SELECT translated_name        FROM topic_translations WHERE ...
 */
export default interface LemmaTranslationsTable {
  translation_id: ColumnType<
    LemmaTranslationsTranslationId,
    LemmaTranslationsTranslationId | undefined,
    LemmaTranslationsTranslationId
  >;

  strongs: ColumnType<LemmasStrongs, LemmasStrongs, LemmasStrongs>;

  /** ISO 639-1 (e.g. "es", "de") or language-region ("pt-BR"). */
  language_code: ColumnType<string, string, string>;

  translated_pos: ColumnType<string | null, string | null, string | null>;

  translated_basic_gloss: ColumnType<
    string | null,
    string | null,
    string | null
  >;

  translated_semantic_range: ColumnType<
    string[] | null,
    string[] | null,
    string[] | null
  >;

  translated_notes: ColumnType<string | null, string | null, string | null>;

  translated_related: ColumnType<
    RelatedWord[] | null,
    RelatedWord[] | null,
    RelatedWord[] | null
  >;

  /**
   * Origin of this translation row — "hand", "llm:<model>", "uw"
   * (unfoldingWord). Lets us prioritize hand entries on collision and
   * audit LLM-translated coverage later.
   */
  source: ColumnType<string | null, string | null, string | null>;

  is_active: ColumnType<
    boolean | null,
    boolean | null | undefined,
    boolean | null
  >;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type LemmaTranslations = Selectable<LemmaTranslationsTable>;
export type NewLemmaTranslations = Insertable<LemmaTranslationsTable>;
export type LemmaTranslationsUpdate = Updateable<LemmaTranslationsTable>;
