// @generated
// This file is automatically generated by Kanel. Do not modify manually.
// (Added by 20260527000000-add-lemmas-and-translations.ts; rerun
// `bun run model:generate` after deploy to confirm the regenerated file
// matches.)

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type LemmasStrongs = string;

/**
 * Universal (language-agnostic) lemma metadata. Per-language fields
 * (basic_gloss, semantic_range, pos, notes, related) live in
 * `lemma_translations`. The `loaded` flag flags theologically tap-worthy
 * lemmas — only these get translations + render as underlined tokens.
 */
export default interface LemmasTable {
  strongs: ColumnType<LemmasStrongs, LemmasStrongs, LemmasStrongs>;

  lemma: ColumnType<string, string, string>;

  translit: ColumnType<string | null, string | null, string | null>;

  pronunciation: ColumnType<string | null, string | null, string | null>;

  nt_frequency: ColumnType<number | null, number | null, number | null>;

  ot_frequency: ColumnType<number | null, number | null, number | null>;

  loaded: ColumnType<boolean, boolean | undefined, boolean>;
}

export type Lemmas = Selectable<LemmasTable>;
export type NewLemmas = Insertable<LemmasTable>;
export type LemmasUpdate = Updateable<LemmasTable>;
