// @generated
// This file is automatically generated by Kanel. Do not modify manually.
// (Added by 20260527000000-add-lemmas-and-translations.ts; rerun
// `bun run model:generate` after deploy to confirm.)

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type LemmasStrongs = string;

/**
 * One related-lemma cross-reference attached to a lemma's `related`
 * (English) or `translated_related` (per-language) array.
 */
export interface RelatedWord {
  /** Transliteration slug of the related lemma (lookup key into lemmas). */
  translit: string;
  /** Translator-supplied note explaining the relationship. */
  note: string;
}

/**
 * `lemmas` holds the universal lemma metadata + the ENGLISH baseline
 * content. Same shape as `topics`: English lives here directly, non-English
 * goes in `lemma_translations`. The `loaded` flag flags theologically
 * tap-worthy lemmas — only these get translations + render as underlined
 * tokens. Non-loaded lemmas (the ~16K long tail) are stored with universal
 * fields only and null English baseline.
 */
export default interface LemmasTable {
  strongs: ColumnType<LemmasStrongs, LemmasStrongs, LemmasStrongs>;

  // Universal (language-agnostic) ---------------------------------------
  lemma: ColumnType<string, string, string>;
  translit: ColumnType<string | null, string | null, string | null>;
  pronunciation: ColumnType<string | null, string | null, string | null>;
  nt_frequency: ColumnType<number | null, number | null, number | null>;
  ot_frequency: ColumnType<number | null, number | null, number | null>;
  loaded: ColumnType<boolean, boolean | undefined, boolean>;

  // English baseline (null for non-loaded entries) ----------------------
  pos: ColumnType<string | null, string | null, string | null>;
  basic_gloss: ColumnType<string | null, string | null, string | null>;
  semantic_range: ColumnType<string[] | null, string[] | null, string[] | null>;
  notes: ColumnType<string | null, string | null, string | null>;
  related: ColumnType<
    RelatedWord[] | null,
    RelatedWord[] | null,
    RelatedWord[] | null
  >;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type Lemmas = Selectable<LemmasTable>;
export type NewLemmas = Insertable<LemmasTable>;
export type LemmasUpdate = Updateable<LemmasTable>;
