// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { ChaptersChapterId } from "./Chapters";

export type NotesNoteId = string;

/** Represents the table public.notes */
export default interface NotesTable {
  note_id: ColumnType<NotesNoteId, NotesNoteId | undefined, NotesNoteId>;

  user_id: ColumnType<string, string, string>;

  chapter_id: ColumnType<
    ChaptersChapterId,
    ChaptersChapterId,
    ChaptersChapterId
  >;

  content: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | undefined, Date>;

  updated_at: ColumnType<Date, Date | undefined, Date>;
}

export type Notes = Selectable<NotesTable>;

export type NewNotes = Insertable<NotesTable>;

export type NotesUpdate = Updateable<NotesTable>;
