// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { ChaptersChapterId } from "./Chapters";
import type { UserId } from "./User";
import type { VersesVerseId } from "./Verses";

export type NotesNoteId = string;

/** Represents the table public.notes */
export default interface NotesTable {
  note_id: ColumnType<NotesNoteId, NotesNoteId | undefined, NotesNoteId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  chapter_id: ColumnType<
    ChaptersChapterId,
    ChaptersChapterId,
    ChaptersChapterId
  >;

  verse_id: ColumnType<
    VersesVerseId | null,
    VersesVerseId | null,
    VersesVerseId | null
  >;

  content: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Notes = Selectable<NotesTable>;

export type NewNotes = Insertable<NotesTable>;

export type NotesUpdate = Updateable<NotesTable>;
