// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { UserId } from "./User";

export type NotificationBroadcastsId = string;

/** Represents the table public.notification_broadcasts */
export default interface NotificationBroadcastsTable {
  id: ColumnType<
    NotificationBroadcastsId,
    NotificationBroadcastsId | undefined,
    NotificationBroadcastsId
  >;

  admin_user_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  title: ColumnType<string, string, string>;

  body: ColumnType<string, string, string>;

  deep_link: ColumnType<string | null, string | null, string | null>;

  recipient_count: ColumnType<number, number, number>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type NotificationBroadcasts = Selectable<NotificationBroadcastsTable>;

export type NewNotificationBroadcasts = Insertable<NotificationBroadcastsTable>;

export type NotificationBroadcastsUpdate =
  Updateable<NotificationBroadcastsTable>;
