// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.prompt_status_enum */
enum PromptStatusEnum {
  active = "active",
  inactive = "inactive",
}

export default PromptStatusEnum;
