// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as BatchJobsTable } from "./BatchJobs";
import type { default as BibleVersionsTable } from "./BibleVersions";
import type { default as BooksTable } from "./Books";
import type { default as ChaptersTable } from "./Chapters";
import type { default as ConversationsTable } from "./Conversations";
import type { default as ExplanationRatingsTable } from "./ExplanationRatings";
import type { default as ExplanationsTable } from "./Explanations";
import type { default as FavoritesTable } from "./Favorites";
import type { default as GenresTable } from "./Genres";
import type { default as KyselyMigrationTable } from "./KyselyMigration";
import type { default as KyselyMigrationLockTable } from "./KyselyMigrationLock";
import type { default as MessagesTable } from "./Messages";
import type { default as NotesTable } from "./Notes";
import type { default as PromptsTable } from "./Prompts";
import type { default as SubtitlesTable } from "./Subtitles";
import type { default as UserTable } from "./User";
import type { default as UserProgressTable } from "./UserProgress";
import type { default as UserPromptTemplatesTable } from "./UserPromptTemplates";
import type { default as VersesTable } from "./Verses";

export default interface PublicSchema {
  kysely_migration: KyselyMigrationTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  user: UserTable;

  genres: GenresTable;

  books: BooksTable;

  chapters: ChaptersTable;

  subtitles: SubtitlesTable;

  verses: VersesTable;

  explanations: ExplanationsTable;

  explanation_ratings: ExplanationRatingsTable;

  conversations: ConversationsTable;

  messages: MessagesTable;

  notes: NotesTable;

  favorites: FavoritesTable;

  user_progress: UserProgressTable;

  prompts: PromptsTable;

  bible_versions: BibleVersionsTable;

  user_prompt_templates: UserPromptTemplatesTable;

  batch_jobs: BatchJobsTable;
}
