// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as AutoHighlightSettingsTable } from "./AutoHighlightSettings";
import type { default as AutoHighlightsTable } from "./AutoHighlights";
import type { default as BatchJobsTable } from "./BatchJobs";
import type { default as BibleVersionsTable } from "./BibleVersions";
import type { default as BookIntroductionsTable } from "./BookIntroductions";
import type { default as BooksTable } from "./Books";
import type { default as ChaptersTable } from "./Chapters";
import type { default as CoachAdminsTable } from "./CoachAdmins";
import type { default as CoachClassesTable } from "./CoachClasses";
import type { default as CoachDatasetMetaTable } from "./CoachDatasetMeta";
import type { default as CoachLeadersTable } from "./CoachLeaders";
import type { default as CoachMonthlyLeaderSummariesTable } from "./CoachMonthlyLeaderSummaries";
import type { default as CoachMonthlyNarrativesTable } from "./CoachMonthlyNarratives";
import type { default as CoachNotesTable } from "./CoachNotes";
import type { default as CoachRecordingLinksTable } from "./CoachRecordingLinks";
import type { default as CoachReportsTable } from "./CoachReports";
import type { default as CoachZoomLinksTable } from "./CoachZoomLinks";
import type { default as ConversationsTable } from "./Conversations";
import type { default as DailyVerseHistoryTable } from "./DailyVerseHistory";
import type { default as DailyVerseTagsTable } from "./DailyVerseTags";
import type { default as DailyVerseToTagTable } from "./DailyVerseToTag";
import type { default as DailyVersesTable } from "./DailyVerses";
import type { default as DeviceTokensTable } from "./DeviceTokens";
import type { default as ExplanationAudioProgressTable } from "./ExplanationAudioProgress";
import type { default as ExplanationAudiosTable } from "./ExplanationAudios";
import type { default as ExplanationLanguagesTable } from "./ExplanationLanguages";
import type { default as ExplanationRatingsTable } from "./ExplanationRatings";
import type { default as ExplanationsTable } from "./Explanations";
import type { default as FavoritesTable } from "./Favorites";
import type { default as GenresTable } from "./Genres";
import type { default as HighlightThemesTable } from "./HighlightThemes";
import type { default as JesusCollectionEntriesTable } from "./JesusCollectionEntries";
import type { default as JesusCollectionEventsTable } from "./JesusCollectionEvents";
import type { default as JesusCollectionsTable } from "./JesusCollections";
import type { default as JesusEntriesTable } from "./JesusEntries";
import type { default as JesusEntryExplanationsTable } from "./JesusEntryExplanations";
import type { default as JesusEntryReferencesTable } from "./JesusEntryReferences";
import type { default as JesusEntryThemesTable } from "./JesusEntryThemes";
import type { default as JesusEntryTranslationsTable } from "./JesusEntryTranslations";
import type { default as JesusEventExplanationsTable } from "./JesusEventExplanations";
import type { default as JesusEventPassagesTable } from "./JesusEventPassages";
import type { default as JesusEventPeopleTable } from "./JesusEventPeople";
import type { default as JesusEventReactionsTable } from "./JesusEventReactions";
import type { default as JesusEventRevealsTable } from "./JesusEventReveals";
import type { default as JesusEventThemesTable } from "./JesusEventThemes";
import type { default as JesusEventsTable } from "./JesusEvents";
import type { default as JesusFacetsTable } from "./JesusFacets";
import type { default as JesusLabelTranslationsTable } from "./JesusLabelTranslations";
import type { default as JesusPeriodsTable } from "./JesusPeriods";
import type { default as JesusThemesTable } from "./JesusThemes";
import type { default as JesusTopicBriefsTable } from "./JesusTopicBriefs";
import type { default as KyselyMigrationTable } from "./KyselyMigration";
import type { default as KyselyMigrationLockTable } from "./KyselyMigrationLock";
import type { default as LemmaTranslationsTable } from "./LemmaTranslations";
import type { default as LemmasTable } from "./Lemmas";
import type { default as MessagesTable } from "./Messages";
import type { default as NotesTable } from "./Notes";
import type { default as NotificationBroadcastsTable } from "./NotificationBroadcasts";
import type { default as PromptsTable } from "./Prompts";
import type { default as RefreshTokensTable } from "./RefreshTokens";
import type { default as StudiesTable } from "./Studies";
import type { default as StudyLabelsTable } from "./StudyLabels";
import type { default as StudyTermTranslationsTable } from "./StudyTermTranslations";
import type { default as StudyTranslationsTable } from "./StudyTranslations";
import type { default as SubtitlesTable } from "./Subtitles";
import type { default as SupportConversationsTable } from "./SupportConversations";
import type { default as SupportMessagesTable } from "./SupportMessages";
import type { default as TopicExplanationsTable } from "./TopicExplanations";
import type { default as TopicReferencesTable } from "./TopicReferences";
import type { default as TopicTranslationsTable } from "./TopicTranslations";
import type { default as TopicsTable } from "./Topics";
import type { default as TranslationJobsTable } from "./TranslationJobs";
import type { default as TranslationTemplatesTable } from "./TranslationTemplates";
import type { default as UserTable } from "./User";
import type { default as UserProgressTable } from "./UserProgress";
import type { default as UserPromptTemplatesTable } from "./UserPromptTemplates";
import type { default as UserRecentlyViewedBooksTable } from "./UserRecentlyViewedBooks";
import type { default as UserSsoAccountsTable } from "./UserSsoAccounts";
import type { default as UserThemePreferencesTable } from "./UserThemePreferences";
import type { default as UserViewedBookIntroductionsTable } from "./UserViewedBookIntroductions";
import type { default as VerseHighlightsTable } from "./VerseHighlights";
import type { default as VersesTable } from "./Verses";
import type { default as VersionBookNamesTable } from "./VersionBookNames";

export default interface PublicSchema {
  kysely_migration: KyselyMigrationTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  user: UserTable;

  genres: GenresTable;

  books: BooksTable;

  chapters: ChaptersTable;

  subtitles: SubtitlesTable;

  verses: VersesTable;

  explanations: ExplanationsTable;

  explanation_ratings: ExplanationRatingsTable;

  conversations: ConversationsTable;

  messages: MessagesTable;

  favorites: FavoritesTable;

  user_progress: UserProgressTable;

  prompts: PromptsTable;

  bible_versions: BibleVersionsTable;

  lemmas: LemmasTable;

  lemma_translations: LemmaTranslationsTable;

  user_prompt_templates: UserPromptTemplatesTable;

  batch_jobs: BatchJobsTable;

  verse_highlights: VerseHighlightsTable;

  explanation_languages: ExplanationLanguagesTable;

  topics: TopicsTable;

  topic_references: TopicReferencesTable;

  topic_explanations: TopicExplanationsTable;

  topic_translations: TopicTranslationsTable;

  jesus_periods: JesusPeriodsTable;

  jesus_themes: JesusThemesTable;

  jesus_entries: JesusEntriesTable;

  jesus_entry_references: JesusEntryReferencesTable;

  jesus_entry_themes: JesusEntryThemesTable;

  jesus_collections: JesusCollectionsTable;

  jesus_collection_entries: JesusCollectionEntriesTable;

  jesus_entry_translations: JesusEntryTranslationsTable;

  jesus_label_translations: JesusLabelTranslationsTable;

  jesus_entry_explanations: JesusEntryExplanationsTable;

  jesus_events: JesusEventsTable;

  jesus_event_passages: JesusEventPassagesTable;

  jesus_facets: JesusFacetsTable;

  jesus_event_reveals: JesusEventRevealsTable;

  jesus_event_reactions: JesusEventReactionsTable;

  jesus_event_people: JesusEventPeopleTable;

  jesus_event_themes: JesusEventThemesTable;

  jesus_event_explanations: JesusEventExplanationsTable;

  jesus_topic_briefs: JesusTopicBriefsTable;

  jesus_collection_events: JesusCollectionEventsTable;

  user_recently_viewed_books: UserRecentlyViewedBooksTable;

  coach_zoom_links: CoachZoomLinksTable;

  coach_classes: CoachClassesTable;

  coach_leaders: CoachLeadersTable;

  coach_recording_links: CoachRecordingLinksTable;

  coach_dataset_meta: CoachDatasetMetaTable;

  coach_notes: CoachNotesTable;

  coach_reports: CoachReportsTable;

  coach_admins: CoachAdminsTable;

  coach_monthly_narratives: CoachMonthlyNarrativesTable;

  coach_monthly_leader_summaries: CoachMonthlyLeaderSummariesTable;

  notes: NotesTable;

  refresh_tokens: RefreshTokensTable;

  highlight_themes: HighlightThemesTable;

  auto_highlights: AutoHighlightsTable;

  user_theme_preferences: UserThemePreferencesTable;

  auto_highlight_settings: AutoHighlightSettingsTable;

  user_sso_accounts: UserSsoAccountsTable;

  book_introductions: BookIntroductionsTable;

  user_viewed_book_introductions: UserViewedBookIntroductionsTable;

  support_conversations: SupportConversationsTable;

  support_messages: SupportMessagesTable;

  translation_templates: TranslationTemplatesTable;

  explanation_audios: ExplanationAudiosTable;

  explanation_audio_progress: ExplanationAudioProgressTable;

  version_book_names: VersionBookNamesTable;

  studies: StudiesTable;

  study_labels: StudyLabelsTable;

  study_term_translations: StudyTermTranslationsTable;

  study_translations: StudyTranslationsTable;

  daily_verse_tags: DailyVerseTagsTable;

  daily_verses: DailyVersesTable;

  daily_verse_to_tag: DailyVerseToTagTable;

  daily_verse_history: DailyVerseHistoryTable;

  translation_jobs: TranslationJobsTable;

  device_tokens: DeviceTokensTable;

  notification_broadcasts: NotificationBroadcastsTable;
}
