// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { UserId } from "./User";

export type RefreshTokensId = string;

/** Represents the table public.refresh_tokens */
export default interface RefreshTokensTable {
  id: ColumnType<RefreshTokensId, RefreshTokensId | undefined, RefreshTokensId>;

  user_id: ColumnType<UserId, UserId, UserId>;

  token: ColumnType<string, string, string>;

  user_agent: ColumnType<string | null, string | null, string | null>;

  ip_address: ColumnType<string | null, string | null, string | null>;

  expires_at: ColumnType<Date, Date | string, Date | string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  last_used_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type RefreshTokens = Selectable<RefreshTokensTable>;

export type NewRefreshTokens = Insertable<RefreshTokensTable>;

export type RefreshTokensUpdate = Updateable<RefreshTokensTable>;
