// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.role_enum */
enum RoleEnum {
  user = "user",
  assistant = "assistant",
}

export default RoleEnum;
