// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.sso_provider_enum */
enum SsoProviderEnum {
  google = "google",
  apple = "apple",
}

export default SsoProviderEnum;
