// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.status_enum */
enum StatusEnum {
  active = "active",
  inactive = "inactive",
  archived = "archived",
}

export default StatusEnum;
