// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType } from "kysely";

/** Represents the table public.study_term_translations */
export default interface StudyTermTranslationsTable {
  language_code: ColumnType<string, string, string>;

  term_type: ColumnType<string, string, string>;

  source_en: ColumnType<string, string, string>;

  target_term: ColumnType<string, string, string>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}
