// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";

export type StudiesStudyId = number;

/** Represents the table public.studies */
export default interface StudiesTable {
  study_id: ColumnType<
    StudiesStudyId,
    StudiesStudyId | undefined,
    StudiesStudyId
  >;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  chapter: ColumnType<number, number, number>;

  content: ColumnType<unknown, unknown, unknown>;

  content_hash: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type Studies = Selectable<StudiesTable>;

export type NewStudies = Insertable<StudiesTable>;

export type StudiesUpdate = Updateable<StudiesTable>;
