// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType } from "kysely";

/** Represents the table public.study_labels */
export default interface StudyLabelsTable {
  language_code: ColumnType<string, string, string>;

  labels: ColumnType<unknown, unknown, unknown>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}
