// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { StudiesStudyId } from "./Studies";

export type StudyTranslationsTranslationId = string;

/** Represents the table public.study_translations */
export default interface StudyTranslationsTable {
  translation_id: ColumnType<
    StudyTranslationsTranslationId,
    StudyTranslationsTranslationId | undefined,
    StudyTranslationsTranslationId
  >;

  study_id: ColumnType<StudiesStudyId, StudiesStudyId, StudiesStudyId>;

  language_code: ColumnType<string, string, string>;

  translated_content: ColumnType<unknown, unknown, unknown>;

  source_content_hash: ColumnType<string | null, string | null, string | null>;

  source: ColumnType<string | null, string | null, string | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type StudyTranslations = Selectable<StudyTranslationsTable>;

export type NewStudyTranslations = Insertable<StudyTranslationsTable>;

export type StudyTranslationsUpdate = Updateable<StudyTranslationsTable>;
