// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { SupportConversationsId } from "./SupportConversations";
import type { default as SupportSenderEnum } from "./SupportSenderEnum";
import type { UserId } from "./User";

export type SupportMessagesId = string;

/** Represents the table public.support_messages */
export default interface SupportMessagesTable {
  id: ColumnType<
    SupportMessagesId,
    SupportMessagesId | undefined,
    SupportMessagesId
  >;

  conversation_id: ColumnType<
    SupportConversationsId,
    SupportConversationsId,
    SupportConversationsId
  >;

  user_id: ColumnType<UserId, UserId, UserId>;

  text: ColumnType<string, string, string>;

  sender: ColumnType<SupportSenderEnum, SupportSenderEnum, SupportSenderEnum>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type SupportMessages = Selectable<SupportMessagesTable>;

export type NewSupportMessages = Insertable<SupportMessagesTable>;

export type SupportMessagesUpdate = Updateable<SupportMessagesTable>;
