// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.support_status_enum */
enum SupportStatusEnum {
  open = "open",
  resolved = "resolved",
}

export default SupportStatusEnum;
