// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.support_sender_enum */
enum SupportSenderEnum {
  user = "user",
  support = "support",
}

export default SupportSenderEnum;
