// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { default as SupportStatusEnum } from "./SupportStatusEnum";
import type { UserId } from "./User";

export type SupportConversationsId = string;

/** Represents the table public.support_conversations */
export default interface SupportConversationsTable {
  id: ColumnType<
    SupportConversationsId,
    SupportConversationsId | undefined,
    SupportConversationsId
  >;

  user_id: ColumnType<UserId, UserId, UserId>;

  subject: ColumnType<string | null, string | null, string | null>;

  slack_thread_ts: ColumnType<string, string, string>;

  status: ColumnType<
    SupportStatusEnum,
    SupportStatusEnum | undefined,
    SupportStatusEnum
  >;

  last_message_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type SupportConversations = Selectable<SupportConversationsTable>;

export type NewSupportConversations = Insertable<SupportConversationsTable>;

export type SupportConversationsUpdate = Updateable<SupportConversationsTable>;
