// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.testament_enum */
enum TestamentEnum {
  OT = "OT",
  NT = "NT",
}

export default TestamentEnum;
