// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { TopicsTopicId } from "./Topics";

export type TopicExplanationsExplanationId = string;

/** Represents the table public.topic_explanations */
export default interface TopicExplanationsTable {
  explanation_id: ColumnType<
    TopicExplanationsExplanationId,
    TopicExplanationsExplanationId | undefined,
    TopicExplanationsExplanationId
  >;

  topic_id: ColumnType<TopicsTopicId, TopicsTopicId, TopicsTopicId>;

  type: ColumnType<string, string, string>;

  explanation: ColumnType<string, string, string>;

  language_code: ColumnType<string, string, string>;

  version: ColumnType<number | null, number | null, number | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  default: ColumnType<boolean | null, boolean | null, boolean | null>;

  parent_explanation_id: ColumnType<
    TopicExplanationsExplanationId | null,
    TopicExplanationsExplanationId | null,
    TopicExplanationsExplanationId | null
  >;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type TopicExplanations = Selectable<TopicExplanationsTable>;

export type NewTopicExplanations = Insertable<TopicExplanationsTable>;

export type TopicExplanationsUpdate = Updateable<TopicExplanationsTable>;
