// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type TopicsTopicId = string;

/** Represents the table public.topics */
export default interface TopicsTable {
  topic_id: ColumnType<TopicsTopicId, TopicsTopicId | undefined, TopicsTopicId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  category: ColumnType<string, string, string>;

  sort_order: ColumnType<number | null, number | null, number | null>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type Topics = Selectable<TopicsTable>;

export type NewTopics = Insertable<TopicsTable>;

export type TopicsUpdate = Updateable<TopicsTable>;
