// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { TopicsTopicId } from "./Topics";

export type TopicTranslationsTranslationId = string;

/** Represents the table public.topic_translations */
export default interface TopicTranslationsTable {
  translation_id: ColumnType<
    TopicTranslationsTranslationId,
    TopicTranslationsTranslationId | undefined,
    TopicTranslationsTranslationId
  >;

  topic_id: ColumnType<TopicsTopicId, TopicsTopicId, TopicsTopicId>;

  language_code: ColumnType<string, string, string>;

  translated_name: ColumnType<string, string, string>;

  translated_description: ColumnType<
    string | null,
    string | null,
    string | null
  >;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type TopicTranslations = Selectable<TopicTranslationsTable>;

export type NewTopicTranslations = Insertable<TopicTranslationsTable>;

export type TopicTranslationsUpdate = Updateable<TopicTranslationsTable>;
