// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { TopicsTopicId } from "./Topics";

export type TopicReferencesReferenceId = string;

/** Represents the table public.topic_references */
export default interface TopicReferencesTable {
  reference_id: ColumnType<
    TopicReferencesReferenceId,
    TopicReferencesReferenceId | undefined,
    TopicReferencesReferenceId
  >;

  topic_id: ColumnType<TopicsTopicId, TopicsTopicId, TopicsTopicId>;

  content: ColumnType<string, string, string>;

  is_active: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_by_admin: ColumnType<boolean | null, boolean | null, boolean | null>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  version: ColumnType<number, number | undefined, number>;
}

export type TopicReferences = Selectable<TopicReferencesTable>;

export type NewTopicReferences = Insertable<TopicReferencesTable>;

export type TopicReferencesUpdate = Updateable<TopicReferencesTable>;
