// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

export type TranslationTemplatesTemplateId = number;

/** Represents the table public.translation_templates */
export default interface TranslationTemplatesTable {
  template_id: ColumnType<
    TranslationTemplatesTemplateId,
    TranslationTemplatesTemplateId | undefined,
    TranslationTemplatesTemplateId
  >;

  language_code: ColumnType<string, string, string>;

  type: ColumnType<string, string, string>;

  title_template: ColumnType<string, string, string>;

  created_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type TranslationTemplates = Selectable<TranslationTemplatesTable>;

export type NewTranslationTemplates = Insertable<TranslationTemplatesTable>;

export type TranslationTemplatesUpdate = Updateable<TranslationTemplatesTable>;
