// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";
import type { UserId } from "./User";

export type UserViewedBookIntroductionsId = number;

/** Represents the table public.user_viewed_book_introductions */
export default interface UserViewedBookIntroductionsTable {
  id: ColumnType<
    UserViewedBookIntroductionsId,
    UserViewedBookIntroductionsId | undefined,
    UserViewedBookIntroductionsId
  >;

  user_id: ColumnType<UserId, UserId, UserId>;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  viewed_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserViewedBookIntroductions =
  Selectable<UserViewedBookIntroductionsTable>;

export type NewUserViewedBookIntroductions =
  Insertable<UserViewedBookIntroductionsTable>;

export type UserViewedBookIntroductionsUpdate =
  Updateable<UserViewedBookIntroductionsTable>;
