// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { default as HighlightColorEnum } from "./HighlightColorEnum";
import type { HighlightThemesThemeId } from "./HighlightThemes";
import type { UserId } from "./User";

/** Represents the table public.user_theme_preferences */
export default interface UserThemePreferencesTable {
  user_id: ColumnType<UserId, UserId, UserId>;

  theme_id: ColumnType<
    HighlightThemesThemeId,
    HighlightThemesThemeId,
    HighlightThemesThemeId
  >;

  is_enabled: ColumnType<boolean | null, boolean | null, boolean | null>;

  custom_color: ColumnType<
    HighlightColorEnum | null,
    HighlightColorEnum | null,
    HighlightColorEnum | null
  >;

  relevance_threshold: ColumnType<number | null, number | null, number | null>;

  updated_at: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;
}

export type UserThemePreferences = Selectable<UserThemePreferencesTable>;

export type NewUserThemePreferences = Insertable<UserThemePreferencesTable>;

export type UserThemePreferencesUpdate = Updateable<UserThemePreferencesTable>;
