// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { default as SsoProviderEnum } from "./SsoProviderEnum";
import type { UserId } from "./User";

export type UserSsoAccountsId = string;

/** Represents the table public.user_sso_accounts */
export default interface UserSsoAccountsTable {
  id: ColumnType<
    UserSsoAccountsId,
    UserSsoAccountsId | undefined,
    UserSsoAccountsId
  >;

  user_id: ColumnType<UserId, UserId, UserId>;

  provider: ColumnType<SsoProviderEnum, SsoProviderEnum, SsoProviderEnum>;

  provider_user_id: ColumnType<string, string, string>;

  email: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserSsoAccounts = Selectable<UserSsoAccountsTable>;

export type NewUserSsoAccounts = Insertable<UserSsoAccountsTable>;

export type UserSsoAccountsUpdate = Updateable<UserSsoAccountsTable>;
