// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BooksBookId } from "./Books";
import type { UserId } from "./User";

export type UserRecentlyViewedBooksId = number;

/** Represents the table public.user_recently_viewed_books */
export default interface UserRecentlyViewedBooksTable {
  id: ColumnType<
    UserRecentlyViewedBooksId,
    UserRecentlyViewedBooksId | undefined,
    UserRecentlyViewedBooksId
  >;

  user_id: ColumnType<UserId, UserId, UserId>;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  last_viewed_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type UserRecentlyViewedBooks = Selectable<UserRecentlyViewedBooksTable>;

export type NewUserRecentlyViewedBooks =
  Insertable<UserRecentlyViewedBooksTable>;

export type UserRecentlyViewedBooksUpdate =
  Updateable<UserRecentlyViewedBooksTable>;
