// @generated
// This file is automatically generated by Kanel. Do not modify manually.
// (The `tokens` column was added by 20260526150000-add-tokens-to-verses.ts;
// rerun `bun run model:generate` after deploy to confirm the regenerated
// file matches.)

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BibleVersionsId } from "./BibleVersions";
import type { ChaptersChapterId } from "./Chapters";

export type VersesVerseId = number;

/**
 * One token in a Strong's-tagged verse. Each verse with tagging stores an
 * ordered array of these in the `tokens` JSONB column. Joining each token's
 * `text` reproduces the verse text byte-for-byte — the lossless-join
 * invariant the chapter endpoint enforces when `?tagged=1` is requested.
 */
export interface VerseToken {
  text: string;
  /** Strong's number in canonical G####/H#### form (4-digit padded). */
  strongs?: string;
  /** Secondary Strong's for compound surface words (e.g. "Jesucristo"). */
  strongs_alt?: string[];
  /** Optional LLM-alignment confidence 0..1 (omitted for published sources). */
  confidence?: number;
}

/** Represents the table public.verses */
export default interface VersesTable {
  verse_id: ColumnType<VersesVerseId, VersesVerseId | undefined, VersesVerseId>;

  chapter_id: ColumnType<
    ChaptersChapterId,
    ChaptersChapterId,
    ChaptersChapterId
  >;

  verse_number: ColumnType<number, number, number>;

  text: ColumnType<string, string, string>;

  version_id: ColumnType<BibleVersionsId, BibleVersionsId, BibleVersionsId>;

  tokens: ColumnType<
    VerseToken[] | null,
    VerseToken[] | null | undefined,
    VerseToken[] | null
  >;
}

export type Verses = Selectable<VersesTable>;

export type NewVerses = Insertable<VersesTable>;

export type VersesUpdate = Updateable<VersesTable>;
