// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { BibleVersionsId } from "./BibleVersions";
import type { BooksBookId } from "./Books";

/** Represents the table public.version_book_names */
export default interface VersionBookNamesTable {
  version_id: ColumnType<BibleVersionsId, BibleVersionsId, BibleVersionsId>;

  book_id: ColumnType<BooksBookId, BooksBookId, BooksBookId>;

  name: ColumnType<string, string, string>;
}

export type VersionBookNames = Selectable<VersionBookNamesTable>;

export type NewVersionBookNames = Insertable<VersionBookNamesTable>;

export type VersionBookNamesUpdate = Updateable<VersionBookNamesTable>;
