// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { ChaptersChapterId } from "./Chapters";
import type { default as HighlightColorEnum } from "./HighlightColorEnum";
import type { UserId } from "./User";

export type VerseHighlightsHighlightId = number;

/** Represents the table public.verse_highlights */
export default interface VerseHighlightsTable {
  highlight_id: ColumnType<
    VerseHighlightsHighlightId,
    VerseHighlightsHighlightId | undefined,
    VerseHighlightsHighlightId
  >;

  user_id: ColumnType<UserId, UserId, UserId>;

  chapter_id: ColumnType<
    ChaptersChapterId,
    ChaptersChapterId,
    ChaptersChapterId
  >;

  start_verse: ColumnType<number, number, number>;

  end_verse: ColumnType<number, number, number>;

  start_char: ColumnType<
    number | null,
    number | null | undefined,
    number | null
  >;

  end_char: ColumnType<number | null, number | null | undefined, number | null>;

  selected_text: ColumnType<
    string | null,
    string | null | undefined,
    string | null
  >;

  color: ColumnType<
    HighlightColorEnum,
    HighlightColorEnum | undefined,
    HighlightColorEnum
  >;

  created_at: ColumnType<Date, Date | undefined, Date>;

  updated_at: ColumnType<Date, Date | undefined, Date>;
}

export type VerseHighlights = Selectable<VerseHighlightsTable>;

export type NewVerseHighlights = Insertable<VerseHighlightsTable>;

export type VerseHighlightsUpdate = Updateable<VerseHighlightsTable>;
