import path from "node:path";
/**
 * Production CLI entry for the Strong's-tokens seed loader.
 *
 * Bundled to dist/ingest-strongs-tokens.js alongside dist/index.js so it
 * can be run inside the deployed backend container after a release:
 *
 *   bun ./dist/ingest-strongs-tokens.js --input <dir> [--version KEY]
 *
 * The <dir> must contain `<key>_tokens.jsonl` files generated by
 * scripts/strongs-ingest/ (e.g. rvr09_tokens.jsonl). One-off seed: place
 * the data inside the container via `docker cp` or a volume mount, run
 * this script, then remove. See scripts/strongs-ingest/README.md for how
 * to produce the JSONL files from source CrossWire SWORD modules.
 *
 * Idempotent: re-running overwrites the tokens array in place. Verses
 * missing from the DB are never inserted (the multi-version ingest loader
 * owns row creation).
 */
import { parseArgs } from "node:util";
import { main } from "backend-base/src/bible/ingest-strongs-tokens";

const { values } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    input: { type: "string" },
    version: { type: "string" },
  },
  allowPositionals: true,
});

if (!values.input) {
  console.error(
    "usage: bun ./dist/ingest-strongs-tokens.js --input <dir> [--version KEY]",
  );
  process.exit(2);
}

main(path.resolve(values.input), values.version)
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
