import type { db } from "../shared/shared.plugin";
import { UserService } from "../user/user.service";
import coachDataJson from "./coach.data.json";
import { CoachRepository } from "./repository/coach.repository";

// ─── Dataset shape (bundled, generated by the coaching pipeline) ───────────
// Source: bible-study-coaching/scripts/export-coach-portal-data.js →
// coach-portal-data/portal.json, copied here as coach.data.json.

export interface CoachCluster {
  name: string;
  weight: number;
  scorePct: number | null;
  contribution: number;
}

export interface CoachDimension {
  n: number;
  name: string;
  score: number | null;
  /** Coach's per-dimension rationale ("why this score"); may be empty. */
  note?: string;
}

export interface CoachReport {
  id: string;
  date: string;
  dateLabel: string;
  session: string;
  topic: string;
  duration: string;
  attendees: number;
  newcomers: number;
  score: number;
  base: number;
  newcomerBonus: number;
  sizeBonus: number;
  status: string;
  statusEmoji: string;
  clusters: CoachCluster[];
  dimensions: CoachDimension[];
  bigIdeas: string[];
  feedback: CoachFeedback;
  docUrl: string;
  pdfUrl: string;
}

/** Coaching feedback rendered directly on the portal (no Google Docs hop). */
export interface CoachFeedback {
  headline: string;
  strengths: string[];
  improvements: string[];
  recommendations: string[];
}

interface CoachRecord {
  id: string;
  name: string;
  email: string;
  group: string;
  coachName: string;
  isCoach: boolean;
  zoomLink: string;
  reports: CoachReport[];
}

interface CoachDataset {
  schemaVersion: number;
  generatedAt: string;
  model: string;
  admins?: string[];
  clusters: { name: string; weight: number }[];
  statusBands: { min: number; label: string; emoji: string }[];
  coaches: CoachRecord[];
}

const coachData = coachDataJson as unknown as CoachDataset;

/** Compact roster row for the admin oversight view. */
export interface CoachSummary {
  id: string;
  name: string;
  group: string;
  coachName: string;
  sessionCount: number;
  latest: {
    date: string;
    dateLabel: string;
    score: number;
    status: string;
    statusEmoji: string;
  } | null;
}

export interface TrendRow {
  date: string;
  dateLabel: string;
  [key: string]: number | string | null;
}

export interface CoachTrends {
  scoreSeries: {
    date: string;
    dateLabel: string;
    session: string;
    score: number;
    status: string;
  }[];
  clusterSeries: TrendRow[];
  dimensionSeries: TrendRow[];
  delta: {
    score: number;
    from: number;
    to: number;
    fromLabel: string;
    toLabel: string;
  } | null;
}

export class CoachService {
  private readonly userService: UserService;
  private readonly coachRepository: CoachRepository;

  constructor(private readonly db: db) {
    this.userService = new UserService(db);
    this.coachRepository = new CoachRepository(db);
  }

  /** Roster lookup by email (the join key between a VerseMate account and a
   *  coaching record). Case-insensitive. */
  private findByEmail(email: string): CoachRecord | null {
    const target = email.trim().toLowerCase();
    return coachData.coaches.find((c) => c.email === target) ?? null;
  }

  private findById(coachId: string): CoachRecord | null {
    return coachData.coaches.find((c) => c.id === coachId) ?? null;
  }

  private static isAdminEmail(email: string): boolean {
    const target = email.trim().toLowerCase();
    return (coachData.admins ?? []).includes(target);
  }

  /** The signed-in user's email (lowercased), or null. */
  private async emailFor(userId: string): Promise<string | null> {
    const user = await this.userService.findOne(userId);
    return user?.email ? user.email.trim().toLowerCase() : null;
  }

  /** Resolve the signed-in user to their coaching record, or null if the
   *  account is not in the roster (authenticated but not a coach). */
  private async recordFor(userId: string): Promise<CoachRecord | null> {
    const email = await this.emailFor(userId);
    return email ? this.findByEmail(email) : null;
  }

  async isCoach(userId: string): Promise<boolean> {
    return (await this.recordFor(userId)) !== null;
  }

  /** True when the signed-in user is a program admin (oversight over every
   *  leader). Admins need not be coachees. */
  async isAdmin(userId: string): Promise<boolean> {
    const email = await this.emailFor(userId);
    return email ? CoachService.isAdminEmail(email) : false;
  }

  async getMe(userId: string) {
    const email = await this.emailFor(userId);
    if (!email) return null;

    const record = this.findByEmail(email);
    const admin = CoachService.isAdminEmail(email);
    // Authenticated but neither a coachee nor an admin → not a coaching account.
    if (!record && !admin) return null;

    const stored = record
      ? await this.coachRepository.getZoomLink(userId)
      : null;
    return {
      isCoach: !!record,
      isAdmin: admin,
      profile: record
        ? {
            id: record.id,
            name: record.name,
            email: record.email,
            group: record.group,
            coachName: record.coachName,
          }
        : null,
      zoomLink: stored ?? record?.zoomLink ?? "",
      model: coachData.model,
      clusters: coachData.clusters,
      statusBands: coachData.statusBands,
    };
  }

  async getReports(userId: string): Promise<CoachReport[] | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return record.reports;
  }

  async getTrends(userId: string): Promise<CoachTrends | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return CoachService.buildTrends(record.reports);
  }

  // ─── Admin oversight (every leader) ──────────────────────────────────────

  /** Roster summary for the admin landing view. Pure over the dataset —
   *  the plugin gates access on isAdmin(). */
  listCoaches(): CoachSummary[] {
    return coachData.coaches.map((c) => {
      // reports are stored newest-first.
      const latest = c.reports[0] ?? null;
      return {
        id: c.id,
        name: c.name,
        group: c.group,
        coachName: c.coachName,
        sessionCount: c.reports.length,
        latest: latest
          ? {
              date: latest.date,
              dateLabel: latest.dateLabel,
              score: latest.score,
              status: latest.status,
              statusEmoji: latest.statusEmoji,
            }
          : null,
      };
    });
  }

  /** A specific coach's reports by id (admin drill-in). null → unknown id. */
  getReportsById(coachId: string): CoachReport[] | null {
    return this.findById(coachId)?.reports ?? null;
  }

  /** A specific coach's trends by id (admin drill-in). null → unknown id. */
  getTrendsById(coachId: string): CoachTrends | null {
    const record = this.findById(coachId);
    return record ? CoachService.buildTrends(record.reports) : null;
  }

  /** Profile header for an admin viewing a specific coach. */
  getProfileById(coachId: string): {
    id: string;
    name: string;
    group: string;
    coachName: string;
  } | null {
    const c = this.findById(coachId);
    return c
      ? { id: c.id, name: c.name, group: c.group, coachName: c.coachName }
      : null;
  }

  async setZoomLink(userId: string, zoomLink: string): Promise<string | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return this.coachRepository.setZoomLink(userId, zoomLink);
  }

  /** Derive the chart series from a coach's reports. Pure — exported shape
   *  matches the web client's CoachTrends. */
  static buildTrends(reports: CoachReport[]): CoachTrends {
    const chrono = [...reports].sort((a, b) => (a.date < b.date ? -1 : 1));

    const scoreSeries = chrono.map((r) => ({
      date: r.date,
      dateLabel: r.dateLabel,
      session: r.session,
      score: r.score,
      status: r.status,
    }));

    const clusterSeries: TrendRow[] = chrono.map((r) => {
      const row: TrendRow = { date: r.date, dateLabel: r.dateLabel };
      for (const c of r.clusters) row[c.name] = c.contribution;
      return row;
    });

    const dimensionSeries: TrendRow[] = chrono.map((r) => {
      const row: TrendRow = { date: r.date, dateLabel: r.dateLabel };
      for (const d of r.dimensions) row[d.name] = d.score;
      return row;
    });

    let delta: CoachTrends["delta"] = null;
    if (chrono.length >= 2) {
      const latest = chrono[chrono.length - 1];
      const prev = chrono[chrono.length - 2];
      delta = {
        score: Math.round((latest.score - prev.score) * 100) / 100,
        from: prev.score,
        to: latest.score,
        fromLabel: prev.dateLabel,
        toLabel: latest.dateLabel,
      };
    }

    return { scoreSeries, clusterSeries, dimensionSeries, delta };
  }
}
