import { createHash } from "node:crypto";

import { CoachInvite, CoachNote, render } from "../../../emails";
import { ConflictError, ValidationError } from "../common/errors";
import type { db } from "../shared/shared.plugin";
import { UserService } from "../user/user.service";
import { rowToReport, rowToSummary } from "./coach-store.transform";
import coachDataJson from "./coach.data.json";
import { CoachReportsRepository } from "./repository/coach-reports.repository";
import {
  type AddedLeaderRow,
  type CoachClassInput,
  type CoachClassRow,
  type CoachNoteRow,
  CoachRepository,
} from "./repository/coach.repository";

/** A registered class as returned to the portal. */
export type CoachClass = CoachClassRow;

/** One class in the admin export — the class plus the leader it belongs to. */
export interface AdminCoachClass extends CoachClassRow {
  leader: { id: string | null; name: string; email: string };
}

/** A minimal mailer contract — satisfied by EmailNotificationConsumer. Kept
 *  local + optional so unit tests can construct CoachService without one. */
export interface CoachMailer {
  sendEmail(data: {
    subject: string;
    to: { name: string; email: string };
    from?: { name: string; email: string };
    text: string;
    html?: string;
  }): Promise<void> | void;
}

// ─── Dataset shape (bundled, generated by the coaching pipeline) ───────────
// Source: bible-study-coaching/scripts/export-coach-portal-data.js →
// coach-portal-data/portal.json, copied here as coach.data.json.

export interface CoachCluster {
  name: string;
  weight: number;
  scorePct: number | null;
  contribution: number;
}

export interface CoachDimension {
  n: number;
  name: string;
  score: number | null;
  /** Coach's per-dimension rationale ("why this score"); may be empty. */
  note?: string;
}

export interface CoachReport {
  id: string;
  date: string;
  dateLabel: string;
  session: string;
  topic: string;
  duration: string;
  attendees: number;
  newcomers: number;
  score: number;
  base: number;
  newcomerBonus: number;
  sizeBonus: number;
  status: string;
  statusEmoji: string;
  clusters: CoachCluster[];
  dimensions: CoachDimension[];
  bigIdeas: string[];
  feedback: CoachFeedback;
  /** Ordered PDF-parity sections rendered after Recommendations. Optional so
   *  reports generated before prose/sections export still type-check. */
  sections?: CoachSection[];
  docUrl: string;
  pdfUrl: string;
  /** Admin-editable recording URL, overlaid from coach_recording_links.
   *  Optional so bundled reports (which don't carry one) still type-check. */
  recordingUrl?: string;
  /** Coaching notes on this session, newest first — overlaid from coach_notes.
   *  Rendered on the admin drill-in and read-only on the leader's dashboard. */
  notes?: CoachNoteView[];
}

/** A coaching note as returned to the portal (DB row minus internals). */
export interface CoachNoteView {
  id: string;
  body: string;
  createdAt: string;
  emailed: boolean;
}

/** One fully-written coaching point: a short title plus prose paragraphs.
 *  Emitted directly by the Bible-Coach pipeline (no Google Docs hop). */
export interface CoachFeedbackPoint {
  title: string;
  paragraphs: string[];
}

/** A timestamped moment inside a report section (Key Moment, timeline entry). */
export interface CoachMoment {
  timestamp?: string;
  detail: string;
}

/** A generic, ordered report section — Key Moments, Session Flow Timeline,
 *  Score Composition, per-dimension notes, etc. Any mix of paragraphs,
 *  bullets, and timestamped moments. */
export interface CoachSection {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  moments?: CoachMoment[];
}

/** Coaching feedback rendered directly on the portal (no Google Docs hop). */
export interface CoachFeedback {
  headline: string;
  strengths: string[];
  improvements: string[];
  recommendations: string[];
  /** Full prose from the pipeline — the expanded (desktop) presentation.
   *  Optional so reports generated before prose export still type-check. */
  overview?: string[];
  strengthsProse?: CoachFeedbackPoint[];
  improvementsProse?: CoachFeedbackPoint[];
  recommendationsProse?: CoachFeedbackPoint[];
}

interface CoachRecord {
  id: string;
  name: string;
  email: string;
  group: string;
  coachName: string;
  isCoach: boolean;
  zoomLink: string;
  reports: CoachReport[];
}

/** Program-wide monthly narrative prose, keyed by YYYY-MM. Generated by the
 *  coaching pipeline (bible-study-coaching/templates/monthly-narrative.js) —
 *  the SAME source the monthly PDF uses — and baked into the dataset so the
 *  portal and the PDF read the same prose. The backend only passes it through. */
export interface CoachMonthlyNarrative {
  executiveSummary: string[];
  trends: string[];
}

// ─── Per-leader monthly summary (full parity with the individual monthly PDF)
// Generated by bible-study-coaching/templates/monthly-narrative.js and baked
// into the dataset; the backend only passes it through. Shapes mirror the
// generator output exactly.

export interface LeaderMonthlyClusterAvg {
  tc: number | null;
  bm: number | null;
  ep: number | null;
  br: number | null;
}
export interface LeaderMonthlyGlanceRow {
  date: string;
  session: string;
  bm: number | null;
  tc: number | null;
  ep: number | null;
  br: number | null;
  composite: number;
  status: string;
}
export interface LeaderMonthlyCluster {
  key: string;
  name: string;
  weight: number;
  avgPct: number | null;
  statusLabel: string;
  strongestDim: { name: string; val: number } | null;
  weakestDim: { name: string; val: number } | null;
  insight: string;
}
export interface LeaderMonthlySessionDetail {
  date: string;
  session: string;
  composite: number;
  status: string;
  dimensions: {
    n: number;
    name: string;
    cluster: string;
    score: number | null;
    note: string;
  }[];
}
export interface LeaderMonthlySummary {
  month: string;
  monthLabel: string;
  priorMonthLabel: string;
  leaderId: string;
  leaderName: string;
  group: string;
  sessionsCount: number;
  composite: number;
  status: { label: string; emoji: string };
  priorComposite: number | null;
  delta: number | null;
  clusterAvg: LeaderMonthlyClusterAvg;
  glance: {
    rows: LeaderMonthlyGlanceRow[];
    avg: {
      bm: number | null;
      tc: number | null;
      ep: number | null;
      br: number | null;
      composite: number;
      status: string;
    };
  };
  trajectory: {
    date: string;
    session: string;
    composite: number;
    status: string;
    delta: number | null;
  }[];
  clusters: LeaderMonthlyCluster[];
  strengths: { text: string; session: string }[];
  growth: { text: string; session: string }[];
  trends: string[];
  conversationGuide: { label: string; q: string }[];
  focus: { clusterName: string; clusterPct: number | null; goals: string[] };
  sessions: LeaderMonthlySessionDetail[];
}

/** What the per-leader monthly-summary endpoints return. */
export interface LeaderMonthlyResponse {
  profile: { id: string; name: string; group: string };
  summary: LeaderMonthlySummary | null;
  /** Months this leader has a summary for, newest first (drives the picker). */
  availableMonths: string[];
}

interface CoachDataset {
  schemaVersion: number;
  generatedAt: string;
  model: string;
  admins?: string[];
  clusters: { name: string; weight: number }[];
  statusBands: { min: number; label: string; emoji: string }[];
  coaches: CoachRecord[];
  /** Optional so pre-v3 datasets (without narratives) still type-check. */
  monthlyNarratives?: Record<string, CoachMonthlyNarrative>;
  /** Per-leader monthly summaries, keyed [coachId][YYYY-MM]. Optional so older
   *  datasets still type-check. */
  monthlyLeaderSummaries?: Record<string, Record<string, LeaderMonthlySummary>>;
}

const coachData = coachDataJson as unknown as CoachDataset;

/** Compact roster row for the admin oversight view. */
export interface CoachSummary {
  id: string;
  name: string;
  group: string;
  coachName: string;
  sessionCount: number;
  latest: {
    date: string;
    dateLabel: string;
    score: number;
    status: string;
    statusEmoji: string;
  } | null;
}

export interface TrendRow {
  date: string;
  dateLabel: string;
  [key: string]: number | string | null;
}

export interface CoachTrends {
  scoreSeries: {
    date: string;
    dateLabel: string;
    session: string;
    score: number;
    status: string;
  }[];
  clusterSeries: TrendRow[];
  dimensionSeries: TrendRow[];
  delta: {
    score: number;
    from: number;
    to: number;
    fromLabel: string;
    toLabel: string;
  } | null;
}

/** One leader's row in the monthly cross-leader analysis. */
export interface MonthlyLeader {
  id: string;
  name: string;
  group: string;
  sessions: number;
  avgScore: number | null;
  status: string;
  statusEmoji: string;
  /** 12-dimension averages for the month (null where the dim was never scored)
   *  — the heatmap row. */
  dimensions: { n: number; name: string; avg: number | null }[];
  /** Change in average composite vs the leader's prior month, or null. */
  delta: number | null;
}

/** Program-wide + per-leader rollup for one calendar month. Mirrors the
 *  coaching pipeline's monthly summary, computed live from the dataset. */
export interface CoachMonthly {
  month: string; // "2026-07"
  monthLabel: string; // "July 2026"
  program: {
    sessions: number;
    activeLeaders: number;
    newcomers: number;
    avgScore: number | null;
    clusters: { name: string; weight: number; avg: number | null }[];
    delta: number | null;
  };
  leaders: MonthlyLeader[];
  /** Every YYYY-MM month that has at least one report across the program,
   *  newest first. Drives the portal's month picker so only months that were
   *  actually done are offered — empty months are never selectable. */
  availableMonths: string[];
  /** Program-wide narrative prose for this month (Executive Summary + Trends),
   *  or null when the dataset carries none for it. Passed straight through from
   *  the coaching pipeline so the portal and the PDF read the same words. */
  narrative: CoachMonthlyNarrative | null;
}

export class CoachService {
  private readonly userService: UserService;
  private readonly coachRepository: CoachRepository;
  /** Report store (change: coach-reports-store) — reports now live in the
   *  database rather than the compiled-in dataset. */
  private readonly reportsRepository: CoachReportsRepository;

  constructor(
    private readonly db: db,
    /** Optional so unit tests can construct without a mailer; when present,
     *  add-leader and add-note send email through it. */
    private readonly notification?: CoachMailer,
  ) {
    this.userService = new UserService(db);
    this.coachRepository = new CoachRepository(db);
    this.reportsRepository = new CoachReportsRepository(db);
  }

  // ─── Publish (ingest) ────────────────────────────────────────────────────

  /**
   * Ingest published reports into the store (change: coach-reports-store).
   *
   * The store is the sole assigner of report identity: an incoming report is
   * matched on the title-free natural key (coach + session date), so a re-title
   * updates the existing row and KEEPS its id — overlay notes/recording links
   * and already-delivered `?s=<id>` links stay valid. The response carries each
   * report's assigned id so the publisher can build links without deriving one.
   *
   * Guards the corpus against a stale publisher: when `expectedCount` is given
   * and is lower than what the store already holds, the publish is refused
   * rather than allowed to shrink live data.
   */
  async ingestReports(input: {
    reports: Array<{
      coachId: string;
      date: string;
      /** The provider's session identifier — part of the row's natural key. */
      sourceSessionId: string;
      id?: string;
      summary: Record<string, unknown>;
      metrics: Record<string, unknown>;
      body: Record<string, unknown>;
    }>;
    generatedAt?: string | null;
    expectedCount?: number | null;
  }): Promise<{
    accepted: Array<{
      id: string;
      coachId: string;
      date: string;
      created: boolean;
    }>;
    version: string;
    reportCount: number;
  }> {
    const stored = await this.reportsRepository.totalReports();
    if (
      typeof input.expectedCount === "number" &&
      input.expectedCount < stored
    ) {
      throw new ConflictError(
        `Publish refused: publisher reports ${input.expectedCount} sessions but the store holds ${stored} — refusing to shrink the corpus`,
      );
    }

    // Validate the WHOLE batch before writing anything, so a bad report at
    // position k cannot leave reports 1..k-1 committed.
    for (const report of input.reports) {
      if (!report.coachId || !report.date || !report.sourceSessionId) {
        throw new ValidationError(
          "Each report needs a coachId, a date and a sourceSessionId",
        );
      }
      if (!/^\d{4}-\d{2}-\d{2}$/.test(report.date)) {
        throw new ValidationError(
          `Report date must be yyyy-mm-dd (got "${report.date}" for ${report.coachId})`,
        );
      }
      // The read path serves ReportSchema, which REQUIRES these fields. Without
      // this check a publisher that renames one field gets a 200, and the
      // malformed row then breaks the leader's ENTIRE report list (the array
      // response fails validation as a whole), with no repair endpoint.
      const assembled = {
        ...report.summary,
        ...report.metrics,
        ...report.body,
      } as Record<string, unknown>;
      const missing = CoachService.REQUIRED_REPORT_FIELDS.filter(
        (f) => assembled[f] === undefined,
      );
      if (missing.length > 0) {
        throw new ValidationError(
          `Report ${report.coachId} ${report.date} is missing required field(s): ${missing.join(", ")}`,
        );
      }
    }

    // ONE transaction for the whole batch. Without it a database error at
    // report k left reports 1..k-1 committed AND skipped the provenance bump,
    // so the store held rows that `coach_dataset_meta` did not account for and
    // no caller could tell a partial publish from a complete one. Rolling back
    // also leaves the batch intact for the caller to retry.
    const { accepted, meta } = await this.reportsRepository.transaction(
      async (writer) => {
        const written: Array<{
          id: string;
          coachId: string;
          date: string;
          created: boolean;
        }> = [];
        for (const report of input.reports) {
          written.push(
            await this.reportsRepository.upsert(
              {
                id:
                  report.id ||
                  CoachService.mintReportId(
                    report.coachId,
                    report.date,
                    report.sourceSessionId,
                  ),
                coach_id: report.coachId,
                session_date: report.date,
                source_session_id: report.sourceSessionId,
                legacy_ids: [],
                summary: report.summary ?? {},
                metrics: report.metrics ?? {},
                body: report.body ?? {},
              },
              writer,
            ),
          );
        }
        return {
          accepted: written,
          meta: await this.reportsRepository.bumpMeta(
            input.generatedAt ?? null,
            writer,
          ),
        };
      },
    );

    return {
      accepted,
      version: meta.version,
      reportCount: meta.reportCount,
    };
  }

  /**
   * Fields the read contract (ReportSchema) requires. An ingest that omits any
   * of them is rejected at the write boundary rather than poisoning the read.
   */
  private static readonly REQUIRED_REPORT_FIELDS = [
    "dateLabel",
    "session",
    "topic",
    "duration",
    "attendees",
    "newcomers",
    "score",
    "base",
    "newcomerBonus",
    "sizeBonus",
    "status",
    "statusEmoji",
    "clusters",
    "dimensions",
    "bigIdeas",
    "feedback",
    "docUrl",
    "pdfUrl",
  ];

  /**
   * Opaque id for a report the store has not seen before. DETERMINISTIC in the
   * natural key, not random: an id minted freshly on every publish lands in
   * `legacy_ids` each time a retry turns the insert into an update, so the
   * array grows without bound. Derived from the source session id — which is
   * opaque provider output, never the session title — so it carries no title
   * and re-minting for the same session reproduces the same value.
   */
  private static mintReportId(
    coachId: string,
    date: string,
    sourceSessionId: string,
  ): string {
    const digest = createHash("sha256")
      .update(`${coachId}\u0000${date}\u0000${sourceSessionId}`)
      .digest("hex")
      .slice(0, 8);
    return `${coachId}-${date}-${digest}`;
  }

  // ─── Roster resolution (bundled dataset + admin-added leaders) ────────────

  /** Turn an admin-added leader row into a roster record (no reports yet). */
  private static syntheticRecord(row: AddedLeaderRow): CoachRecord {
    return {
      id: row.id,
      name: row.name || CoachService.nameFromEmail(row.email),
      email: row.email,
      group: row.group_name,
      coachName: row.coach_name,
      isCoach: true,
      zoomLink: "",
      reports: [],
    };
  }

  /** "jeff.ward@x.com" → "Jeff Ward". Best-effort display name for a leader
   *  added by email only. */
  private static nameFromEmail(email: string): string {
    const local = email.split("@")[0] ?? email;
    return (
      local
        .split(/[._-]+/)
        .filter(Boolean)
        .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
        .join(" ") || email
    );
  }

  /** Resolve a coaching record by email — bundled roster first, then an
   *  admin-added leader. */
  private async resolveByEmail(email: string): Promise<CoachRecord | null> {
    const bundled = this.findByEmail(email);
    if (bundled) return bundled;
    const added = await this.coachRepository.findAddedLeaderByEmail(email);
    return added ? CoachService.syntheticRecord(added) : null;
  }

  /** Resolve a coaching record by id — bundled roster first, then an
   *  admin-added leader (uuid id). */
  private async resolveById(coachId: string): Promise<CoachRecord | null> {
    const bundled = this.findById(coachId);
    if (bundled) return bundled;
    const added = (await this.coachRepository.listAddedLeaders()).find(
      (r) => r.id === coachId,
    );
    return added ? CoachService.syntheticRecord(added) : null;
  }

  /** All coaching records — bundled roster plus admin-added leaders, deduped
   *  by email (a bundled record wins if the same email exists in both). */
  private async allRecords(): Promise<CoachRecord[]> {
    const added = await this.coachRepository.listAddedLeaders();
    const bundledEmails = new Set(coachData.coaches.map((c) => c.email));
    const synthetic = added
      .filter((a) => !bundledEmails.has(a.email))
      .map(CoachService.syntheticRecord);
    return [...coachData.coaches, ...synthetic];
  }

  /** Overlay admin-editable state (recording link + notes) onto a coach's
   *  reports. Returns fresh objects — never mutates the bundled dataset. */
  private async overlayReports(
    coachId: string,
    reports: CoachReport[],
    fallbackRecordingUrl = "",
  ): Promise<CoachReport[]> {
    if (reports.length === 0) return [];
    const [recMap, noteRows] = await Promise.all([
      this.coachRepository.getRecordingLinksForCoach(coachId),
      this.coachRepository.listNotes(coachId),
    ]);
    const notesByReport = new Map<string, CoachNoteRow[]>();
    for (const n of noteRows) {
      const list = notesByReport.get(n.reportId) ?? [];
      list.push(n);
      notesByReport.set(n.reportId, list);
    }
    return reports.map((r) => {
      // An explicit admin value (including an explicit clear to "") wins;
      // otherwise fall back to any bundled URL, then to the leader's saved
      // meeting link so every session auto-carries a recording link.
      const explicit = recMap[r.id];
      const recordingUrl =
        explicit !== undefined
          ? explicit
          : r.recordingUrl || fallbackRecordingUrl || "";
      return {
        ...r,
        recordingUrl,
        notes: (notesByReport.get(r.id) ?? []).map(CoachService.toNoteView),
      };
    });
  }

  private static toNoteView(row: CoachNoteRow): CoachNoteView {
    return {
      id: row.id,
      body: row.body,
      createdAt: row.createdAt,
      emailed: row.emailed,
    };
  }

  /** Roster lookup by email (the join key between a VerseMate account and a
   *  coaching record). Case-insensitive. */
  private findByEmail(email: string): CoachRecord | null {
    const target = email.trim().toLowerCase();
    return coachData.coaches.find((c) => c.email === target) ?? null;
  }

  private findById(coachId: string): CoachRecord | null {
    return coachData.coaches.find((c) => c.id === coachId) ?? null;
  }

  private static isAdminEmail(email: string): boolean {
    const target = email.trim().toLowerCase();
    return (coachData.admins ?? []).includes(target);
  }

  /** The signed-in user's email (lowercased), or null. */
  private async emailFor(userId: string): Promise<string | null> {
    const user = await this.userService.findOne(userId);
    return user?.email ? user.email.trim().toLowerCase() : null;
  }

  /** Resolve the signed-in user to their coaching record, or null if the
   *  account is not in the roster (authenticated but not a coach). Consults
   *  both the bundled roster and admin-added leaders. */
  private async recordFor(userId: string): Promise<CoachRecord | null> {
    const email = await this.emailFor(userId);
    return email ? this.resolveByEmail(email) : null;
  }

  async isCoach(userId: string): Promise<boolean> {
    return (await this.recordFor(userId)) !== null;
  }

  /** True when the signed-in user is a program admin (oversight over every
   *  leader). Admins need not be coachees. */
  async isAdmin(userId: string): Promise<boolean> {
    const email = await this.emailFor(userId);
    return email ? CoachService.isAdminEmail(email) : false;
  }

  async getMe(userId: string) {
    const email = await this.emailFor(userId);
    if (!email) return null;

    const record = await this.resolveByEmail(email);
    const admin = CoachService.isAdminEmail(email);
    // Authenticated but neither a coachee nor an admin → not a coaching account.
    if (!record && !admin) return null;

    // Church + Bible-coach settings apply to any portal member (coachee OR
    // admin), so fetch the stored row for admins too — not just coachees.
    const stored =
      record || admin ? await this.coachRepository.getSettings(userId) : null;
    return {
      isCoach: !!record,
      isAdmin: admin,
      profile: record
        ? {
            id: record.id,
            name: record.name,
            email: record.email,
            group: record.group,
            coachName: record.coachName,
          }
        : null,
      zoomLink: stored?.zoomLink ?? record?.zoomLink ?? "",
      affiliatedChurch: stored?.affiliatedChurch ?? "",
      bibleCoach: stored?.bibleCoach ?? "",
      model: coachData.model,
      clusters: coachData.clusters,
      statusBands: coachData.statusBands,
    };
  }

  /**
   * A coach's reports from the STORE, or null when the store holds none for
   * them yet (migration-gate: the compiled-in bundle still answers until the
   * backfill has run for that coach — never as a runtime outage fallback).
   */
  private async storeReports(coachId: string): Promise<CoachReport[] | null> {
    // Gate on the DATASET-level signal, not this coach's row count. Gating on
    // rows meant a single ingest landing before the backfill flipped the coach
    // to store-only and their history appeared deleted (23 sessions -> 1).
    const meta = await this.reportsRepository.getMeta();
    if (!meta) return null;
    // ONE query for the whole history — not listMetrics + getDetail per row.
    const rows = await this.reportsRepository.listFullReports(coachId);
    if (rows.length === 0) return null;
    return rows.map(
      (d) =>
        rowToReport({
          id: d.id,
          session_date: d.date,
          summary: d.summary,
          metrics: d.metrics,
          body: d.body,
        }) as unknown as CoachReport,
    );
  }

  /**
   * Every coach's reports from the store, keyed by coach id — ONE query, and
   * without prose, because the consumers of this view (trends, roster, monthly)
   * only read score / status / clusters / dimensions / date. Null when the
   * store is not yet backfilled, so the bundle keeps answering.
   */
  private async storeReportsByCoach(): Promise<Map<
    string,
    CoachReport[]
  > | null> {
    const meta = await this.reportsRepository.getMeta();
    if (!meta) return null;
    const rows = await this.reportsRepository.listAllMetrics();
    if (rows.length === 0) return null;
    const byCoach = new Map<string, CoachReport[]>();
    for (const r of rows) {
      const report = rowToReport({
        id: r.id,
        session_date: r.date,
        summary: r.summary,
        metrics: r.metrics,
        body: {},
      }) as unknown as CoachReport;
      const list = byCoach.get(r.coachId) ?? [];
      list.push(report);
      byCoach.set(r.coachId, list);
    }
    // The contract everywhere else is newest-first.
    for (const list of byCoach.values()) {
      list.sort((a, b) => (a.date < b.date ? 1 : -1));
    }
    return byCoach;
  }

  /**
   * Roster records whose `reports` come from the store where it has them, so
   * trends / roster / monthly reflect a publish immediately instead of lagging
   * until the next deploy (they previously all read the compiled-in bundle).
   */
  private async recordsWithStoreReports(): Promise<CoachRecord[]> {
    const records = await this.allRecords();
    const byCoach = await this.storeReportsByCoach();
    if (!byCoach) return records;
    return records.map((r) => {
      const stored = byCoach.get(r.id);
      return stored ? { ...r, reports: stored } : r;
    });
  }

  /** Reports for a roster record: store first, bundled dataset until backfilled. */
  private async reportsFor(record: CoachRecord): Promise<CoachReport[]> {
    const fromStore = await this.storeReports(record.id);
    return fromStore ?? record.reports;
  }

  /**
   * One page of a coach's sessions as list rows — summary only, never prose, so
   * a long history stays bounded. Falls back to projecting the bundled reports
   * while the store has not been backfilled for that coach.
   */
  async getReportSummaries(
    coachId: string,
    opts: { limit?: number; offset?: number } = {},
  ): Promise<{ items: Record<string, unknown>[]; total: number }> {
    const total = await this.reportsRepository.countForCoach(coachId);
    if (total > 0) {
      const rows = await this.reportsRepository.listSummaries(coachId, opts);
      return {
        items: rows.map((r) =>
          rowToSummary({ id: r.id, session_date: r.date, summary: r.summary }),
        ),
        total,
      };
    }
    const record = await this.resolveById(coachId);
    if (!record) return { items: [], total: 0 };
    // Same clamp as the store path, so the bundle fallback cannot be handed a
    // NaN slice window and quietly return nothing.
    const limit = Number.isFinite(Number(opts.limit))
      ? Math.min(Math.max(Math.trunc(Number(opts.limit)), 1), 100)
      : 25;
    const offset = Number.isFinite(Number(opts.offset))
      ? Math.max(Math.trunc(Number(opts.offset)), 0)
      : 0;
    const page = record.reports.slice(offset, offset + limit);
    return {
      items: page.map((r) => ({
        id: r.id,
        date: r.date,
        dateLabel: r.dateLabel,
        session: r.session,
        topic: r.topic,
        score: r.score,
        status: r.status,
        statusEmoji: r.statusEmoji,
        pdfUrl: r.pdfUrl,
      })),
      total: record.reports.length,
    };
  }

  /**
   * One session's full content by immutable OR legacy id, SCOPED to the coach
   * that owns it. Null when the id names nothing for that coach — so a leader
   * can never read another leader's report, and an unknown id reports
   * not-found rather than silently showing a different session.
   */
  async getReportDetail(
    coachId: string,
    reportId: string,
  ): Promise<CoachReport | null> {
    const row = await this.reportsRepository.getDetail(coachId, reportId);
    if (row) {
      const report = rowToReport({
        id: row.id,
        session_date: row.date,
        summary: row.summary,
        metrics: row.metrics,
        body: row.body,
      }) as unknown as CoachReport;
      const [overlaid] = await this.overlayReports(coachId, [report]);
      return overlaid ?? report;
    }
    // Migration-gate: the bundle still answers for reports not yet backfilled —
    // scoped to THIS coach only, never a global search across every leader.
    const bundled = coachData.coaches.find((c) => c.id === coachId);
    const found = bundled?.reports.find((r) => r.id === reportId);
    if (found) {
      const [overlaid] = await this.overlayReports(coachId, [found]);
      return overlaid ?? found;
    }
    return null;
  }

  async getReports(userId: string): Promise<CoachReport[] | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    const stored = await this.coachRepository.getSettings(userId);
    const fallback = stored?.zoomLink ?? record.zoomLink ?? "";
    return this.overlayReports(
      record.id,
      await this.reportsFor(record),
      fallback,
    );
  }

  async getTrends(userId: string): Promise<CoachTrends | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return CoachService.buildTrends(await this.reportsFor(record));
  }

  // ─── Admin oversight (every leader) ──────────────────────────────────────

  /** Roster summary for the admin landing view. Includes admin-added leaders
   *  (0 sessions until the pipeline produces their first report). */
  async listCoaches(): Promise<CoachSummary[]> {
    const records = await this.recordsWithStoreReports();
    return records.map((c) => {
      // reports are stored newest-first.
      const latest = c.reports[0] ?? null;
      return {
        id: c.id,
        name: c.name,
        group: c.group,
        coachName: c.coachName,
        sessionCount: c.reports.length,
        latest: latest
          ? {
              date: latest.date,
              dateLabel: latest.dateLabel,
              score: latest.score,
              status: latest.status,
              statusEmoji: latest.statusEmoji,
            }
          : null,
      };
    });
  }

  /** A specific coach's reports by id (admin drill-in), with recording + notes
   *  overlaid. null → unknown id. */
  async getReportsById(coachId: string): Promise<CoachReport[] | null> {
    const record = await this.resolveById(coachId);
    if (!record) return null;
    // Auto-attach the leader's saved meeting link (looked up by their account
    // email) so each session carries a recording link on the admin drill-in too.
    const fallback =
      (await this.coachRepository.getZoomLinkByEmail(record.email)) ||
      record.zoomLink ||
      "";
    return this.overlayReports(
      record.id,
      await this.reportsFor(record),
      fallback,
    );
  }

  /** A specific coach's trends by id (admin drill-in). null → unknown id. */
  async getTrendsById(coachId: string): Promise<CoachTrends | null> {
    const record = await this.resolveById(coachId);
    return record
      ? CoachService.buildTrends(await this.reportsFor(record))
      : null;
  }

  /** Profile header for an admin viewing a specific coach. */
  async getProfileById(coachId: string): Promise<{
    id: string;
    name: string;
    group: string;
    coachName: string;
  } | null> {
    const c = await this.resolveById(coachId);
    return c
      ? { id: c.id, name: c.name, group: c.group, coachName: c.coachName }
      : null;
  }

  // ─── Admin writes: add leader · recording link · notes ───────────────────

  /** Add a leader by email (+ optional name/group), send an invite email, and
   *  return the new roster summary. Returns `{ ok:false, reason:'duplicate' }`
   *  when the email is already a coach. */
  async addLeader(
    adminUserId: string,
    input: { email: string; name?: string; group?: string; coachName?: string },
  ): Promise<
    { ok: true; coach: CoachSummary } | { ok: false; reason: "duplicate" }
  > {
    const email = input.email.trim().toLowerCase();
    const existing =
      this.findByEmail(email) ??
      (await this.coachRepository.findAddedLeaderByEmail(email));
    if (existing) return { ok: false, reason: "duplicate" };

    const name = input.name?.trim() || CoachService.nameFromEmail(email);
    const row = await this.coachRepository.addLeader({
      email,
      name,
      group: input.group?.trim() ?? "",
      coachName: input.coachName?.trim() ?? "",
      invitedBy: adminUserId,
    });

    // Best-effort invite email — never let a mail hiccup fail the add.
    try {
      const invitedBy = await this.displayNameFor(adminUserId);
      const portalUrl = `${process.env.APP_URL ?? ""}/coach`;
      await this.notification?.sendEmail({
        to: { email, name },
        subject: "You've been added to VerseMate Coaching",
        text: `You've been added to the VerseMate coaching portal. Sign in at ${portalUrl} with this email to see your dashboard.`,
        html: render(CoachInvite({ name, invitedBy, portalUrl })),
      });
    } catch (err) {
      console.log("[CoachService] invite email failed:", err);
    }

    return {
      ok: true,
      coach: {
        id: row.id,
        name,
        group: row.group_name,
        coachName: row.coach_name,
        sessionCount: 0,
        latest: null,
      },
    };
  }

  /**
   * Resolve a report id an admin supplied (possibly a legacy id) to the id the
   * overlay tables should store. Falls back to the bundled dataset while the
   * store has not been backfilled for that coach.
   */
  private async canonicalReportId(
    coachId: string,
    reportId: string,
    record: CoachRecord,
  ): Promise<string | null> {
    const fromStore = await this.reportsRepository.canonicalId(
      coachId,
      reportId,
    );
    if (fromStore) return fromStore;
    return record.reports.some((r) => r.id === reportId) ? reportId : null;
  }

  /** Set (or clear) a session's recording URL. null → unknown coach/session. */
  async setRecordingLink(
    coachId: string,
    reportId: string,
    recordingUrl: string,
  ): Promise<string | null> {
    const record = await this.resolveById(coachId);
    if (!record) return null;
    // Canonicalise: an admin may act on a report addressed by a LEGACY id, and
    // the overlay row must store the report's current immutable id.
    const canonical = await this.canonicalReportId(coachId, reportId, record);
    if (!canonical) return null;
    return this.coachRepository.setRecordingLink(
      coachId,
      canonical,
      recordingUrl,
    );
  }

  /** Persist a coaching note on a session, email it to the leader, and return
   *  the saved note. null → unknown coach/session. */
  async addNote(
    coachId: string,
    reportId: string,
    authorUserId: string | null,
    body: string,
  ): Promise<CoachNoteView | null> {
    const record = await this.resolveById(coachId);
    if (!record) return null;
    // Canonicalise a possibly-legacy id, then resolve the session for the email.
    const canonical = await this.canonicalReportId(coachId, reportId, record);
    if (!canonical) return null;
    const report =
      (await this.getReportDetail(coachId, canonical)) ??
      record.reports.find((r) => r.id === canonical);
    if (!report) return null;

    // Email the leader first; persist with the actual delivery outcome so the
    // note is never lost even if the mailer throws.
    let emailed = false;
    try {
      if (this.notification && record.email) {
        const portalUrl = `${process.env.APP_URL ?? ""}/coach`;
        await this.notification.sendEmail({
          to: { email: record.email, name: record.name },
          subject: `Coaching note — ${report.session}`,
          text: body,
          html: render(
            CoachNote({
              name: record.name,
              sessionLabel: `${report.session} — ${report.dateLabel}`,
              body,
              portalUrl,
            }),
          ),
        });
        emailed = true;
      }
    } catch (err) {
      console.log("[CoachService] note email failed:", err);
    }

    const saved = await this.coachRepository.addNote({
      coachId,
      // persist the canonical id so the note attaches to the report's identity
      reportId: canonical,
      authorUserId,
      body,
      emailed,
    });
    return CoachService.toNoteView(saved);
  }

  /** Best-effort display name for a user id (for the invite email). */
  private async displayNameFor(userId: string): Promise<string | undefined> {
    const email = await this.emailFor(userId);
    if (!email) return undefined;
    const record = this.findByEmail(email);
    return record?.name || CoachService.nameFromEmail(email);
  }

  // ─── Monthly cross-leader analysis ───────────────────────────────────────

  /** Program-wide + per-leader rollup for one YYYY-MM month, computed live
   *  from the dataset (current v3 weighted model). Mirrors the coaching
   *  pipeline's monthly summary. */
  async getMonthly(month: string): Promise<CoachMonthly> {
    const records = await this.recordsWithStoreReports();
    const prev = CoachService.prevMonth(month);

    // Canonical n→name map for the 12-dimension heatmap columns, plus the set
    // of months that actually have reports (for the picker).
    const dimNames = new Map<number, string>();
    const monthSet = new Set<string>();
    for (const c of records)
      for (const r of c.reports) {
        monthSet.add(r.date.slice(0, 7));
        for (const d of r.dimensions)
          if (!dimNames.has(d.n)) dimNames.set(d.n, d.name);
      }
    const dimList = [...dimNames.entries()].sort((a, b) => a[0] - b[0]);
    const availableMonths = [...monthSet].sort((a, b) => (a < b ? 1 : -1));

    const leaders: MonthlyLeader[] = [];
    let programSessions = 0;
    let programNewcomers = 0;
    const monthScores: number[] = [];
    const prevScores: number[] = [];
    const clusterSums = new Map<string, { sum: number; n: number }>();

    for (const c of records) {
      const inMonth = c.reports.filter((r) => r.date.startsWith(month));
      const inPrev = c.reports.filter((r) => r.date.startsWith(prev));
      if (inMonth.length === 0) continue;

      const avg = CoachService.mean(inMonth.map((r) => r.score));
      const prevAvg = inPrev.length
        ? CoachService.mean(inPrev.map((r) => r.score))
        : null;
      const band = CoachService.statusFor(avg);

      leaders.push({
        id: c.id,
        name: c.name,
        group: c.group,
        sessions: inMonth.length,
        avgScore: avg,
        status: band.label,
        statusEmoji: band.emoji,
        dimensions: dimList.map(([n, name]) => ({
          n,
          name,
          avg: CoachService.mean(
            inMonth
              .flatMap((r) => r.dimensions.filter((d) => d.n === n))
              .map((d) => d.score)
              .filter((s): s is number => s !== null),
          ),
        })),
        delta:
          avg !== null && prevAvg !== null
            ? Math.round((avg - prevAvg) * 10) / 10
            : null,
      });

      programSessions += inMonth.length;
      for (const r of inMonth) {
        programNewcomers += r.newcomers;
        monthScores.push(r.score);
        for (const cl of r.clusters) {
          if (cl.scorePct === null) continue;
          const acc = clusterSums.get(cl.name) ?? { sum: 0, n: 0 };
          acc.sum += cl.scorePct;
          acc.n += 1;
          clusterSums.set(cl.name, acc);
        }
      }
      for (const r of inPrev) prevScores.push(r.score);
    }

    leaders.sort((a, b) => (b.avgScore ?? -1) - (a.avgScore ?? -1));

    const programAvg = CoachService.mean(monthScores);
    const prevProgramAvg = prevScores.length
      ? CoachService.mean(prevScores)
      : null;

    return {
      month,
      monthLabel: CoachService.monthLabel(month),
      program: {
        sessions: programSessions,
        activeLeaders: leaders.length,
        newcomers: programNewcomers,
        avgScore: programAvg,
        clusters: coachData.clusters.map((cl) => {
          const acc = clusterSums.get(cl.name);
          return {
            name: cl.name,
            weight: cl.weight,
            avg: acc?.n ? Math.round((acc.sum / acc.n) * 10) / 10 : null,
          };
        }),
        delta:
          programAvg !== null && prevProgramAvg !== null
            ? Math.round((programAvg - prevProgramAvg) * 10) / 10
            : null,
      },
      leaders,
      availableMonths,
      narrative: coachData.monthlyNarratives?.[month] ?? null,
    };
  }

  // ─── Per-leader monthly summary ──────────────────────────────────────────

  /** Months a leader has a monthly summary for, newest first. */
  private monthsForCoach(coachId: string): string[] {
    const byMonth = coachData.monthlyLeaderSummaries?.[coachId];
    if (!byMonth) return [];
    return Object.keys(byMonth).sort((a, b) => (a < b ? 1 : -1));
  }

  /** Build the response for a resolved coach record + requested month. */
  private leaderMonthlyFor(
    record: CoachRecord,
    month: string,
  ): LeaderMonthlyResponse {
    const byMonth = coachData.monthlyLeaderSummaries?.[record.id];
    return {
      profile: { id: record.id, name: record.name, group: record.group },
      summary: byMonth?.[month] ?? null,
      availableMonths: this.monthsForCoach(record.id),
    };
  }

  /** The signed-in leader's own monthly summary for a month. null → the
   *  account is not a coachee (403). */
  async getMyMonthlySummary(
    userId: string,
    month: string,
  ): Promise<LeaderMonthlyResponse | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return this.leaderMonthlyFor(record, month);
  }

  /** A specific leader's monthly summary (admin drill-in). null → unknown id. */
  async getMonthlySummaryById(
    coachId: string,
    month: string,
  ): Promise<LeaderMonthlyResponse | null> {
    const record = await this.resolveById(coachId);
    if (!record) return null;
    return this.leaderMonthlyFor(record, month);
  }

  private static mean(nums: number[]): number | null {
    if (nums.length === 0) return null;
    return (
      Math.round((nums.reduce((a, b) => a + b, 0) / nums.length) * 10) / 10
    );
  }

  /** Highest status band whose min the score meets (bands are stored desc). */
  private static statusFor(score: number | null): {
    label: string;
    emoji: string;
  } {
    if (score === null) return { label: "", emoji: "" };
    const band = coachData.statusBands.find((b) => score >= b.min);
    return band
      ? { label: band.label, emoji: band.emoji }
      : { label: "", emoji: "" };
  }

  /** "2026-07" → "2026-06". */
  private static prevMonth(month: string): string {
    const [y, m] = month.split("-").map(Number);
    if (!y || !m) return month;
    const d = m === 1 ? { y: y - 1, m: 12 } : { y, m: m - 1 };
    return `${d.y}-${String(d.m).padStart(2, "0")}`;
  }

  /** "2026-07" → "July 2026". */
  private static monthLabel(month: string): string {
    const names = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ];
    const [y, m] = month.split("-").map(Number);
    if (!y || !m || m < 1 || m > 12) return month;
    return `${names[m - 1]} ${y}`;
  }

  async setZoomLink(userId: string, zoomLink: string): Promise<string | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return this.coachRepository.setZoomLink(userId, zoomLink);
  }

  /** True when the user belongs to the coach portal at all — a coachee OR a
   *  program admin. Church + Bible-coach settings are writable by both. */
  private async isPortalMember(userId: string): Promise<boolean> {
    if (await this.recordFor(userId)) return true;
    return this.isAdmin(userId);
  }

  async setAffiliatedChurch(
    userId: string,
    affiliatedChurch: string,
  ): Promise<string | null> {
    if (!(await this.isPortalMember(userId))) return null;
    return this.coachRepository.setAffiliatedChurch(userId, affiliatedChurch);
  }

  async setBibleCoach(
    userId: string,
    bibleCoach: string,
  ): Promise<string | null> {
    if (!(await this.isPortalMember(userId))) return null;
    return this.coachRepository.setBibleCoach(userId, bibleCoach);
  }

  // ─── Classes (many per leader) ────────────────────────────────────────────
  // Every class op is gated on the caller being a coachee (recordFor). An
  // admin who is not also a coachee has no classes of their own; they read the
  // whole cohort via listAllClasses().

  /** A leader's classes, most-recently-updated first. null → not a coach. */
  async getClasses(userId: string): Promise<CoachClass[] | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return this.coachRepository.listClasses(userId);
  }

  async addClass(
    userId: string,
    input: CoachClassInput,
  ): Promise<CoachClass | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return this.coachRepository.createClass(userId, input);
  }

  /** Update a class the caller owns. null → not a coach OR unknown class id
   *  (both surface to the caller the same way; the plugin maps to 403/404). */
  async updateClass(
    userId: string,
    classId: string,
    input: CoachClassInput,
  ): Promise<CoachClass | null> {
    const record = await this.recordFor(userId);
    if (!record) return null;
    return this.coachRepository.updateClass(userId, classId, input);
  }

  /** Delete a class the caller owns. Returns 'not_coach' | 'not_found' |
   *  'deleted' so the plugin can pick the right status. */
  async removeClass(
    userId: string,
    classId: string,
  ): Promise<"not_coach" | "not_found" | "deleted"> {
    const record = await this.recordFor(userId);
    if (!record) return "not_coach";
    const ok = await this.coachRepository.deleteClass(userId, classId);
    return ok ? "deleted" : "not_found";
  }

  /** Every leader's classes with owner identity resolved (admin export). The
   *  Fireflies operator reads this to configure which meeting links the bot
   *  auto-joins. Owner name comes from the coaching roster when the account is
   *  a known leader; otherwise it falls back to the account's email. */
  async listAllClasses(): Promise<AdminCoachClass[]> {
    const rows = await this.coachRepository.listAllClasses();
    // Resolve each distinct user_id once → email → roster record.
    const emailCache = new Map<string, string | null>();
    const out: AdminCoachClass[] = [];
    for (const row of rows) {
      if (!emailCache.has(row.userId)) {
        emailCache.set(row.userId, await this.emailFor(row.userId));
      }
      const email = emailCache.get(row.userId) ?? null;
      const record = email ? this.findByEmail(email) : null;
      out.push({
        id: row.id,
        name: row.name,
        classDate: row.classDate,
        recurrence: row.recurrence,
        zoomLink: row.zoomLink,
        leader: {
          id: record?.id ?? null,
          name: record?.name ?? email ?? "Unknown",
          email: email ?? "",
        },
      });
    }
    return out;
  }

  /** Derive the chart series from a coach's reports. Pure — exported shape
   *  matches the web client's CoachTrends. */
  static buildTrends(reports: CoachReport[]): CoachTrends {
    const chrono = [...reports].sort((a, b) => (a.date < b.date ? -1 : 1));

    const scoreSeries = chrono.map((r) => ({
      date: r.date,
      dateLabel: r.dateLabel,
      session: r.session,
      score: r.score,
      status: r.status,
    }));

    const clusterSeries: TrendRow[] = chrono.map((r) => {
      const row: TrendRow = { date: r.date, dateLabel: r.dateLabel };
      for (const c of r.clusters) row[c.name] = c.contribution;
      return row;
    });

    const dimensionSeries: TrendRow[] = chrono.map((r) => {
      const row: TrendRow = { date: r.date, dateLabel: r.dateLabel };
      for (const d of r.dimensions) row[d.name] = d.score;
      return row;
    });

    let delta: CoachTrends["delta"] = null;
    if (chrono.length >= 2) {
      const latest = chrono[chrono.length - 1];
      const prev = chrono[chrono.length - 2];
      delta = {
        score: Math.round((latest.score - prev.score) * 100) / 100,
        from: prev.score,
        to: latest.score,
        fromLabel: prev.dateLabel,
        toLabel: latest.dateLabel,
      };
    }

    return { scoreSeries, clusterSeries, dimensionSeries, delta };
  }
}
