export enum ErrorCode {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_VERIFICATION_TOKEN = "INVALID_VERIFICATION_TOKEN",
  VERIFICATION_LINK_ALREADY_USED = "VERIFICATION_LINK_ALREADY_USED",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
}
