declare const styles: {
  readonly active: string;
  readonly animateSpin: string;
  readonly button: string;
  readonly card: string;
  readonly cardContent: string;
  readonly chatContainer: string;
  readonly chatContent: string;
  readonly disabled: string;
  readonly enabled: string;
  readonly flexBetween: string;
  readonly groupContainer: string;
  readonly historyContainer: string;
  readonly icon: string;
  readonly input: string;
  readonly scrollArea: string;
  readonly separator: string;
  readonly simpleText: string;
  readonly spin: string;
  readonly subHeader: string;
  readonly title: string;
  readonly trigger: string;
};
export = styles;
