import type { CountryCode } from "libphonenumber-js";

interface CountryDialCode {
  name: string;
  dialCode: string;
  code: CountryCode;
  codeName: string;
}

export const countriesDialCodes: CountryDialCode[] = [
  {
    name: "Afghanistan",
    dialCode: "+93",
    code: "AF",
    codeName: "AF - Afghanistan",
  },
  {
    name: "Aland Islands",
    dialCode: "+358",
    code: "AX",
    codeName: "AX - Aland Islands",
  },
  {
    name: "Albania",
    dialCode: "+355",
    code: "AL",
    codeName: "AL - Albania",
  },
  {
    name: "Algeria",
    dialCode: "+213",
    code: "DZ",
    codeName: "DZ - Algeria",
  },
  {
    name: "American Samoa",
    dialCode: "+1684",
    code: "AS",
    codeName: "AS - American Samoa",
  },
  {
    name: "Andorra",
    dialCode: "+376",
    code: "AD",
    codeName: "AD - Andorra",
  },
  {
    name: "Angola",
    dialCode: "+244",
    code: "AO",
    codeName: "AO - Angola",
  },
  {
    name: "Anguilla",
    dialCode: "+1264",
    code: "AI",
    codeName: "AI - Anguilla",
  },
  {
    name: "Antigua and Barbuda",
    dialCode: "+1268",
    code: "AG",
    codeName: "AG - Antigua and Barbuda",
  },
  {
    name: "Argentina",
    dialCode: "+54",
    code: "AR",
    codeName: "AR - Argentina",
  },
  {
    name: "Armenia",
    dialCode: "+374",
    code: "AM",
    codeName: "AM - Armenia",
  },
  {
    name: "Aruba",
    dialCode: "+297",
    code: "AW",
    codeName: "AW - Aruba",
  },
  {
    name: "Australia",
    dialCode: "+61",
    code: "AU",
    codeName: "AU - Australia",
  },
  {
    name: "Austria",
    dialCode: "+43",
    code: "AT",
    codeName: "AT - Austria",
  },
  {
    name: "Azerbaijan",
    dialCode: "+994",
    code: "AZ",
    codeName: "AZ - Azerbaijan",
  },
  {
    name: "Bahamas",
    dialCode: "+1242",
    code: "BS",
    codeName: "BS - Bahamas",
  },
  {
    name: "Bahrain",
    dialCode: "+973",
    code: "BH",
    codeName: "BH - Bahrain",
  },
  {
    name: "Bangladesh",
    dialCode: "+880",
    code: "BD",
    codeName: "BD - Bangladesh",
  },
  {
    name: "Barbados",
    dialCode: "+1246",
    code: "BB",
    codeName: "BB - Barbados",
  },
  {
    name: "Belarus",
    dialCode: "+375",
    code: "BY",
    codeName: "BY - Belarus",
  },
  {
    name: "Belgium",
    dialCode: "+32",
    code: "BE",
    codeName: "BE - Belgium",
  },
  {
    name: "Belize",
    dialCode: "+501",
    code: "BZ",
    codeName: "BZ - Belize",
  },
  {
    name: "Benin",
    dialCode: "+229",
    code: "BJ",
    codeName: "BJ - Benin",
  },
  {
    name: "Bermuda",
    dialCode: "+1441",
    code: "BM",
    codeName: "BM - Bermuda",
  },
  {
    name: "Bhutan",
    dialCode: "+975",
    code: "BT",
    codeName: "BT - Bhutan",
  },
  {
    name: "Bolivia, Plurinational State of",
    dialCode: "+591",
    code: "BO",
    codeName: "BO - Bolivia, Plurinational State of",
  },
  {
    name: "Bosnia and Herzegovina",
    dialCode: "+387",
    code: "BA",
    codeName: "BA - Bosnia and Herzegovina",
  },
  {
    name: "Botswana",
    dialCode: "+267",
    code: "BW",
    codeName: "BW - Botswana",
  },
  {
    name: "Brasil",
    dialCode: "+55",
    code: "BR",
    codeName: "BR - Brasil",
  },
  {
    name: "British Indian Ocean Territory",
    dialCode: "+246",
    code: "IO",
    codeName: "IO - British Indian Ocean Territory",
  },
  {
    name: "Brunei Darussalam",
    dialCode: "+673",
    code: "BN",
    codeName: "BN - Brunei Darussalam",
  },
  {
    name: "Bulgaria",
    dialCode: "+359",
    code: "BG",
    codeName: "BG - Bulgaria",
  },
  {
    name: "Burkina Faso",
    dialCode: "+226",
    code: "BF",
    codeName: "BF - Burkina Faso",
  },
  {
    name: "Burundi",
    dialCode: "+257",
    code: "BI",
    codeName: "BI - Burundi",
  },
  {
    name: "Cambodia",
    dialCode: "+855",
    code: "KH",
    codeName: "KH - Cambodia",
  },
  {
    name: "Cameroon",
    dialCode: "+237",
    code: "CM",
    codeName: "CM - Cameroon",
  },
  {
    name: "Canada",
    dialCode: "+1",
    code: "CA",
    codeName: "CA - Canada",
  },
  {
    name: "Cape Verde",
    dialCode: "+238",
    code: "CV",
    codeName: "CV - Cape Verde",
  },
  {
    name: "Cayman Islands",
    dialCode: "+ 345",
    code: "KY",
    codeName: "KY - Cayman Islands",
  },
  {
    name: "Central African Republic",
    dialCode: "+236",
    code: "CF",
    codeName: "CF - Central African Republic",
  },
  {
    name: "Chad",
    dialCode: "+235",
    code: "TD",
    codeName: "TD - Chad",
  },
  {
    name: "Chile",
    dialCode: "+56",
    code: "CL",
    codeName: "CL - Chile",
  },
  {
    name: "China",
    dialCode: "+86",
    code: "CN",
    codeName: "CN - China",
  },
  {
    name: "Christmas Island",
    dialCode: "+61",
    code: "CX",
    codeName: "CX - Christmas Island",
  },
  {
    name: "Cocos (Keeling) Islands",
    dialCode: "+61",
    code: "CC",
    codeName: "CC - Cocos (Keeling) Islands",
  },
  {
    name: "Colombia",
    dialCode: "+57",
    code: "CO",
    codeName: "CO - Colombia",
  },
  {
    name: "Comoros",
    dialCode: "+269",
    code: "KM",
    codeName: "KM - Comoros",
  },
  {
    name: "Congo",
    dialCode: "+242",
    code: "CG",
    codeName: "CG - Congo",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dialCode: "+243",
    code: "CD",
    codeName: "CD - Congo, The Democratic Republic of the Congo",
  },
  {
    name: "Cook Islands",
    dialCode: "+682",
    code: "CK",
    codeName: "CK - Cook Islands",
  },
  {
    name: "Costa Rica",
    dialCode: "+506",
    code: "CR",
    codeName: "CR - Costa Rica",
  },
  {
    name: "Cote d'Ivoire",
    dialCode: "+225",
    code: "CI",
    codeName: "CI - Cote d'Ivoire",
  },
  {
    name: "Croatia",
    dialCode: "+385",
    code: "HR",
    codeName: "HR - Croatia",
  },
  {
    name: "Cuba",
    dialCode: "+53",
    code: "CU",
    codeName: "CU - Cuba",
  },
  {
    name: "Cyprus",
    dialCode: "+357",
    code: "CY",
    codeName: "CY - Cyprus",
  },
  {
    name: "Czech Republic",
    dialCode: "+420",
    code: "CZ",
    codeName: "CZ - Czech Republic",
  },
  {
    name: "Denmark",
    dialCode: "+45",
    code: "DK",
    codeName: "DK - Denmark",
  },
  {
    name: "Djibouti",
    dialCode: "+253",
    code: "DJ",
    codeName: "DJ - Djibouti",
  },
  {
    name: "Dominica",
    dialCode: "+1767",
    code: "DM",
    codeName: "DM - Dominica",
  },
  {
    name: "Dominican Republic",
    dialCode: "+1849",
    code: "DO",
    codeName: "DO - Dominican Republic",
  },
  {
    name: "Ecuador",
    dialCode: "+593",
    code: "EC",
    codeName: "EC - Ecuador",
  },
  {
    name: "Egypt",
    dialCode: "+20",
    code: "EG",
    codeName: "EG - Egypt",
  },
  {
    name: "El Salvador",
    dialCode: "+503",
    code: "SV",
    codeName: "SV - El Salvador",
  },
  {
    name: "Equatorial Guinea",
    dialCode: "+240",
    code: "GQ",
    codeName: "GQ - Equatorial Guinea",
  },
  {
    name: "Eritrea",
    dialCode: "+291",
    code: "ER",
    codeName: "ER - Eritrea",
  },
  {
    name: "Estonia",
    dialCode: "+372",
    code: "EE",
    codeName: "EE - Estonia",
  },
  {
    name: "Ethiopia",
    dialCode: "+251",
    code: "ET",
    codeName: "ET - Ethiopia",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dialCode: "+500",
    code: "FK",
    codeName: "FK - Falkland Islands (Malvinas)",
  },
  {
    name: "Faroe Islands",
    dialCode: "+298",
    code: "FO",
    codeName: "FO - Faroe Islands",
  },
  {
    name: "Fiji",
    dialCode: "+679",
    code: "FJ",
    codeName: "FJ - Fiji",
  },
  {
    name: "Finland",
    dialCode: "+358",
    code: "FI",
    codeName: "FI - Finland",
  },
  {
    name: "France",
    dialCode: "+33",
    code: "FR",
    codeName: "FR - France",
  },
  {
    name: "French Guiana",
    dialCode: "+594",
    code: "GF",
    codeName: "GF - French Guiana",
  },
  {
    name: "French Polynesia",
    dialCode: "+689",
    code: "PF",
    codeName: "PF - French Polynesia",
  },
  {
    name: "Gabon",
    dialCode: "+241",
    code: "GA",
    codeName: "GA - Gabon",
  },
  {
    name: "Gambia",
    dialCode: "+220",
    code: "GM",
    codeName: "GM - Gambia",
  },
  {
    name: "Georgia",
    dialCode: "+995",
    code: "GE",
    codeName: "GE - Georgia",
  },
  {
    name: "Germany",
    dialCode: "+49",
    code: "DE",
    codeName: "DE - Germany",
  },
  {
    name: "Ghana",
    dialCode: "+233",
    code: "GH",
    codeName: "GH - Ghana",
  },
  {
    name: "Gibraltar",
    dialCode: "+350",
    code: "GI",
    codeName: "GI - Gibraltar",
  },
  {
    name: "Greece",
    dialCode: "+30",
    code: "GR",
    codeName: "GR - Greece",
  },
  {
    name: "Greenland",
    dialCode: "+299",
    code: "GL",
    codeName: "GL - Greenland",
  },
  {
    name: "Grenada",
    dialCode: "+1473",
    code: "GD",
    codeName: "GD - Grenada",
  },
  {
    name: "Guadeloupe",
    dialCode: "+590",
    code: "GP",
    codeName: "GP - Guadeloupe",
  },
  {
    name: "Guam",
    dialCode: "+1671",
    code: "GU",
    codeName: "GU - Guam",
  },
  {
    name: "Guatemala",
    dialCode: "+502",
    code: "GT",
    codeName: "GT - Guatemala",
  },
  {
    name: "Guernsey",
    dialCode: "+44",
    code: "GG",
    codeName: "GG - Guernsey",
  },
  {
    name: "Guinea",
    dialCode: "+224",
    code: "GN",
    codeName: "GN - Guinea",
  },
  {
    name: "Guinea-Bissau",
    dialCode: "+245",
    code: "GW",
    codeName: "GW - Guinea-Bissau",
  },
  {
    name: "Guyana",
    dialCode: "+595",
    code: "GY",
    codeName: "GY - Guyana",
  },
  {
    name: "Haiti",
    dialCode: "+509",
    code: "HT",
    codeName: "HT - Haiti",
  },
  {
    name: "Holy See (Vatican City State)",
    dialCode: "+379",
    code: "VA",
    codeName: "VA - Holy See (Vatican City State)",
  },
  {
    name: "Honduras",
    dialCode: "+504",
    code: "HN",
    codeName: "HN - Honduras",
  },
  {
    name: "Hong Kong",
    dialCode: "+852",
    code: "HK",
    codeName: "HK - Hong Kong",
  },
  {
    name: "Hungary",
    dialCode: "+36",
    code: "HU",
    codeName: "HU - Hungary",
  },
  {
    name: "Iceland",
    dialCode: "+354",
    code: "IS",
    codeName: "IS - Iceland",
  },
  {
    name: "India",
    dialCode: "+91",
    code: "IN",
    codeName: "IN - India",
  },
  {
    name: "Indonesia",
    dialCode: "+62",
    code: "ID",
    codeName: "ID - Indonesia",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dialCode: "+98",
    code: "IR",
    codeName: "IR - Iran, Islamic Republic of Persian Gulf",
  },
  {
    name: "Iraq",
    dialCode: "+964",
    code: "IQ",
    codeName: "IQ - Iraq",
  },
  {
    name: "Ireland",
    dialCode: "+353",
    code: "IE",
    codeName: "IE - Ireland",
  },
  {
    name: "Isle of Man",
    dialCode: "+44",
    code: "IM",
    codeName: "IM - Isle of Man",
  },
  {
    name: "Israel",
    dialCode: "+972",
    code: "IL",
    codeName: "IL - Israel",
  },
  {
    name: "Italy",
    dialCode: "+39",
    code: "IT",
    codeName: "IT - Italy",
  },
  {
    name: "Jamaica",
    dialCode: "+1876",
    code: "JM",
    codeName: "JM - Jamaica",
  },
  {
    name: "Japan",
    dialCode: "+81",
    code: "JP",
    codeName: "JP - Japan",
  },
  {
    name: "Jersey",
    dialCode: "+44",
    code: "JE",
    codeName: "JE - Jersey",
  },
  {
    name: "Jordan",
    dialCode: "+962",
    code: "JO",
    codeName: "JO - Jordan",
  },
  {
    name: "Kazakhstan",
    dialCode: "+77",
    code: "KZ",
    codeName: "KZ - Kazakhstan",
  },
  {
    name: "Kenya",
    dialCode: "+254",
    code: "KE",
    codeName: "KE - Kenya",
  },
  {
    name: "Kiribati",
    dialCode: "+686",
    code: "KI",
    codeName: "KI - Kiribati",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dialCode: "+850",
    code: "KP",
    codeName: "KP - Korea, Democratic People's Republic of Korea",
  },
  {
    name: "Korea, Republic of South Korea",
    dialCode: "+82",
    code: "KR",
    codeName: "KR - Korea, Republic of South Korea",
  },
  {
    name: "Kuwait",
    dialCode: "+965",
    code: "KW",
    codeName: "KW - Kuwait",
  },
  {
    name: "Kyrgyzstan",
    dialCode: "+996",
    code: "KG",
    codeName: "KG - Kyrgyzstan",
  },
  {
    name: "Laos",
    dialCode: "+856",
    code: "LA",
    codeName: "LA - Laos",
  },
  {
    name: "Latvia",
    dialCode: "+371",
    code: "LV",
    codeName: "LV - Latvia",
  },
  {
    name: "Lebanon",
    dialCode: "+961",
    code: "LB",
    codeName: "LB - Lebanon",
  },
  {
    name: "Lesotho",
    dialCode: "+266",
    code: "LS",
    codeName: "LS - Lesotho",
  },
  {
    name: "Liberia",
    dialCode: "+231",
    code: "LR",
    codeName: "LR - Liberia",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dialCode: "+218",
    code: "LY",
    codeName: "LY - Libyan Arab Jamahiriya",
  },
  {
    name: "Liechtenstein",
    dialCode: "+423",
    code: "LI",
    codeName: "LI - Liechtenstein",
  },
  {
    name: "Lithuania",
    dialCode: "+370",
    code: "LT",
    codeName: "LT - Lithuania",
  },
  {
    name: "Luxembourg",
    dialCode: "+352",
    code: "LU",
    codeName: "LU - Luxembourg",
  },
  {
    name: "Macao",
    dialCode: "+853",
    code: "MO",
    codeName: "MO - Macao",
  },
  {
    name: "Macedonia",
    dialCode: "+389",
    code: "MK",
    codeName: "MK - Macedonia",
  },
  {
    name: "Madagascar",
    dialCode: "+261",
    code: "MG",
    codeName: "MG - Madagascar",
  },
  {
    name: "Malawi",
    dialCode: "+265",
    code: "MW",
    codeName: "MW - Malawi",
  },
  {
    name: "Malaysia",
    dialCode: "+60",
    code: "MY",
    codeName: "MY - Malaysia",
  },
  {
    name: "Maldives",
    dialCode: "+960",
    code: "MV",
    codeName: "MV - Maldives",
  },
  {
    name: "Mali",
    dialCode: "+223",
    code: "ML",
    codeName: "ML - Mali",
  },
  {
    name: "Malta",
    dialCode: "+356",
    code: "MT",
    codeName: "MT - Malta",
  },
  {
    name: "Marshall Islands",
    dialCode: "+692",
    code: "MH",
    codeName: "MH - Marshall Islands",
  },
  {
    name: "Martinique",
    dialCode: "+596",
    code: "MQ",
    codeName: "MQ - Martinique",
  },
  {
    name: "Mauritania",
    dialCode: "+222",
    code: "MR",
    codeName: "MR - Mauritania",
  },
  {
    name: "Mauritius",
    dialCode: "+230",
    code: "MU",
    codeName: "MU - Mauritius",
  },
  {
    name: "Mayotte",
    dialCode: "+262",
    code: "YT",
    codeName: "YT - Mayotte",
  },
  {
    name: "Mexico",
    dialCode: "+52",
    code: "MX",
    codeName: "MX - Mexico",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dialCode: "+691",
    code: "FM",
    codeName: "FM - Micronesia, Federated States of Micronesia",
  },
  {
    name: "Moldova",
    dialCode: "+373",
    code: "MD",
    codeName: "MD - Moldova",
  },
  {
    name: "Monaco",
    dialCode: "+377",
    code: "MC",
    codeName: "MC - Monaco",
  },
  {
    name: "Mongolia",
    dialCode: "+976",
    code: "MN",
    codeName: "MN - Mongolia",
  },
  {
    name: "Montenegro",
    dialCode: "+382",
    code: "ME",
    codeName: "ME - Montenegro",
  },
  {
    name: "Montserrat",
    dialCode: "+1664",
    code: "MS",
    codeName: "MS - Montserrat",
  },
  {
    name: "Morocco",
    dialCode: "+212",
    code: "MA",
    codeName: "MA - Morocco",
  },
  {
    name: "Mozambique",
    dialCode: "+258",
    code: "MZ",
    codeName: "MZ - Mozambique",
  },
  {
    name: "Myanmar",
    dialCode: "+95",
    code: "MM",
    codeName: "MM - Myanmar",
  },
  {
    name: "Namibia",
    dialCode: "+264",
    code: "NA",
    codeName: "NA - Namibia",
  },
  {
    name: "Nauru",
    dialCode: "+674",
    code: "NR",
    codeName: "NR - Nauru",
  },
  {
    name: "Nepal",
    dialCode: "+977",
    code: "NP",
    codeName: "NP - Nepal",
  },
  {
    name: "Netherlands",
    dialCode: "+31",
    code: "NL",
    codeName: "NL - Netherlands",
  },
  {
    name: "New Caledonia",
    dialCode: "+687",
    code: "NC",
    codeName: "NC - New Caledonia",
  },
  {
    name: "New Zealand",
    dialCode: "+64",
    code: "NZ",
    codeName: "NZ - New Zealand",
  },
  {
    name: "Nicaragua",
    dialCode: "+505",
    code: "NI",
    codeName: "NI - Nicaragua",
  },
  {
    name: "Niger",
    dialCode: "+227",
    code: "NE",
    codeName: "NE - Niger",
  },
  {
    name: "Nigeria",
    dialCode: "+234",
    code: "NG",
    codeName: "NG - Nigeria",
  },
  {
    name: "Niue",
    dialCode: "+683",
    code: "NU",
    codeName: "NU - Niue",
  },
  {
    name: "Norfolk Island",
    dialCode: "+672",
    code: "NF",
    codeName: "NF - Norfolk Island",
  },
  {
    name: "Northern Mariana Islands",
    dialCode: "+1670",
    code: "MP",
    codeName: "MP - Northern Mariana Islands",
  },
  {
    name: "Norway",
    dialCode: "+47",
    code: "NO",
    codeName: "NO - Norway",
  },
  {
    name: "Oman",
    dialCode: "+968",
    code: "OM",
    codeName: "OM - Oman",
  },
  {
    name: "Pakistan",
    dialCode: "+92",
    code: "PK",
    codeName: "PK - Pakistan",
  },
  {
    name: "Palau",
    dialCode: "+680",
    code: "PW",
    codeName: "PW - Palau",
  },
  {
    name: "Palestinian Territory, Occupied",
    dialCode: "+970",
    code: "PS",
    codeName: "PS - Palestinian Territory, Occupied",
  },
  {
    name: "Panama",
    dialCode: "+507",
    code: "PA",
    codeName: "PA - Panama",
  },
  {
    name: "Papua New Guinea",
    dialCode: "+675",
    code: "PG",
    codeName: "PG - Papua New Guinea",
  },
  {
    name: "Paraguay",
    dialCode: "+595",
    code: "PY",
    codeName: "PY - Paraguay",
  },
  {
    name: "Peru",
    dialCode: "+51",
    code: "PE",
    codeName: "PE - Peru",
  },
  {
    name: "Philippines",
    dialCode: "+63",
    code: "PH",
    codeName: "PH - Philippines",
  },
  {
    name: "Poland",
    dialCode: "+48",
    code: "PL",
    codeName: "PL - Poland",
  },
  {
    name: "Portugal",
    dialCode: "+351",
    code: "PT",
    codeName: "PT - Portugal",
  },
  {
    name: "Puerto Rico",
    dialCode: "+1939",
    code: "PR",
    codeName: "PR - Puerto Rico",
  },
  {
    name: "Qatar",
    dialCode: "+974",
    code: "QA",
    codeName: "QA - Qatar",
  },
  {
    name: "Romania",
    dialCode: "+40",
    code: "RO",
    codeName: "RO - Romania",
  },
  {
    name: "Russia",
    dialCode: "+7",
    code: "RU",
    codeName: "RU - Russia",
  },
  {
    name: "Rwanda",
    dialCode: "+250",
    code: "RW",
    codeName: "RW - Rwanda",
  },
  {
    name: "Reunion",
    dialCode: "+262",
    code: "RE",
    codeName: "RE - Reunion",
  },
  {
    name: "Saint Barthelemy",
    dialCode: "+590",
    code: "BL",
    codeName: "BL - Saint Barthelemy",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dialCode: "+290",
    code: "SH",
    codeName: "SH - Saint Helena, Ascension and Tristan Da Cunha",
  },
  {
    name: "Saint Kitts and Nevis",
    dialCode: "+1869",
    code: "KN",
    codeName: "KN - Saint Kitts and Nevis",
  },
  {
    name: "Saint Lucia",
    dialCode: "+1758",
    code: "LC",
    codeName: "LC - Saint Lucia",
  },
  {
    name: "Saint Martin",
    dialCode: "+590",
    code: "MF",
    codeName: "MF - Saint Martin",
  },
  {
    name: "Saint Pierre and Miquelon",
    dialCode: "+508",
    code: "PM",
    codeName: "PM - Saint Pierre and Miquelon",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dialCode: "+1784",
    code: "VC",
    codeName: "VC - Saint Vincent and the Grenadines",
  },
  {
    name: "Samoa",
    dialCode: "+685",
    code: "WS",
    codeName: "WS - Samoa",
  },
  {
    name: "San Marino",
    dialCode: "+378",
    code: "SM",
    codeName: "SM - San Marino",
  },
  {
    name: "Sao Tome and Principe",
    dialCode: "+239",
    code: "ST",
    codeName: "ST - Sao Tome and Principe",
  },
  {
    name: "Saudi Arabia",
    dialCode: "+966",
    code: "SA",
    codeName: "SA - Saudi Arabia",
  },
  {
    name: "Senegal",
    dialCode: "+221",
    code: "SN",
    codeName: "SN - Senegal",
  },
  {
    name: "Serbia",
    dialCode: "+381",
    code: "RS",
    codeName: "RS - Serbia",
  },
  {
    name: "Seychelles",
    dialCode: "+248",
    code: "SC",
    codeName: "SC - Seychelles",
  },
  {
    name: "Sierra Leone",
    dialCode: "+232",
    code: "SL",
    codeName: "SL - Sierra Leone",
  },
  {
    name: "Singapore",
    dialCode: "+65",
    code: "SG",
    codeName: "SG - Singapore",
  },
  {
    name: "Slovakia",
    dialCode: "+421",
    code: "SK",
    codeName: "SK - Slovakia",
  },
  {
    name: "Slovenia",
    dialCode: "+386",
    code: "SI",
    codeName: "SI - Slovenia",
  },
  {
    name: "Solomon Islands",
    dialCode: "+677",
    code: "SB",
    codeName: "SB - Solomon Islands",
  },
  {
    name: "Somalia",
    dialCode: "+252",
    code: "SO",
    codeName: "SO - Somalia",
  },
  {
    name: "South Africa",
    dialCode: "+27",
    code: "ZA",
    codeName: "ZA - South Africa",
  },
  {
    name: "South Sudan",
    dialCode: "+211",
    code: "SS",
    codeName: "SS - South Sudan",
  },
  {
    name: "Spain",
    dialCode: "+34",
    code: "ES",
    codeName: "ES - Spain",
  },
  {
    name: "Sri Lanka",
    dialCode: "+94",
    code: "LK",
    codeName: "LK - Sri Lanka",
  },
  {
    name: "Sudan",
    dialCode: "+249",
    code: "SD",
    codeName: "SD - Sudan",
  },
  {
    name: "Suriname",
    dialCode: "+597",
    code: "SR",
    codeName: "SR - Suriname",
  },
  {
    name: "Svalbard and Jan Mayen",
    dialCode: "+47",
    code: "SJ",
    codeName: "SJ - Svalbard and Jan Mayen",
  },
  {
    name: "Swaziland",
    dialCode: "+268",
    code: "SZ",
    codeName: "SZ - Swaziland",
  },
  {
    name: "Sweden",
    dialCode: "+46",
    code: "SE",
    codeName: "SE - Sweden",
  },
  {
    name: "Switzerland",
    dialCode: "+41",
    code: "CH",
    codeName: "CH - Switzerland",
  },
  {
    name: "Syrian Arab Republic",
    dialCode: "+963",
    code: "SY",
    codeName: "SY - Syrian Arab Republic",
  },
  {
    name: "Taiwan",
    dialCode: "+886",
    code: "TW",
    codeName: "TW - Taiwan",
  },
  {
    name: "Tajikistan",
    dialCode: "+992",
    code: "TJ",
    codeName: "TJ - Tajikistan",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dialCode: "+255",
    code: "TZ",
    codeName: "TZ - Tanzania, United Republic of Tanzania",
  },
  {
    name: "Thailand",
    dialCode: "+66",
    code: "TH",
    codeName: "TH - Thailand",
  },
  {
    name: "Timor-Leste",
    dialCode: "+670",
    code: "TL",
    codeName: "TL - Timor-Leste",
  },
  {
    name: "Togo",
    dialCode: "+228",
    code: "TG",
    codeName: "TG - Togo",
  },
  {
    name: "Tokelau",
    dialCode: "+690",
    code: "TK",
    codeName: "TK - Tokelau",
  },
  {
    name: "Tonga",
    dialCode: "+676",
    code: "TO",
    codeName: "TO - Tonga",
  },
  {
    name: "Trinidad and Tobago",
    dialCode: "+1868",
    code: "TT",
    codeName: "TT - Trinidad and Tobago",
  },
  {
    name: "Tunisia",
    dialCode: "+216",
    code: "TN",
    codeName: "TN - Tunisia",
  },
  {
    name: "Turkey",
    dialCode: "+90",
    code: "TR",
    codeName: "TR - Turkey",
  },
  {
    name: "Turkmenistan",
    dialCode: "+993",
    code: "TM",
    codeName: "TM - Turkmenistan",
  },
  {
    name: "Turks and Caicos Islands",
    dialCode: "+1649",
    code: "TC",
    codeName: "TC - Turks and Caicos Islands",
  },
  {
    name: "Tuvalu",
    dialCode: "+688",
    code: "TV",
    codeName: "TV - Tuvalu",
  },
  {
    name: "Uganda",
    dialCode: "+256",
    code: "UG",
    codeName: "UG - Uganda",
  },
  {
    name: "Ukraine",
    dialCode: "+380",
    code: "UA",
    codeName: "UA - Ukraine",
  },
  {
    name: "United Arab Emirates",
    dialCode: "+971",
    code: "AE",
    codeName: "AE - United Arab Emirates",
  },
  {
    name: "United Kingdom",
    dialCode: "+44",
    code: "GB",
    codeName: "GB - United Kingdom",
  },
  {
    name: "United States",
    dialCode: "+1",
    code: "US",
    codeName: "US - United States",
  },
  {
    name: "Uruguay",
    dialCode: "+598",
    code: "UY",
    codeName: "UY - Uruguay",
  },
  {
    name: "Uzbekistan",
    dialCode: "+998",
    code: "UZ",
    codeName: "UZ - Uzbekistan",
  },
  {
    name: "Vanuatu",
    dialCode: "+678",
    code: "VU",
    codeName: "VU - Vanuatu",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dialCode: "+58",
    code: "VE",
    codeName: "VE - Venezuela, Bolivarian Republic of Venezuela",
  },
  {
    name: "Vietnam",
    dialCode: "+84",
    code: "VN",
    codeName: "VN - Vietnam",
  },
  {
    name: "Virgin Islands, British",
    dialCode: "+1284",
    code: "VG",
    codeName: "VG - Virgin Islands, British",
  },
  {
    name: "Virgin Islands, U.S.",
    dialCode: "+1340",
    code: "VI",
    codeName: "VI - Virgin Islands, U.S.",
  },
  {
    name: "Wallis and Futuna",
    dialCode: "+681",
    code: "WF",
    codeName: "WF - Wallis and Futuna",
  },
  {
    name: "Yemen",
    dialCode: "+967",
    code: "YE",
    codeName: "YE - Yemen",
  },
  {
    name: "Zambia",
    dialCode: "+260",
    code: "ZM",
    codeName: "ZM - Zambia",
  },
  {
    name: "Zimbabwe",
    dialCode: "+263",
    code: "ZW",
    codeName: "ZW - Zimbabwe",
  },
];

export type { CountryCode, CountryDialCode };
