declare const styles: {
  readonly border: string;
  readonly container: string;
  readonly dashedEye: string;
  readonly dateInputContainer: string;
  readonly head: string;
  readonly helperMessage: string;
  readonly input: string;
  readonly inputContainer: string;
  readonly line: string;
  readonly phoneInputContainer: string;
  readonly rounded: string;
  readonly shadow: string;
  readonly slot: string;
  readonly soft: string;
  readonly square: string;
  readonly timeOption: string;
  readonly timeOptionsContainer: string;
  readonly timePickerContainer: string;
};
export = styles;
