import { BibleBook, BibleVersion, Chapter, Commentary, VerseInsight, Topic, TopicEvent, MostQuotedVerse } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { name: 'Genesis', shortName: 'Gen', testament: 'OT', chapters: 50 },
  { name: 'Exodus', shortName: 'Exod', testament: 'OT', chapters: 40 },
  { name: 'Leviticus', shortName: 'Lev', testament: 'OT', chapters: 27 },
  { name: 'Numbers', shortName: 'Num', testament: 'OT', chapters: 36 },
  { name: 'Deuteronomy', shortName: 'Deut', testament: 'OT', chapters: 34 },
  { name: 'Joshua', shortName: 'Josh', testament: 'OT', chapters: 24 },
  { name: 'Judges', shortName: 'Judg', testament: 'OT', chapters: 21 },
  { name: 'Ruth', shortName: 'Ruth', testament: 'OT', chapters: 4 },
  { name: '1 Samuel', shortName: '1Sam', testament: 'OT', chapters: 31 },
  { name: '2 Samuel', shortName: '2Sam', testament: 'OT', chapters: 24 },
  { name: '1 Kings', shortName: '1Kgs', testament: 'OT', chapters: 22 },
  { name: '2 Kings', shortName: '2Kgs', testament: 'OT', chapters: 25 },
  { name: '1 Chronicles', shortName: '1Chr', testament: 'OT', chapters: 29 },
  { name: '2 Chronicles', shortName: '2Chr', testament: 'OT', chapters: 36 },
  { name: 'Ezra', shortName: 'Ezra', testament: 'OT', chapters: 10 },
  { name: 'Nehemiah', shortName: 'Neh', testament: 'OT', chapters: 13 },
  { name: 'Esther', shortName: 'Esth', testament: 'OT', chapters: 10 },
  { name: 'Job', shortName: 'Job', testament: 'OT', chapters: 42 },
  { name: 'Psalms', shortName: 'Ps', testament: 'OT', chapters: 150 },
  { name: 'Proverbs', shortName: 'Prov', testament: 'OT', chapters: 31 },
  { name: 'Ecclesiastes', shortName: 'Eccl', testament: 'OT', chapters: 12 },
  { name: 'Song of Solomon', shortName: 'Song', testament: 'OT', chapters: 8 },
  { name: 'Isaiah', shortName: 'Isa', testament: 'OT', chapters: 66 },
  { name: 'Jeremiah', shortName: 'Jer', testament: 'OT', chapters: 52 },
  { name: 'Lamentations', shortName: 'Lam', testament: 'OT', chapters: 5 },
  { name: 'Ezekiel', shortName: 'Ezek', testament: 'OT', chapters: 48 },
  { name: 'Daniel', shortName: 'Dan', testament: 'OT', chapters: 12 },
  { name: 'Hosea', shortName: 'Hos', testament: 'OT', chapters: 14 },
  { name: 'Joel', shortName: 'Joel', testament: 'OT', chapters: 3 },
  { name: 'Amos', shortName: 'Amos', testament: 'OT', chapters: 9 },
  { name: 'Obadiah', shortName: 'Obad', testament: 'OT', chapters: 1 },
  { name: 'Jonah', shortName: 'Jonah', testament: 'OT', chapters: 4 },
  { name: 'Micah', shortName: 'Mic', testament: 'OT', chapters: 7 },
  { name: 'Nahum', shortName: 'Nah', testament: 'OT', chapters: 3 },
  { name: 'Habakkuk', shortName: 'Hab', testament: 'OT', chapters: 3 },
  { name: 'Zephaniah', shortName: 'Zeph', testament: 'OT', chapters: 3 },
  { name: 'Haggai', shortName: 'Hag', testament: 'OT', chapters: 2 },
  { name: 'Zechariah', shortName: 'Zech', testament: 'OT', chapters: 14 },
  { name: 'Malachi', shortName: 'Mal', testament: 'OT', chapters: 4 },
  // New Testament
  { name: 'Matthew', shortName: 'Matt', testament: 'NT', chapters: 28 },
  { name: 'Mark', shortName: 'Mark', testament: 'NT', chapters: 16 },
  { name: 'Luke', shortName: 'Luke', testament: 'NT', chapters: 24 },
  { name: 'John', shortName: 'John', testament: 'NT', chapters: 21 },
  { name: 'Acts', shortName: 'Acts', testament: 'NT', chapters: 28 },
  { name: 'Romans', shortName: 'Rom', testament: 'NT', chapters: 16 },
  { name: '1 Corinthians', shortName: '1Cor', testament: 'NT', chapters: 16 },
  { name: '2 Corinthians', shortName: '2Cor', testament: 'NT', chapters: 13 },
  { name: 'Galatians', shortName: 'Gal', testament: 'NT', chapters: 6 },
  { name: 'Ephesians', shortName: 'Eph', testament: 'NT', chapters: 6 },
  { name: 'Philippians', shortName: 'Phil', testament: 'NT', chapters: 4 },
  { name: 'Colossians', shortName: 'Col', testament: 'NT', chapters: 4 },
  { name: '1 Thessalonians', shortName: '1Thess', testament: 'NT', chapters: 5 },
  { name: '2 Thessalonians', shortName: '2Thess', testament: 'NT', chapters: 3 },
  { name: '1 Timothy', shortName: '1Tim', testament: 'NT', chapters: 6 },
  { name: '2 Timothy', shortName: '2Tim', testament: 'NT', chapters: 4 },
  { name: 'Titus', shortName: 'Titus', testament: 'NT', chapters: 3 },
  { name: 'Philemon', shortName: 'Phlm', testament: 'NT', chapters: 1 },
  { name: 'Hebrews', shortName: 'Heb', testament: 'NT', chapters: 13 },
  { name: 'James', shortName: 'Jas', testament: 'NT', chapters: 5 },
  { name: '1 Peter', shortName: '1Pet', testament: 'NT', chapters: 5 },
  { name: '2 Peter', shortName: '2Pet', testament: 'NT', chapters: 3 },
  { name: '1 John', shortName: '1John', testament: 'NT', chapters: 5 },
  { name: '2 John', shortName: '2John', testament: 'NT', chapters: 1 },
  { name: '3 John', shortName: '3John', testament: 'NT', chapters: 1 },
  { name: 'Jude', shortName: 'Jude', testament: 'NT', chapters: 1 },
  { name: 'Revelation', shortName: 'Rev', testament: 'NT', chapters: 22 },
];

const JOHN_1: Record<BibleVersion, Chapter> = {
  ESV: {
    book: 'John', chapter: 1,
    verses: [
      { number: 1, text: 'In the beginning was the Word, and the Word was with God, and the Word was God.' },
      { number: 2, text: 'He was in the beginning with God.' },
      { number: 3, text: 'All things were made through him, and without him was not any thing made that was made.' },
      { number: 4, text: 'In him was life, and the life was the light of men.' },
      { number: 5, text: 'The light shines in the darkness, and the darkness has not overcome it.' },
      { number: 6, text: 'There was a man sent from God, whose name was John.' },
      { number: 7, text: 'He came as a witness, to bear witness about the light, that all might believe through him.' },
      { number: 8, text: 'He was not the light, but came to bear witness about the light.' },
      { number: 9, text: 'The true light, which gives light to everyone, was coming into the world.' },
      { number: 10, text: 'He was in the world, and the world was made through him, yet the world did not know him.' },
      { number: 11, text: 'He came to his own, and his own people did not receive him.' },
      { number: 12, text: 'But to all who did receive him, who believed in his name, he gave the right to become children of God,' },
      { number: 13, text: 'who were born, not of blood nor of the will of the flesh nor of the will of man, but of God.' },
      { number: 14, text: 'And the Word became flesh and dwelt among us, and we have seen his glory, glory as of the only Son from the Father, full of grace and truth.' },
      { number: 15, text: '(John bore witness about him, and cried out, "This was he of whom I said, \'He who comes after me ranks before me, because he was before me.\'")'  },
      { number: 16, text: 'For from his fullness we have all received, grace upon grace.' },
      { number: 17, text: 'For the law was given through Moses; grace and truth came through Jesus Christ.' },
      { number: 18, text: 'No one has ever seen God; the only God, who is at the Father\'s side, he has made him known.' },
      { number: 19, text: 'And this is the testimony of John, when the Jews sent priests and Levites from Jerusalem to ask him, "Who are you?"' },
      { number: 20, text: 'He confessed, and did not deny, but confessed, "I am not the Christ."' },
      { number: 21, text: 'And they asked him, "What then? Are you Elijah?" He said, "I am not." "Are you the Prophet?" And he answered, "No."' },
      { number: 22, text: 'So they said to him, "Who are you? We need to give an answer to those who sent us. What do you say about yourself?"' },
      { number: 23, text: 'He said, "I am the voice of one crying out in the wilderness, \'Make straight the way of the Lord,\' as the prophet Isaiah said."' },
      { number: 24, text: '(Now they had been sent from the Pharisees.)' },
      { number: 25, text: 'They asked him, "Then why are you baptizing, if you are neither the Christ, nor Elijah, nor the Prophet?"' },
      { number: 26, text: 'John answered them, "I baptize with water, but among you stands one you do not know,' },
      { number: 27, text: 'even he who comes after me, the strap of whose sandal I am not worthy to untie."' },
      { number: 28, text: 'These things took place in Bethany across the Jordan, where John was baptizing.' },
      { number: 29, text: 'The next day he saw Jesus coming toward him, and said, "Behold, the Lamb of God, who takes away the sin of the world!' },
      { number: 30, text: 'This is he of whom I said, \'After me comes a man who ranks before me, because he was before me.\'' },
      { number: 31, text: 'I myself did not know him, but for this purpose I came baptizing with water, that he might be revealed to Israel."' },
      { number: 32, text: 'And John bore witness: "I saw the Spirit descend from heaven like a dove, and it remained on him.' },
      { number: 33, text: 'I myself did not know him, but he who sent me to baptize with water said to me, \'He on whom you see the Spirit descend and remain, this is he who baptizes with the Holy Spirit.\'' },
      { number: 34, text: 'And I have seen and have borne witness that this is the Son of God."' },
      { number: 35, text: 'The next day again John was standing with two of his disciples,' },
      { number: 36, text: 'and he looked at Jesus as he walked by and said, "Behold, the Lamb of God!"' },
      { number: 37, text: 'The two disciples heard him say this, and they followed Jesus.' },
      { number: 38, text: 'Jesus turned and saw them following and said to them, "What are you seeking?" And they said to him, "Rabbi" (which means Teacher), "where are you staying?"' },
      { number: 39, text: 'He said to them, "Come and you will see." So they came and saw where he was staying, and they stayed with him that day, for it was about the tenth hour.' },
      { number: 40, text: 'One of the two who heard John speak and followed Jesus was Andrew, Simon Peter\'s brother.' },
      { number: 41, text: 'He first found his own brother Simon and said to him, "We have found the Messiah" (which means Christ).' },
      { number: 42, text: 'He brought him to Jesus. Jesus looked at him and said, "You are Simon the son of John. You shall be called Cephas" (which means Peter).' },
      { number: 43, text: 'The next day Jesus decided to go to Galilee. He found Philip and said to him, "Follow me."' },
      { number: 44, text: 'Now Philip was from Bethsaida, the city of Andrew and Peter.' },
      { number: 45, text: 'Philip found Nathanael and said to him, "We have found him of whom Moses in the Law and also the prophets wrote, Jesus of Nazareth, the son of Joseph."' },
      { number: 46, text: 'Nathanael said to him, "Can anything good come out of Nazareth?" Philip said to him, "Come and see."' },
      { number: 47, text: 'Jesus saw Nathanael coming toward him and said of him, "Behold, an Israelite indeed, in whom there is no deceit!"' },
      { number: 48, text: 'Nathanael said to him, "How do you know me?" Jesus answered him, "Before Philip called you, when you were under the fig tree, I saw you."' },
      { number: 49, text: 'Nathanael answered him, "Rabbi, you are the Son of God! You are the King of Israel!"' },
      { number: 50, text: 'Jesus answered him, "Because I said to you, \'I saw you under the fig tree,\' do you believe? You will see greater things than these."' },
      { number: 51, text: 'And he said to him, "Truly, truly, I say to you, you will see heaven opened, and the angels of God ascending and descending on the Son of Man."' },
    ],
  },
  NIV: {
    book: 'John', chapter: 1,
    verses: [
      { number: 1, text: 'In the beginning was the Word, and the Word was with God, and the Word was God.' },
      { number: 2, text: 'He was with God in the beginning.' },
      { number: 3, text: 'Through him all things were made; without him nothing was made that has been made.' },
      { number: 4, text: 'In him was life, and that life was the light of all mankind.' },
      { number: 5, text: 'The light shines in the darkness, and the darkness has not overcome it.' },
      { number: 6, text: 'There was a man sent from God whose name was John.' },
      { number: 7, text: 'He came as a witness to testify concerning that light, so that through him all might believe.' },
      { number: 8, text: 'He himself was not the light; he came only as a witness to the light.' },
      { number: 9, text: 'The true light that gives light to everyone was coming into the world.' },
      { number: 10, text: 'He was in the world, and though the world was made through him, the world did not recognize him.' },
    ],
  },
  KJV: {
    book: 'John', chapter: 1,
    verses: [
      { number: 1, text: 'In the beginning was the Word, and the Word was with God, and the Word was God.' },
      { number: 2, text: 'The same was in the beginning with God.' },
      { number: 3, text: 'All things were made by him; and without him was not any thing made that was made.' },
      { number: 4, text: 'In him was life; and the life was the light of men.' },
      { number: 5, text: 'And the light shineth in darkness; and the darkness comprehended it not.' },
      { number: 6, text: 'There was a man sent from God, whose name was John.' },
      { number: 7, text: 'The same came for a witness, to bear witness of the Light, that all men through him might believe.' },
      { number: 8, text: 'He was not that Light, but was sent to bear witness of that Light.' },
      { number: 9, text: 'That was the true Light, which lighteth every man that cometh into the world.' },
      { number: 10, text: 'He was in the world, and the world was made by him, and the world knew him not.' },
    ],
  },
  NLT: {
    book: 'John', chapter: 1,
    verses: [
      { number: 1, text: 'In the beginning the Word already existed. The Word was with God, and the Word was God.' },
      { number: 2, text: 'He existed in the beginning with God.' },
      { number: 3, text: 'God created everything through him, and nothing was created except through him.' },
      { number: 4, text: 'The Word gave life to everything that was created, and his life brought light to everyone.' },
      { number: 5, text: 'The light shines in the darkness, and the darkness can never extinguish it.' },
      { number: 6, text: 'God sent a man, John the Baptist,' },
      { number: 7, text: 'to tell about the light so that everyone might believe because of his testimony.' },
      { number: 8, text: 'John himself was not the light; he was simply a witness to tell about the light.' },
      { number: 9, text: 'The one who is the true light, who gives light to everyone, was coming into the world.' },
      { number: 10, text: 'He came into the very world he created, but the world didn\'t recognize him.' },
    ],
  },
};

const PSALM_23: Record<BibleVersion, Chapter> = {
  ESV: {
    book: 'Psalms', chapter: 23,
    verses: [
      { number: 1, text: 'The LORD is my shepherd; I shall not want.' },
      { number: 2, text: 'He makes me lie down in green pastures. He leads me beside still waters.' },
      { number: 3, text: 'He restores my soul. He leads me in paths of righteousness for his name\'s sake.' },
      { number: 4, text: 'Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me; your rod and your staff, they comfort me.' },
      { number: 5, text: 'You prepare a table before me in the presence of my enemies; you anoint my head with oil; my cup overflows.' },
      { number: 6, text: 'Surely goodness and mercy shall follow me all the days of my life, and I shall dwell in the house of the LORD forever.' },
    ],
  },
  NIV: {
    book: 'Psalms', chapter: 23,
    verses: [
      { number: 1, text: 'The LORD is my shepherd, I lack nothing.' },
      { number: 2, text: 'He makes me lie down in green pastures, he leads me beside quiet waters,' },
      { number: 3, text: 'he refreshes my soul. He guides me along the right paths for his name\'s sake.' },
      { number: 4, text: 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.' },
      { number: 5, text: 'You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows.' },
      { number: 6, text: 'Surely your goodness and love will follow me all the days of my life, and I will dwell in the house of the LORD forever.' },
    ],
  },
  KJV: {
    book: 'Psalms', chapter: 23,
    verses: [
      { number: 1, text: 'The LORD is my shepherd; I shall not want.' },
      { number: 2, text: 'He maketh me to lie down in green pastures: he leadeth me beside the still waters.' },
      { number: 3, text: 'He restoreth my soul: he leadeth me in the paths of righteousness for his name\'s sake.' },
      { number: 4, text: 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.' },
      { number: 5, text: 'Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.' },
      { number: 6, text: 'Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.' },
    ],
  },
  NLT: {
    book: 'Psalms', chapter: 23,
    verses: [
      { number: 1, text: 'The LORD is my shepherd; I have all that I need.' },
      { number: 2, text: 'He lets me rest in green meadows; he leads me beside peaceful streams.' },
      { number: 3, text: 'He renews my strength. He guides me along right paths, bringing honor to his name.' },
      { number: 4, text: 'Even when I walk through the darkest valley, I will not be afraid, for you are close beside me. Your rod and your staff protect and comfort me.' },
      { number: 5, text: 'You prepare a feast for me in the presence of my enemies. You honor me by anointing my head with oil. My cup overflows with blessings.' },
      { number: 6, text: 'Surely your goodness and unfailing love will pursue me all the days of my life, and I will live in the house of the LORD forever.' },
    ],
  },
};

const GENESIS_1: Record<BibleVersion, Chapter> = {
  ESV: {
    book: 'Genesis', chapter: 1,
    verses: [
      { number: 1, text: 'In the beginning, God created the heavens and the earth.' },
      { number: 2, text: 'The earth was without form and void, and darkness was over the face of the deep. And the Spirit of God was hovering over the face of the waters.' },
      { number: 3, text: 'And God said, "Let there be light," and there was light.' },
      { number: 4, text: 'And God saw that the light was good. And God separated the light from the darkness.' },
      { number: 5, text: 'God called the light Day, and the darkness he called Night. And there was evening and there was morning, the first day.' },
      { number: 6, text: 'And God said, "Let there be an expanse in the midst of the waters, and let it separate the waters from the waters."' },
      { number: 7, text: 'And God made the expanse and separated the waters that were under the expanse from the waters that were above the expanse. And it was so.' },
      { number: 8, text: 'And God called the expanse Heaven. And there was evening and there was morning, the second day.' },
      { number: 9, text: 'And God said, "Let the waters under the heavens be gathered together into one place, and let the dry land appear." And it was so.' },
      { number: 10, text: 'God called the dry land Earth, and the waters that were gathered together he called Seas. And God saw that it was good.' },
    ],
  },
  NIV: {
    book: 'Genesis', chapter: 1,
    verses: [
      { number: 1, text: 'In the beginning God created the heavens and the earth.' },
      { number: 2, text: 'Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.' },
      { number: 3, text: 'And God said, "Let there be light," and there was light.' },
      { number: 4, text: 'God saw that the light was good, and he separated the light from the darkness.' },
      { number: 5, text: 'God called the light "day," and the darkness he called "night." And there was evening, and there was morning—the first day.' },
    ],
  },
  KJV: {
    book: 'Genesis', chapter: 1,
    verses: [
      { number: 1, text: 'In the beginning God created the heaven and the earth.' },
      { number: 2, text: 'And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.' },
      { number: 3, text: 'And God said, Let there be light: and there was light.' },
      { number: 4, text: 'And God saw the light, that it was good: and God divided the light from the darkness.' },
      { number: 5, text: 'And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.' },
    ],
  },
  NLT: {
    book: 'Genesis', chapter: 1,
    verses: [
      { number: 1, text: 'In the beginning God created the heavens and the earth.' },
      { number: 2, text: 'The earth was formless and empty, and darkness covered the deep waters. And the Spirit of God was hovering over the surface of the waters.' },
      { number: 3, text: 'Then God said, "Let there be light," and there was light.' },
      { number: 4, text: 'And God saw that the light was good. Then he separated the light from the darkness.' },
      { number: 5, text: 'God called the light "day" and the darkness "night." And evening passed and morning came, marking the first day.' },
    ],
  },
};

const ROMANS_8: Record<BibleVersion, Chapter> = {
  ESV: {
    book: 'Romans', chapter: 8,
    verses: [
      { number: 1, text: 'There is therefore now no condemnation for those who are in Christ Jesus.' },
      { number: 2, text: 'For the law of the Spirit of life has set you free in Christ Jesus from the law of sin and death.' },
      { number: 3, text: 'For God has done what the law, weakened by the flesh, could not do. By sending his own Son in the likeness of sinful flesh and for sin, he condemned sin in the flesh,' },
      { number: 4, text: 'in order that the righteous requirement of the law might be fulfilled in us, who walk not according to the flesh but according to the Spirit.' },
      { number: 5, text: 'For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit set their minds on the things of the Spirit.' },
      { number: 6, text: 'For to set the mind on the flesh is death, but to set the mind on the Spirit is life and peace.' },
      { number: 7, text: 'For the mind that is set on the flesh is hostile to God, for it does not submit to God\'s law; indeed, it cannot.' },
      { number: 8, text: 'Those who are in the flesh cannot please God.' },
      { number: 9, text: 'You, however, are not in the flesh but in the Spirit, if in fact the Spirit of God dwells in you. Anyone who does not have the Spirit of Christ does not belong to him.' },
      { number: 10, text: 'But if Christ is in you, although the body is dead because of sin, the Spirit is life because of righteousness.' },
      { number: 28, text: 'And we know that for those who love God all things work together for good, for those who are called according to his purpose.' },
      { number: 31, text: 'What then shall we say to these things? If God is for us, who can be against us?' },
      { number: 37, text: 'No, in all these things we are more than conquerors through him who loved us.' },
      { number: 38, text: 'For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers,' },
      { number: 39, text: 'nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord.' },
    ],
  },
  NIV: {
    book: 'Romans', chapter: 8,
    verses: [
      { number: 1, text: 'Therefore, there is now no condemnation for those who are in Christ Jesus,' },
      { number: 2, text: 'because through Christ Jesus the law of the Spirit who gives life has set you free from the law of sin and death.' },
      { number: 28, text: 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.' },
    ],
  },
  KJV: {
    book: 'Romans', chapter: 8,
    verses: [
      { number: 1, text: 'There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.' },
      { number: 2, text: 'For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.' },
      { number: 28, text: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.' },
    ],
  },
  NLT: {
    book: 'Romans', chapter: 8,
    verses: [
      { number: 1, text: 'So now there is no condemnation for those who belong to Christ Jesus.' },
      { number: 2, text: 'And because you belong to him, the power of the life-giving Spirit has freed you from the power of sin that leads to death.' },
      { number: 28, text: 'And we know that God causes everything to work together for the good of those who love God and are called according to his purpose for them.' },
    ],
  },
};

const SAMPLE_CHAPTERS: Record<string, Record<BibleVersion, Chapter>> = {
  'John-1': JOHN_1,
  'Psalms-23': PSALM_23,
  'Genesis-1': GENESIS_1,
  'Romans-8': ROMANS_8,
};

export function getChapter(book: string, chapter: number, version: BibleVersion): Chapter {
  const key = `${book}-${chapter}`;
  const data = SAMPLE_CHAPTERS[key];
  if (data && data[version]) return data[version];
  const verses = Array.from({ length: 10 }, (_, i) => ({
    number: i + 1,
    text: `[${version}] ${book} ${chapter}:${i + 1} — Sample verse text. Full content will be available when connected to a Bible API.`,
  }));
  return { book, chapter, verses };
}

// ─── Commentaries (every verse for our 4 sample chapters) ───

export const COMMENTARIES: Record<string, Commentary[]> = {
  'John-1': [
    { verse: 1, summary: 'The eternal Word', detail: 'John opens his Gospel by echoing Genesis 1:1, establishing that the Word (Logos) existed before creation. The Greek philosophical concept of Logos is repurposed to describe Jesus as the divine reason and creative power of God.' },
    { verse: 2, summary: 'With God from eternity', detail: 'This verse reinforces the pre-existence of Christ. "He was in the beginning with God" eliminates any notion that the Word was created at some point in time.' },
    { verse: 3, summary: 'Agent of creation', detail: 'The Word is identified as the agent through whom all things were made, echoing Colossians 1:16 and Hebrews 1:2. Nothing in creation exists apart from the Word\'s creative activity.' },
    { verse: 4, summary: 'Life and light', detail: 'The Word is the source of all life, and that life serves as the light of humanity—revelation, truth, and guidance flowing from the divine source.' },
    { verse: 5, summary: 'Light overcomes darkness', detail: 'The present tense "shines" indicates an ongoing reality. Darkness—representing evil, ignorance, and death—cannot extinguish or comprehend the light of Christ.' },
    { verse: 6, summary: 'John the Baptist introduced', detail: 'The narrative shifts to introduce John the Baptist as a divinely commissioned herald. "Sent from God" establishes his prophetic authority.' },
    { verse: 7, summary: 'A witness to the light', detail: 'John\'s purpose was testimony—not to attract followers to himself, but to point all people toward the true light so that they might believe.' },
    { verse: 8, summary: 'Not the light himself', detail: 'John carefully clarifies the Baptist\'s subordinate role. He was a lamp, not the sun; a herald, not the king.' },
    { verse: 9, summary: 'The true light entering', detail: 'The adjective "true" (alēthinos) distinguishes Christ from all partial lights. He is the authentic, ultimate source of spiritual illumination for every person.' },
    { verse: 10, summary: 'World did not know him', detail: 'A tragic irony: the creator entered his own creation, yet the world—the very thing made through him—failed to recognize him.' },
    { verse: 11, summary: 'Rejected by his own', detail: 'Israel, God\'s chosen people, did not receive their Messiah. This rejection is a recurring theme in John\'s Gospel.' },
    { verse: 12, summary: 'Children of God', detail: 'Those who receive Christ and believe in his name receive the extraordinary privilege of becoming God\'s children—a status conferred by grace, not earned by merit.' },
    { verse: 13, summary: 'Born of God', detail: 'Spiritual rebirth originates entirely from God\'s will, not from human descent, physical desire, or human decision. This anticipates the "born again" teaching in John 3.' },
    { verse: 14, summary: 'The Incarnation', detail: 'The climactic verse of the prologue: the eternal Word "became flesh." The Greek "eskēnōsen" (dwelt/tabernacled) recalls God\'s presence in the tabernacle, signaling a new and permanent dwelling of God among humanity.' },
    { verse: 15, summary: 'John\'s testimony', detail: 'The Baptist publicly declares Christ\'s superiority, acknowledging that although Jesus came after him chronologically, Jesus existed before him eternally.' },
    { verse: 16, summary: 'Grace upon grace', detail: 'Believers continuously receive from Christ\'s infinite fullness. "Grace upon grace" suggests wave after wave of divine favor.' },
    { verse: 17, summary: 'Grace and truth', detail: 'The law given through Moses was good but incomplete. Through Jesus Christ came the fullness of grace and truth—fulfillment of what the law pointed toward.' },
    { verse: 18, summary: 'God revealed', detail: 'No one has ever seen God directly. The Son, who is himself God and is in closest relationship with the Father, has made God known—fully and finally.' },
  ],
  'Psalms-23': [
    { verse: 1, summary: 'The Lord as shepherd', detail: 'David opens with the foundational metaphor: God is a shepherd who provides everything needed. "I shall not want" expresses complete trust and satisfaction.' },
    { verse: 2, summary: 'Rest and refreshment', detail: 'Green pastures and still waters represent provision, peace, and restoration. The shepherd leads to places of nourishment and calm.' },
    { verse: 3, summary: 'Soul restoration', detail: 'God renews the weary soul and guides along righteous paths—not for our merit, but for the honor of his own name.' },
    { verse: 4, summary: 'Through the darkest valley', detail: 'Even in the shadow of death, the psalmist fears no evil because of God\'s presence. The rod and staff are instruments of both protection and guidance.' },
    { verse: 5, summary: 'A table prepared', detail: 'God provides abundantly even in the presence of adversaries. Anointing with oil signifies honor and joy; the overflowing cup represents abundant blessing.' },
    { verse: 6, summary: 'Eternal dwelling', detail: 'Goodness and mercy are not merely hoped for but pursued actively by God himself. The psalm concludes with the assurance of dwelling in God\'s house forever.' },
  ],
  'Genesis-1': [
    { verse: 1, summary: 'The beginning of all things', detail: 'The opening verse of the Bible declares God as the uncaused cause of all existence. "In the beginning" marks the start of time, space, and matter.' },
    { verse: 2, summary: 'Formless and void', detail: 'The earth was initially without form (tohu) and void (bohu). The Spirit of God hovering over the waters anticipates the creative work to follow.' },
    { verse: 3, summary: 'Let there be light', detail: 'God creates by speaking—his word carries creative power. Light is the first element called into existence, symbolizing order emerging from chaos.' },
    { verse: 4, summary: 'Light separated from darkness', detail: 'God evaluates his creation as "good" and establishes the fundamental distinction between light and darkness—a theme that runs throughout Scripture.' },
    { verse: 5, summary: 'The first day', detail: 'God names the light "Day" and the darkness "Night." The act of naming demonstrates sovereignty over creation. Evening and morning mark the first day.' },
    { verse: 6, summary: 'The expanse', detail: 'God creates a firmament (raqia) to separate waters above from waters below, establishing the sky as a boundary in the created order.' },
    { verse: 7, summary: 'Waters divided', detail: 'The separation of waters is an act of ordering chaos. Ancient Near Eastern cosmology understood the sky as holding back heavenly waters.' },
    { verse: 8, summary: 'Heaven named', detail: 'God names the expanse "Heaven," completing the second day of creation with another act of ordering and naming.' },
    { verse: 9, summary: 'Dry land appears', detail: 'God gathers the waters to reveal dry ground. This third creative command continues the pattern of separation and distinction.' },
    { verse: 10, summary: 'Earth and seas named', detail: 'God names the dry land "Earth" and the gathered waters "Seas," then declares them good—affirming the goodness of the material world.' },
  ],
  'Romans-8': [
    { verse: 1, summary: 'No condemnation', detail: 'Paul\'s triumphant declaration: those united to Christ by faith are completely free from condemnation. This is the logical conclusion of the argument begun in Romans 1.' },
    { verse: 2, summary: 'Freedom from sin\'s law', detail: 'The Spirit of life operating in Christ Jesus has liberated believers from the binding power of sin and its consequence, death.' },
    { verse: 3, summary: 'What the law could not do', detail: 'The law was powerless to save because human flesh was too weak to obey it. God solved this by sending his own Son in human likeness to deal with sin.' },
    { verse: 4, summary: 'Righteous requirement fulfilled', detail: 'Through Christ, the law\'s righteous demand is satisfied in believers who walk by the Spirit rather than by the flesh.' },
    { verse: 5, summary: 'Flesh vs. Spirit mindset', detail: 'Paul draws a sharp contrast between two orientations of life: the flesh-oriented mind focuses on earthly desires; the Spirit-oriented mind focuses on God\'s purposes.' },
    { verse: 6, summary: 'Death vs. life and peace', detail: 'The outcome of each mindset is stark: the flesh leads to death, while the Spirit leads to life and peace—shalom, total well-being.' },
    { verse: 7, summary: 'Flesh is hostile to God', detail: 'The carnal mind is not merely indifferent to God but actively opposed to him. It cannot submit to God\'s law—it lacks the capacity.' },
    { verse: 8, summary: 'Cannot please God', detail: 'Those controlled by the sinful nature are unable to please God. This is not about occasional failure but a fundamental orientation.' },
    { verse: 9, summary: 'In the Spirit', detail: 'Believers are "in the Spirit" because the Spirit of God dwells in them. Having the Spirit is the defining mark of belonging to Christ.' },
    { verse: 10, summary: 'Spirit gives life', detail: 'Even though the body is subject to death because of sin, the Spirit provides life because of the righteousness secured by Christ.' },
    { verse: 28, summary: 'All things for good', detail: 'One of the most beloved promises in Scripture: God sovereignly orchestrates all circumstances for the ultimate good of those who love him and are called according to his purpose.' },
    { verse: 31, summary: 'God is for us', detail: 'If the sovereign God of the universe is for us, no opposition can ultimately prevail. This rhetorical question invites confidence and assurance.' },
    { verse: 37, summary: 'More than conquerors', detail: 'Believers do not merely survive hardship—they overwhelmingly triumph through Christ who loved them and gave himself for them.' },
    { verse: 38, summary: 'Nothing can separate', detail: 'Paul lists cosmic powers, temporal realities, and spiritual forces. None of them—individually or combined—can sever believers from God\'s love.' },
    { verse: 39, summary: 'Inseparable love', detail: 'The chapter\'s grand conclusion: no dimension of reality can separate us from the love of God that is in Christ Jesus our Lord. This is the believer\'s ultimate security.' },
  ],
};

// ─── Verse Insights ───

export const VERSE_INSIGHTS: Record<string, VerseInsight[]> = {
  'John-1': [
    { verse: 1, crossReferences: ['Genesis 1:1', 'Proverbs 8:22-31', '1 John 1:1-2'], originalLanguage: 'Ἐν ἀρχῇ ἦν ὁ λόγος (En archē ēn ho logos) — The imperfect tense "ēn" indicates continuous past existence, not a point of origin.', historicalContext: 'Written around 90 AD in Ephesus, John\'s prologue bridges Jewish monotheism and Greek philosophy. "Logos" was familiar to both Hellenistic Jews (via Philo) and Greek Stoic philosophers.' },
    { verse: 2, crossReferences: ['Colossians 1:17', 'Hebrews 1:2', 'John 17:5'], originalLanguage: 'οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν (houtos ēn en archē pros ton theon) — "This one was in the beginning with God."', historicalContext: 'Early church fathers used this verse against Arian heresy, which claimed the Son was a created being. The repeated "ēn" (was) reinforces eternal co-existence.' },
    { verse: 3, crossReferences: ['Colossians 1:16', 'Hebrews 1:2', 'Psalm 33:6'], originalLanguage: 'πάντα δι\' αὐτοῦ ἐγένετο (panta di autou egeneto) — "All things through him came into being." The preposition "dia" marks the Word as the agent of creation.', historicalContext: 'Jewish wisdom literature (Proverbs 8, Wisdom of Solomon) personified wisdom as present at creation. John identifies this creative wisdom with Jesus.' },
    { verse: 4, crossReferences: ['John 8:12', 'John 11:25', 'John 14:6'], originalLanguage: 'ἐν αὐτῷ ζωὴ ἦν (en autō zōē ēn) — "In him was life." Zōē refers to eternal, spiritual life rather than mere biological existence (bios).', historicalContext: 'Greek philosophy debated the source of life. John asserts it resides in the Logos, connecting Jewish creation theology with universal questions about existence.' },
    { verse: 5, crossReferences: ['John 3:19', 'Isaiah 9:2', '2 Corinthians 4:6'], originalLanguage: 'ἡ σκοτία αὐτὸ οὐ κατέλαβεν (hē skotia auto ou katelaben) — "The darkness did not overcome/comprehend it." Katalambanō can mean both "overcome" and "understand."', historicalContext: 'The light-darkness motif was central in Jewish apocalyptic literature and the Dead Sea Scrolls. John employs it to frame the cosmic conflict between good and evil.' },
    { verse: 6, crossReferences: ['Matthew 3:1', 'Mark 1:4', 'Malachi 3:1'], originalLanguage: 'ἐγένετο ἄνθρωπος (egeneto anthrōpos) — "There came a man." The aorist "egeneto" (came to be) contrasts with the imperfect "ēn" (was) used of the Logos.', historicalContext: 'John the Baptist was a well-known figure. Josephus mentions him in Antiquities 18.5.2. His following persisted after his death, making clarification of his role necessary.' },
    { verse: 7, crossReferences: ['Acts 19:4', 'John 3:26-30', 'John 5:33-35'], originalLanguage: 'εἰς μαρτυρίαν (eis martyrian) — "For testimony/witness." Martyria is a key Johannine term, appearing 47 times in the Gospel and letters.', historicalContext: 'In the Roman legal system, testimony (martyria) was crucial for establishing truth. John frames the Baptist\'s ministry in legal-testimonial language.' },
    { verse: 8, crossReferences: ['John 1:20', 'John 3:28', 'Acts 13:25'], originalLanguage: 'οὐκ ἦν ἐκεῖνος τὸ φῶς (ouk ēn ekeinos to phōs) — "He was not that light." The emphatic pronoun ekeinos underscores the distinction.', historicalContext: 'Followers of John the Baptist existed as a distinct group well into the first century (Acts 19:1-7). This verse addresses any lingering confusion about the Baptist\'s identity.' },
    { verse: 9, crossReferences: ['John 8:12', 'John 9:5', 'Isaiah 49:6'], originalLanguage: 'τὸ φῶς τὸ ἀληθινόν (to phōs to alēthinon) — "The true light." Alēthinos means "genuine, real" as opposed to "apparent" or "partial."', historicalContext: 'In Greek philosophy, "true" (alēthinos) distinguished reality from shadow (cf. Plato\'s cave allegory). John claims Jesus is the ultimate reality behind all lesser lights.' },
    { verse: 10, crossReferences: ['John 17:25', 'Wisdom 9:9', 'Hebrews 1:2'], originalLanguage: 'ὁ κόσμος αὐτὸν οὐκ ἔγνω (ho kosmos auton ouk egnō) — "The world did not know him." Ginōskō implies relational knowledge, not merely intellectual awareness.', historicalContext: 'First-century Judaism expected the Messiah to be recognized by Israel. The irony that the world\'s creator went unrecognized underscores humanity\'s spiritual blindness.' },
    { verse: 14, crossReferences: ['Philippians 2:6-8', 'Colossians 1:15', '1 Timothy 3:16'], originalLanguage: 'ὁ λόγος σὰρξ ἐγένετο (ho logos sarx egeneto) — "The Word became flesh." "Egeneto" (became) contrasts with "ēn" (was), marking a definitive moment of incarnation.', historicalContext: 'The claim that the divine Logos became "flesh" (sarx) was scandalous to both Greeks and Jews. Greeks saw flesh as inferior; Jews guarded God\'s transcendence. This verse became central to Christological debates.' },
    { verse: 16, crossReferences: ['Ephesians 1:3', 'Colossians 2:9-10', '2 Peter 1:3'], originalLanguage: 'χάριν ἀντὶ χάριτος (charin anti charitos) — "Grace upon grace" or "grace in place of grace." The preposition anti suggests successive waves of grace.', historicalContext: 'In the patron-client culture of the Roman Empire, "grace" (charis) connoted the generous favor of a patron. John transforms this social concept to describe God\'s lavish giving.' },
    { verse: 17, crossReferences: ['Exodus 34:6', 'John 14:6', 'Hebrews 3:3-6'], originalLanguage: 'ἡ χάρις καὶ ἡ ἀλήθεια (hē charis kai hē alētheia) — "Grace and truth" echoes the Hebrew pair hesed we\'emet (steadfast love and faithfulness) from Exodus 34:6.', historicalContext: 'Moses received the law at Sinai, a foundational moment for Israel. John presents Jesus as bringing something greater—the fullness of God\'s covenant love and ultimate truth.' },
    { verse: 18, crossReferences: ['Exodus 33:20', 'John 6:46', 'Colossians 1:15'], originalLanguage: 'μονογενὴς θεός (monogenēs theos) — "The only-begotten God" (some manuscripts read "the only-begotten Son"). Monogenēs means unique, one-of-a-kind.', historicalContext: 'The tension between God\'s invisibility (Exodus 33:20) and human encounters with God (Genesis 32:30) was debated in Judaism. John resolves it: the Son is the definitive revelation of the Father.' },
  ],
  'Psalms-23': [
    { verse: 1, crossReferences: ['Psalm 100:3', 'Isaiah 40:11', 'Ezekiel 34:11-16'], originalLanguage: 'יְהוָה רֹעִי (YHWH ro\'i) — "The LORD [is] my shepherd." The possessive "my" makes this deeply personal. Ro\'eh (shepherd) was also a royal title in the ancient Near East.', historicalContext: 'David, himself a former shepherd, understood the intimate care a shepherd provides. This metaphor also echoed Mesopotamian royal ideology, where kings called themselves "shepherds of their people."' },
    { verse: 2, crossReferences: ['Psalm 46:2-3', 'Revelation 7:17', 'Isaiah 49:10'], originalLanguage: 'בִּנְאוֹת דֶּשֶׁא (bin\'ot deshe) — "In pastures of tender grass." Deshe refers to fresh, young vegetation—the best grazing.', historicalContext: 'In the arid climate of ancient Israel, green pastures and still waters were rare luxuries. David\'s imagery conveyed extraordinary divine provision.' },
    { verse: 3, crossReferences: ['Psalm 19:7', 'Proverbs 3:6', 'Isaiah 43:25'], originalLanguage: 'יְשׁוֹבֵב נַפְשִׁי (yeshobeb nafshi) — "He restores my soul." The verb shub means to return or restore—bringing the soul back to its proper state.', historicalContext: 'Soul (nephesh) in Hebrew encompasses the whole person—vitality, emotions, will. Restoration of the nephesh meant renewal of one\'s entire being.' },
    { verse: 4, crossReferences: ['Psalm 91:1-4', 'Isaiah 43:2', 'Job 10:21-22'], originalLanguage: 'גֵּיא צַלְמָוֶת (gey tsalmawet) — "Valley of the shadow of death" or "valley of deep darkness." The compound word evokes the deepest, most threatening darkness.', historicalContext: 'Judean geography includes steep, narrow valleys (wadis) where predators lurked. Shepherds navigated these treacherous paths regularly, making this metaphor vivid to David\'s original audience.' },
    { verse: 5, crossReferences: ['Psalm 78:19', 'Psalm 104:15', 'Luke 7:46'], originalLanguage: 'דִּשַּׁנְתָּ בַשֶּׁמֶן רֹאשִׁי (dishanta bashemen roshi) — "You anoint my head with oil." Anointing with oil signified honor, celebration, and divine favor.', historicalContext: 'Anointing guests with oil was a sign of hospitality in the ancient Near East. The overflowing cup symbolized extravagant abundance beyond what was needed.' },
    { verse: 6, crossReferences: ['Psalm 27:4', 'Psalm 84:10', 'John 14:2-3'], originalLanguage: 'וְשַׁבְתִּי בְּבֵית יְהוָה (weshavti bebet YHWH) — "And I shall dwell in the house of the LORD." Some read shavti as "return to" rather than "dwell in."', historicalContext: 'The "house of the LORD" refers to the tabernacle/temple—the place of God\'s manifest presence. David expresses the ultimate hope: eternal communion with God.' },
  ],
  'Genesis-1': [
    { verse: 1, crossReferences: ['John 1:1-3', 'Hebrews 11:3', 'Psalm 33:6'], originalLanguage: 'בְּרֵאשִׁית בָּרָא אֱלֹהִים (bereshit bara elohim) — "In the beginning God created." Bara is used exclusively of divine creation—bringing into existence something fundamentally new.', historicalContext: 'Unlike Babylonian creation myths (Enuma Elish) where creation results from conflict between gods, Genesis presents creation as the sovereign, peaceful act of one God.' },
    { verse: 2, crossReferences: ['Jeremiah 4:23', 'Isaiah 45:18', 'Psalm 104:30'], originalLanguage: 'תֹהוּ וָבֹהוּ (tohu wabohu) — "Formless and void." This rhyming pair describes primordial chaos before God\'s ordering work began.', historicalContext: 'Ancient Near Eastern creation accounts often began with a watery chaos. Genesis shares this starting point but diverges radically in its monotheistic theology.' },
    { verse: 3, crossReferences: ['2 Corinthians 4:6', 'Psalm 33:9', 'Hebrews 11:3'], originalLanguage: 'יְהִי אוֹר (yehi or) — "Let there be light." The jussive form of the verb expresses divine command. God creates by speaking.', historicalContext: 'In Egyptian theology, light was associated with the sun god Ra. Genesis depersonalizes light—it is not a deity but a creation of the one true God.' },
    { verse: 4, crossReferences: ['Isaiah 45:7', '1 John 1:5', 'James 1:17'], originalLanguage: 'כִּי טוֹב (ki tov) — "That it was good." Tov means beautiful, fitting, and morally excellent—not merely functional.', historicalContext: 'The repeated declaration "good" (tov) stands against dualistic worldviews that saw matter as inherently evil. The material world is affirmed as God\'s good creation.' },
    { verse: 5, crossReferences: ['Psalm 74:16', 'Psalm 104:20', 'Genesis 8:22'], originalLanguage: 'יוֹם אֶחָד (yom echad) — "Day one" rather than "the first day." The use of a cardinal number (one) rather than ordinal (first) may emphasize the uniqueness of this day.', historicalContext: 'The Jewish day began at evening, which is why "evening and morning" mark each creation day. This pattern continues in Jewish religious observance to this day.' },
    { verse: 6, crossReferences: ['Psalm 19:1', 'Proverbs 8:27-28', 'Job 37:18'], originalLanguage: 'רָקִיעַ (raqia) — "Expanse/firmament." The root raqa means to spread out or hammer thin, like beaten metal. It refers to the sky-dome.', historicalContext: 'Ancient peoples conceived the sky as a solid dome holding back celestial waters. While Genesis uses this language, its theological focus is on God\'s sovereignty over the cosmic structure.' },
    { verse: 7, crossReferences: ['Proverbs 8:28-29', '2 Peter 3:5', 'Job 38:8-11'], originalLanguage: 'וַיַּעַשׂ (wayya\'as) — "And [God] made." The verb \'asah (to make/fashion) complements bara (to create), emphasizing God actively shaping what he spoke into existence.', historicalContext: 'The separation of waters above and below parallels Mesopotamian cosmology (Marduk dividing Tiamat), but Genesis attributes it to one sovereign God acting without conflict or struggle.' },
    { verse: 8, crossReferences: ['Psalm 148:4', 'Deuteronomy 33:26', 'Job 22:14'], originalLanguage: 'שָׁמָיִם (shamayim) — "Heaven/sky." The dual form suggests the ancient concept of multiple heavens or expanses. God names and thus claims authority over the sky.', historicalContext: 'In Canaanite religion, the sky god Baal ruled the heavens. By naming the sky, God demonstrates absolute sovereignty over what pagans worshipped as divine.' },
    { verse: 9, crossReferences: ['Psalm 95:5', 'Job 38:8-11', 'Proverbs 8:29'], originalLanguage: 'יִקָּווּ הַמַּיִם (yiqqawu hammayim) — "Let the waters be gathered." Qawah means to collect or bind together, implying God setting boundaries.', historicalContext: 'In Mesopotamian myths, the sea was a threatening chaos deity (Tiamat). In Genesis, the waters simply obey God\'s command, reflecting absolute divine authority over nature.' },
    { verse: 10, crossReferences: ['Psalm 24:1-2', 'Psalm 95:5', 'Nehemiah 9:6'], originalLanguage: 'אֶרֶץ (erets) and יַמִּים (yammim) — "Earth" and "Seas." God names both, asserting ownership. In the ancient world, naming was an act of authority and dominion.', historicalContext: 'The Canaanite sea god Yam was a feared deity. By casually naming the seas, Genesis demythologizes the ocean, presenting it as merely one part of God\'s ordered creation.' },
  ],
  'Romans-8': [
    { verse: 1, crossReferences: ['Romans 5:1', 'John 3:18', 'John 5:24'], originalLanguage: 'οὐδὲν κατάκριμα (ouden katakrima) — "No condemnation." Katakrima is a legal term meaning the sentence of punishment following a guilty verdict.', historicalContext: 'Roman law was the most developed legal system of the ancient world. Paul uses legal terminology his Roman audience would understand: the verdict against believers has been fully set aside.' },
    { verse: 2, crossReferences: ['Galatians 5:1', 'John 8:32-36', '2 Corinthians 3:17'], originalLanguage: 'ὁ νόμος τοῦ πνεύματος τῆς ζωῆς (ho nomos tou pneumatos tēs zōēs) — "The law of the Spirit of life." This "law" (governing principle) operates in the opposite direction from sin\'s law.', historicalContext: 'Paul contrasts two operating systems: the old regime of sin and death versus the new regime of the Spirit and life. This reflects the apocalyptic "two ages" framework in Jewish thought.' },
    { verse: 3, crossReferences: ['Hebrews 7:18-19', '2 Corinthians 5:21', 'Galatians 4:4-5'], originalLanguage: 'ἐν ὁμοιώματι σαρκὸς ἁμαρτίας (en homoiōmati sarkos hamartias) — "In the likeness of sinful flesh." Homoiōma means a real likeness—Jesus was fully human, yet without sin.', historicalContext: 'This careful phrasing avoids both docetism (denying Jesus\'s real humanity) and the idea that Jesus had a sinful nature. It became key in later Christological formulations.' },
    { verse: 4, crossReferences: ['Galatians 5:16', 'Galatians 5:25', 'Colossians 2:10'], originalLanguage: 'τὸ δικαίωμα τοῦ νόμου (to dikaiōma tou nomou) — "The righteous requirement of the law." Dikaiōma means the just demand or legal requirement.', historicalContext: 'Paul argued that Christ fulfilled the law\'s demands on behalf of believers, enabling them to live by the Spirit rather than futilely trying to keep the law in their own strength.' },
    { verse: 5, crossReferences: ['Galatians 5:17', 'Galatians 6:8', 'Colossians 3:2'], originalLanguage: 'φρονοῦσιν (phronousin) — "Set their minds on." Phroneō involves the whole orientation of a person\'s thinking, values, and priorities—not just passing thoughts.', historicalContext: 'Greco-Roman philosophy debated the relationship between mind (nous) and desire (epithumia). Paul reframes the issue: the fundamental division is between flesh-oriented and Spirit-oriented living.' },
    { verse: 6, crossReferences: ['Galatians 6:8', 'John 6:63', 'Romans 6:23'], originalLanguage: 'τὸ φρόνημα τῆς σαρκός (to phronēma tēs sarkos) — "The mindset of the flesh." Phronēma refers to one\'s settled disposition or habitual way of thinking.', historicalContext: 'The Stoics valued apatheia (freedom from passions) as the path to peace. Paul offers a different solution: peace comes not from suppressing passions but from being oriented by the Spirit.' },
    { verse: 28, crossReferences: ['Genesis 50:20', 'Jeremiah 29:11', 'Ephesians 1:11'], originalLanguage: 'συνεργεῖ εἰς ἀγαθόν (synergei eis agathon) — "Works together for good." Synergeō means to cooperate, collaborate—God weaves all threads into a good design.', historicalContext: 'Stoic philosophy taught that fate controlled all events. Paul affirms divine sovereignty but adds a personal dimension: God works all things for the good of those who love him.' },
    { verse: 31, crossReferences: ['Psalm 118:6', 'Numbers 14:9', 'Isaiah 8:10'], originalLanguage: 'εἰ ὁ θεὸς ὑπὲρ ἡμῶν (ei ho theos hyper hēmōn) — "If God [is] for us." The conditional ei with indicative assumes a true condition: since God is for us.', historicalContext: 'In Roman courts, having a powerful patron (advocatus) ensured favorable outcomes. Paul declares God as the ultimate patron and advocate.' },
    { verse: 37, crossReferences: ['2 Corinthians 2:14', '1 John 5:4', 'Revelation 12:11'], originalLanguage: 'ὑπερνικῶμεν (hypernikōmen) — "We are more than conquerors." Hyper-nikaō is a compound verb meaning to be super-victorious, to win an overwhelming victory.', historicalContext: 'Roman culture celebrated military triumph (triumphus). Paul uses victory language but redefines it: Christian triumph comes not through military might but through the love of Christ.' },
    { verse: 38, crossReferences: ['Ephesians 6:12', 'Colossians 1:16', '1 Peter 3:22'], originalLanguage: 'οὔτε ἄγγελοι οὔτε ἀρχαί (oute angeloi oute archai) — "Neither angels nor rulers." Archai refers to cosmic powers or spiritual authorities in the heavenly realm.', historicalContext: 'First-century people were deeply anxious about cosmic powers (astrological forces, demons, fate). Paul\'s list addresses every category of feared power, declaring Christ\'s love supreme over all.' },
    { verse: 39, crossReferences: ['Ephesians 3:18-19', 'Psalm 139:7-12', 'Deuteronomy 31:6'], originalLanguage: 'οὔτε ὕψωμα οὔτε βάθος (oute hypsōma oute bathos) — "Neither height nor depth." These may be astrological terms for the highest and lowest points of a star\'s orbit.', historicalContext: 'Paul encompasses all of reality—spatial, temporal, spiritual—to make an exhaustive argument. Nothing in the entire created order can break the bond of God\'s love in Christ Jesus.' },
  ],
};

// ─── Topics (6 topics, 2-3 events each, most-quoted per event) ───

// Figma "Topics" categories — Mobile App section
export const TOPICS: Topic[] = [
  { id: 'events', name: 'Events', description: 'Key events in biblical history', icon: 'Sparkles' },
  { id: 'prophecies', name: 'Prophecies', description: 'Prophetic words and their fulfillment', icon: 'Eye' },
  { id: 'parables', name: 'Parables', description: 'Stories Jesus told to teach truth', icon: 'BookOpen' },
  { id: 'themes', name: 'Themes', description: 'Faith, love, prayer, wisdom, salvation, grace', icon: 'Heart' },
  { id: 'top-verses', name: 'Top Verses', description: 'The most quoted and beloved verses', icon: 'Zap' },
  { id: 'promises', name: 'Promises / Commands / Warnings', description: 'What God promises, commands, and warns', icon: 'Shield' },
  { id: 'covenants', name: 'Covenants & Covenant Signs', description: 'God\'s covenants with his people', icon: 'MessageCircle' },
  { id: 'attributes', name: 'Attributes of God', description: 'Who God is and what he is like', icon: 'Sparkles' },
  { id: 'christology', name: 'Chistology: Title & Offices of Jesus', description: 'The titles and offices of Jesus Christ', icon: 'Heart' },
];

export const TOPIC_EVENTS: TopicEvent[] = [
  // Events — salvation-history milestones
  { id: 'event-creation', topicId: 'events', title: 'The Creation of the World', description: 'God creates the heavens, the earth, and all life in six days, culminating in the creation of humanity.', references: ['Genesis 1:1-2:3'] },
  { id: 'event-fall', topicId: 'events', title: 'The Fall of Man', description: 'Adam and Eve disobey God by eating from the tree of the knowledge of good and evil, and sin enters the world.', references: ['Genesis 3:1-24'] },
  { id: 'event-cain', topicId: 'events', title: 'Cain Murders Abel', description: 'Cain kills his brother Abel out of jealousy, becoming the first murderer and receiving God\'s mark.', references: ['Genesis 4:1-16'] },
  { id: 'event-flood', topicId: 'events', title: 'The Great Flood', description: 'God sends a global flood to judge human wickedness; Noah and his family are saved in the ark.', references: ['Genesis 6:5-9:17'] },
  { id: 'event-covenant-noah', topicId: 'events', title: 'God\'s Covenant with Noah', description: 'God promises never again to destroy the earth by flood and establishes the rainbow as a sign.', references: ['Genesis 9:8-17'] },
  { id: 'event-babel', topicId: 'events', title: 'The Tower of Babel', description: 'Humanity\'s attempt to build a tower to the heavens is confused by God scattering languages.', references: ['Genesis 11:1-9'] },
  { id: 'event-exodus', topicId: 'events', title: 'The Exodus', description: 'God delivers Israel from slavery in Egypt through Moses and the ten plagues.', references: ['Exodus 12-14'] },
  { id: 'event-cross', topicId: 'events', title: 'The Cross', description: 'Jesus is crucified for the sins of the world on Golgotha.', references: ['John 19:17-30', 'Romans 5:8'] },
  { id: 'event-resurrection', topicId: 'events', title: 'The Resurrection', description: 'Jesus rises from the dead on the third day, conquering sin and death.', references: ['Matthew 28:1-10', '1 Corinthians 15:3-8'] },

  // Prophecies
  { id: 'prophecy-messiah', topicId: 'prophecies', title: 'The Coming Messiah', description: 'Old Testament prophecies foretelling the birth, ministry, and mission of the Messiah.', references: ['Isaiah 7:14', 'Micah 5:2', 'Isaiah 53'] },
  { id: 'prophecy-virgin-birth', topicId: 'prophecies', title: 'The Virgin Birth', description: 'Isaiah\'s sign that the virgin shall conceive and bear a son called Immanuel.', references: ['Isaiah 7:14', 'Matthew 1:22-23'] },
  { id: 'prophecy-suffering-servant', topicId: 'prophecies', title: 'The Suffering Servant', description: 'Isaiah\'s song of the servant who would be pierced for our transgressions.', references: ['Isaiah 53:1-12'] },
  { id: 'prophecy-end-times', topicId: 'prophecies', title: 'End Times', description: 'Prophecies about the return of Christ, final judgment, and new creation.', references: ['Matthew 24', 'Revelation 19-22'] },

  // Parables
  { id: 'parable-sower', topicId: 'parables', title: 'The Sower', description: 'A sower scatters seed on four kinds of soil, illustrating different responses to God\'s word.', references: ['Matthew 13:1-23', 'Mark 4:1-20', 'Luke 8:4-15'] },
  { id: 'parable-samaritan', topicId: 'parables', title: 'The Good Samaritan', description: 'Jesus teaches that love crosses every boundary through the story of a compassionate Samaritan.', references: ['Luke 10:25-37'] },
  { id: 'parable-prodigal', topicId: 'parables', title: 'The Prodigal Son', description: 'A father\'s unmerited grace toward his wayward son who returns home.', references: ['Luke 15:11-32'] },
  { id: 'parable-wedding-feast', topicId: 'parables', title: 'The Wedding Feast', description: 'The kingdom of heaven is like a king who gave a wedding feast for his son.', references: ['Matthew 22:1-14'] },
  { id: 'parable-mustard-seed', topicId: 'parables', title: 'The Mustard Seed', description: 'The kingdom of heaven is like a mustard seed — small but grows into a tree.', references: ['Matthew 13:31-32', 'Mark 4:30-32'] },

  // Themes
  { id: 'theme-faith', topicId: 'themes', title: 'Faith', description: 'Trust and belief in God — Abraham\'s call, Hebrews 11, justification by faith.', references: ['Hebrews 11', 'Romans 4', 'Ephesians 2:8-9'] },
  { id: 'theme-love', topicId: 'themes', title: 'Love', description: 'God\'s love and how we love others — John 3:16, the love chapter, loving your neighbor.', references: ['1 Corinthians 13', 'John 3:16', '1 John 4:7-21'] },
  { id: 'theme-prayer', topicId: 'themes', title: 'Prayer', description: 'Communication with God — the Lord\'s Prayer, persistent prayer, praying in the Spirit.', references: ['Matthew 6:9-13', 'Luke 11:1-13', 'Ephesians 6:18'] },
  { id: 'theme-wisdom', topicId: 'themes', title: 'Wisdom', description: 'Godly wisdom and understanding — Solomon, Proverbs, and wisdom from above.', references: ['Proverbs 1-9', 'James 3:13-18'] },
  { id: 'theme-salvation', topicId: 'themes', title: 'Salvation', description: 'God\'s plan for redeeming humanity through Jesus Christ.', references: ['Romans 3:23-26', 'Ephesians 2:1-10'] },
  { id: 'theme-grace', topicId: 'themes', title: 'Grace', description: 'Unmerited favor from God — grace upon grace, grace for salvation, grace for service.', references: ['John 1:16-17', 'Romans 5:15-21', '2 Corinthians 12:9'] },
  { id: 'theme-hope', topicId: 'themes', title: 'Hope', description: 'Confident expectation of God\'s promises — hope in affliction, hope of glory.', references: ['Romans 5:1-5', 'Hebrews 6:19'] },

  // Top Verses
  { id: 'topverse-john-316', topicId: 'top-verses', title: 'John 3:16', description: 'For God so loved the world, that he gave his only Son.', references: ['John 3:16'] },
  { id: 'topverse-psalm-23', topicId: 'top-verses', title: 'Psalm 23', description: 'The LORD is my shepherd, I shall not want.', references: ['Psalm 23:1-6'] },
  { id: 'topverse-philippians-413', topicId: 'top-verses', title: 'Philippians 4:13', description: 'I can do all things through him who strengthens me.', references: ['Philippians 4:13'] },
  { id: 'topverse-jeremiah-2911', topicId: 'top-verses', title: 'Jeremiah 29:11', description: 'For I know the plans I have for you, declares the LORD.', references: ['Jeremiah 29:11'] },
  { id: 'topverse-romans-828', topicId: 'top-verses', title: 'Romans 8:28', description: 'All things work together for good for those who love God.', references: ['Romans 8:28'] },
  { id: 'topverse-proverbs-35', topicId: 'top-verses', title: 'Proverbs 3:5-6', description: 'Trust in the LORD with all your heart and lean not on your own understanding.', references: ['Proverbs 3:5-6'] },

  // Promises / Commands / Warnings
  { id: 'promise-presence', topicId: 'promises', title: 'I Will Be With You', description: 'God\'s promise to be with his people always — with Moses, Joshua, and the disciples.', references: ['Exodus 3:12', 'Joshua 1:9', 'Matthew 28:20'] },
  { id: 'promise-provision', topicId: 'promises', title: 'God\'s Provision', description: 'God will supply all your needs according to his riches in glory.', references: ['Philippians 4:19', 'Matthew 6:25-34'] },
  { id: 'command-great', topicId: 'promises', title: 'The Great Commandment', description: 'Love the Lord your God and love your neighbor as yourself.', references: ['Matthew 22:36-40', 'Mark 12:30-31'] },
  { id: 'command-commission', topicId: 'promises', title: 'The Great Commission', description: 'Go and make disciples of all nations.', references: ['Matthew 28:18-20'] },
  { id: 'warning-judgment', topicId: 'promises', title: 'Warnings of Judgment', description: 'Prophetic warnings about coming judgment and the need for repentance.', references: ['Matthew 24', '2 Peter 3:9-10'] },

  // Covenants
  { id: 'covenant-noah', topicId: 'covenants', title: 'The Noahic Covenant', description: 'God\'s covenant with Noah, sealed with the rainbow, never again to flood the earth.', references: ['Genesis 9:8-17'] },
  { id: 'covenant-abraham', topicId: 'covenants', title: 'The Abrahamic Covenant', description: 'God\'s covenant with Abraham promising land, descendants, and blessing for all nations.', references: ['Genesis 12:1-3', 'Genesis 15', 'Genesis 17'] },
  { id: 'covenant-moses', topicId: 'covenants', title: 'The Mosaic Covenant', description: 'God\'s covenant with Israel at Mount Sinai, giving the Law.', references: ['Exodus 19-24'] },
  { id: 'covenant-david', topicId: 'covenants', title: 'The Davidic Covenant', description: 'God\'s covenant promising David a perpetual dynasty and an eternal king.', references: ['2 Samuel 7:8-16'] },
  { id: 'covenant-new', topicId: 'covenants', title: 'The New Covenant', description: 'The covenant in Jesus\' blood, writing God\'s law on our hearts.', references: ['Jeremiah 31:31-34', 'Luke 22:20', 'Hebrews 8:8-12'] },

  // Attributes of God
  { id: 'attribute-holiness', topicId: 'attributes', title: 'Holiness', description: 'God is holy, holy, holy — set apart and morally perfect.', references: ['Isaiah 6:1-7', '1 Peter 1:15-16'] },
  { id: 'attribute-love', topicId: 'attributes', title: 'Love', description: 'God is love — his steadfast love endures forever.', references: ['1 John 4:8', 'Psalm 136'] },
  { id: 'attribute-justice', topicId: 'attributes', title: 'Justice', description: 'God is just — he will judge the world with righteousness.', references: ['Deuteronomy 32:4', 'Psalm 9:7-8'] },
  { id: 'attribute-mercy', topicId: 'attributes', title: 'Mercy', description: 'God\'s mercies are new every morning; great is his faithfulness.', references: ['Lamentations 3:22-23', 'Ephesians 2:4-5'] },
  { id: 'attribute-faithful', topicId: 'attributes', title: 'Faithfulness', description: 'God is faithful — he cannot deny himself or break his promises.', references: ['2 Timothy 2:13', 'Deuteronomy 7:9'] },
  { id: 'attribute-sovereign', topicId: 'attributes', title: 'Sovereignty', description: 'God rules over all creation and works all things according to his will.', references: ['Psalm 115:3', 'Ephesians 1:11'] },

  // Christology
  { id: 'christ-messiah', topicId: 'christology', title: 'Messiah / Christ', description: 'Jesus is the Anointed One, the promised Savior of Israel and the world.', references: ['Matthew 16:16', 'John 1:41'] },
  { id: 'christ-lord', topicId: 'christology', title: 'Lord', description: 'Jesus is Lord — the Greek kyrios used for Yahweh in the Septuagint.', references: ['Philippians 2:9-11', 'Romans 10:9'] },
  { id: 'christ-king', topicId: 'christology', title: 'King of Kings', description: 'Jesus is the King of kings and Lord of lords.', references: ['Revelation 19:16', 'Matthew 2:2'] },
  { id: 'christ-priest', topicId: 'christology', title: 'Great High Priest', description: 'Jesus is our great high priest after the order of Melchizedek.', references: ['Hebrews 4:14-16', 'Hebrews 7'] },
  { id: 'christ-lamb', topicId: 'christology', title: 'Lamb of God', description: 'Behold, the Lamb of God who takes away the sin of the world.', references: ['John 1:29', 'Revelation 5:6-14'] },
  { id: 'christ-word', topicId: 'christology', title: 'The Word', description: 'In the beginning was the Word, and the Word was with God, and the Word was God.', references: ['John 1:1-14', 'Revelation 19:13'] },
];

export const MOST_QUOTED: Record<string, MostQuotedVerse[]> = {
  'faith-1': [
    { reference: 'Hebrews 11:1', book: 'Hebrews', chapter: 11, verse: 1, text: 'Now faith is the assurance of things hoped for, the conviction of things not seen.', quoteCount: 2847 },
    { reference: 'Genesis 15:6', book: 'Genesis', chapter: 15, verse: 6, text: 'And he believed the LORD, and he counted it to him as righteousness.', quoteCount: 1923 },
    { reference: 'Romans 4:3', book: 'Romans', chapter: 4, verse: 3, text: 'Abraham believed God, and it was counted to him as righteousness.', quoteCount: 1654 },
    { reference: 'Hebrews 11:8', book: 'Hebrews', chapter: 11, verse: 8, text: 'By faith Abraham obeyed when he was called to go out to a place he was to receive as an inheritance.', quoteCount: 1432 },
    { reference: 'Genesis 12:1', book: 'Genesis', chapter: 12, verse: 1, text: 'Now the LORD said to Abram, "Go from your country and your kindred and your father\'s house to the land that I will show you."', quoteCount: 1201 },
  ],
  'faith-2': [
    { reference: 'Exodus 14:14', book: 'Exodus', chapter: 14, verse: 14, text: 'The LORD will fight for you, and you have only to be silent.', quoteCount: 3102 },
    { reference: 'Exodus 14:13', book: 'Exodus', chapter: 14, verse: 13, text: 'Fear not, stand firm, and see the salvation of the LORD.', quoteCount: 2456 },
    { reference: 'Hebrews 11:29', book: 'Hebrews', chapter: 11, verse: 29, text: 'By faith the people crossed the Red Sea as on dry land.', quoteCount: 1789 },
    { reference: 'Psalm 77:19', book: 'Psalms', chapter: 77, verse: 19, text: 'Your way was through the sea, your path through the great waters.', quoteCount: 987 },
    { reference: 'Isaiah 43:2', book: 'Isaiah', chapter: 43, verse: 2, text: 'When you pass through the waters, I will be with you.', quoteCount: 876 },
  ],
  'faith-3': [
    { reference: '1 Samuel 17:47', book: '1 Samuel', chapter: 17, verse: 47, text: 'The battle is the LORD\'s, and he will give you into our hand.', quoteCount: 2134 },
    { reference: '1 Samuel 17:45', book: '1 Samuel', chapter: 17, verse: 45, text: 'I come to you in the name of the LORD of hosts, the God of the armies of Israel.', quoteCount: 1876 },
    { reference: 'Psalm 27:1', book: 'Psalms', chapter: 27, verse: 1, text: 'The LORD is my light and my salvation; whom shall I fear?', quoteCount: 1654 },
    { reference: 'Philippians 4:13', book: 'Philippians', chapter: 4, verse: 13, text: 'I can do all things through him who strengthens me.', quoteCount: 1432 },
    { reference: '2 Timothy 1:7', book: '2 Timothy', chapter: 1, verse: 7, text: 'For God gave us a spirit not of fear but of power and love and self-control.', quoteCount: 1201 },
  ],
  'love-1': [
    { reference: 'John 3:16', book: 'John', chapter: 3, verse: 16, text: 'For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.', quoteCount: 5234 },
    { reference: 'Romans 5:8', book: 'Romans', chapter: 5, verse: 8, text: 'But God shows his love for us in that while we were still sinners, Christ died for us.', quoteCount: 3421 },
    { reference: '1 John 4:9', book: '1 John', chapter: 4, verse: 9, text: 'In this the love of God was made manifest among us, that God sent his only Son into the world.', quoteCount: 2145 },
    { reference: 'John 15:13', book: 'John', chapter: 15, verse: 13, text: 'Greater love has no one than this, that someone lay down his life for his friends.', quoteCount: 1987 },
    { reference: 'Romans 8:39', book: 'Romans', chapter: 8, verse: 39, text: 'Nothing will be able to separate us from the love of God in Christ Jesus our Lord.', quoteCount: 1654 },
  ],
  'love-2': [
    { reference: 'Luke 10:27', book: 'Luke', chapter: 10, verse: 27, text: 'You shall love the Lord your God with all your heart and your neighbor as yourself.', quoteCount: 2876 },
    { reference: 'Luke 10:37', book: 'Luke', chapter: 10, verse: 37, text: 'Go, and do likewise.', quoteCount: 2134 },
    { reference: 'Galatians 5:14', book: 'Galatians', chapter: 5, verse: 14, text: 'The whole law is fulfilled in one word: "You shall love your neighbor as yourself."', quoteCount: 1654 },
    { reference: 'James 2:8', book: 'James', chapter: 2, verse: 8, text: 'If you really fulfill the royal law according to the Scripture, "You shall love your neighbor as yourself," you are doing well.', quoteCount: 1234 },
    { reference: 'Matthew 22:39', book: 'Matthew', chapter: 22, verse: 39, text: 'You shall love your neighbor as yourself.', quoteCount: 1102 },
  ],
  'love-3': [
    { reference: '1 Corinthians 13:4', book: '1 Corinthians', chapter: 13, verse: 4, text: 'Love is patient and kind; love does not envy or boast; it is not arrogant.', quoteCount: 4321 },
    { reference: '1 Corinthians 13:13', book: '1 Corinthians', chapter: 13, verse: 13, text: 'So now faith, hope, and love abide, these three; but the greatest of these is love.', quoteCount: 3654 },
    { reference: '1 Corinthians 13:7', book: '1 Corinthians', chapter: 13, verse: 7, text: 'Love bears all things, believes all things, hopes all things, endures all things.', quoteCount: 2987 },
    { reference: '1 Corinthians 13:8', book: '1 Corinthians', chapter: 13, verse: 8, text: 'Love never ends.', quoteCount: 2345 },
    { reference: '1 John 4:8', book: '1 John', chapter: 4, verse: 8, text: 'Anyone who does not love does not know God, because God is love.', quoteCount: 1987 },
  ],
  'prayer-1': [
    { reference: 'Matthew 6:9', book: 'Matthew', chapter: 6, verse: 9, text: 'Our Father in heaven, hallowed be your name.', quoteCount: 4567 },
    { reference: 'Philippians 4:6', book: 'Philippians', chapter: 4, verse: 6, text: 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.', quoteCount: 3210 },
    { reference: 'Matthew 7:7', book: 'Matthew', chapter: 7, verse: 7, text: 'Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you.', quoteCount: 2876 },
    { reference: '1 Thessalonians 5:17', book: '1 Thessalonians', chapter: 5, verse: 17, text: 'Pray without ceasing.', quoteCount: 2345 },
    { reference: 'Jeremiah 29:12', book: 'Jeremiah', chapter: 29, verse: 12, text: 'Then you will call upon me and come and pray to me, and I will hear you.', quoteCount: 1654 },
  ],
  'prayer-2': [
    { reference: '1 Kings 18:37', book: '1 Kings', chapter: 18, verse: 37, text: 'Answer me, O LORD, answer me, that this people may know that you, O LORD, are God.', quoteCount: 1876 },
    { reference: 'James 5:16', book: 'James', chapter: 5, verse: 16, text: 'The prayer of a righteous person has great power as it is working.', quoteCount: 2654 },
    { reference: 'Psalm 50:15', book: 'Psalms', chapter: 50, verse: 15, text: 'Call upon me in the day of trouble; I will deliver you, and you shall glorify me.', quoteCount: 1432 },
    { reference: 'Isaiah 65:24', book: 'Isaiah', chapter: 65, verse: 24, text: 'Before they call I will answer; while they are yet speaking I will hear.', quoteCount: 1234 },
    { reference: 'Psalm 145:18', book: 'Psalms', chapter: 145, verse: 18, text: 'The LORD is near to all who call on him, to all who call on him in truth.', quoteCount: 1102 },
  ],
  'wisdom-1': [
    { reference: 'Proverbs 9:10', book: 'Proverbs', chapter: 9, verse: 10, text: 'The fear of the LORD is the beginning of wisdom, and the knowledge of the Holy One is insight.', quoteCount: 3456 },
    { reference: 'James 1:5', book: 'James', chapter: 1, verse: 5, text: 'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach.', quoteCount: 2987 },
    { reference: '1 Kings 3:9', book: '1 Kings', chapter: 3, verse: 9, text: 'Give your servant therefore an understanding mind to govern your people, that I may discern between good and evil.', quoteCount: 1876 },
    { reference: 'Proverbs 2:6', book: 'Proverbs', chapter: 2, verse: 6, text: 'For the LORD gives wisdom; from his mouth come knowledge and understanding.', quoteCount: 1654 },
    { reference: 'Colossians 2:3', book: 'Colossians', chapter: 2, verse: 3, text: 'In whom are hidden all the treasures of wisdom and knowledge.', quoteCount: 1234 },
  ],
  'wisdom-2': [
    { reference: 'Proverbs 1:7', book: 'Proverbs', chapter: 1, verse: 7, text: 'The fear of the LORD is the beginning of knowledge; fools despise wisdom and instruction.', quoteCount: 3102 },
    { reference: 'Proverbs 3:5-6', book: 'Proverbs', chapter: 3, verse: 5, text: 'Trust in the LORD with all your heart, and do not lean on your own understanding.', quoteCount: 4567 },
    { reference: 'Proverbs 4:7', book: 'Proverbs', chapter: 4, verse: 7, text: 'The beginning of wisdom is this: Get wisdom, and whatever you get, get insight.', quoteCount: 1876 },
    { reference: 'Proverbs 16:9', book: 'Proverbs', chapter: 16, verse: 9, text: 'The heart of man plans his way, but the LORD establishes his steps.', quoteCount: 1654 },
    { reference: 'Ecclesiastes 7:12', book: 'Ecclesiastes', chapter: 7, verse: 12, text: 'Wisdom preserves the life of him who has it.', quoteCount: 987 },
  ],
  'wisdom-3': [
    { reference: 'James 3:17', book: 'James', chapter: 3, verse: 17, text: 'But the wisdom from above is first pure, then peaceable, gentle, open to reason, full of mercy and good fruits.', quoteCount: 2345 },
    { reference: 'James 1:5', book: 'James', chapter: 1, verse: 5, text: 'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach.', quoteCount: 2987 },
    { reference: 'Proverbs 2:6', book: 'Proverbs', chapter: 2, verse: 6, text: 'For the LORD gives wisdom; from his mouth come knowledge and understanding.', quoteCount: 1654 },
    { reference: 'Colossians 3:16', book: 'Colossians', chapter: 3, verse: 16, text: 'Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom.', quoteCount: 1432 },
    { reference: '1 Corinthians 1:30', book: '1 Corinthians', chapter: 1, verse: 30, text: 'He is the source of your life in Christ Jesus, whom God made our wisdom and our righteousness.', quoteCount: 1102 },
  ],
  'salvation-1': [
    { reference: 'Exodus 15:2', book: 'Exodus', chapter: 15, verse: 2, text: 'The LORD is my strength and my song, and he has become my salvation.', quoteCount: 2345 },
    { reference: 'Psalm 27:1', book: 'Psalms', chapter: 27, verse: 1, text: 'The LORD is my light and my salvation; whom shall I fear?', quoteCount: 2876 },
    { reference: 'Isaiah 12:2', book: 'Isaiah', chapter: 12, verse: 2, text: 'Behold, God is my salvation; I will trust, and will not be afraid.', quoteCount: 1654 },
    { reference: 'Acts 4:12', book: 'Acts', chapter: 4, verse: 12, text: 'And there is salvation in no one else, for there is no other name under heaven given among men by which we must be saved.', quoteCount: 1987 },
    { reference: 'Titus 2:11', book: 'Titus', chapter: 2, verse: 11, text: 'For the grace of God has appeared, bringing salvation for all people.', quoteCount: 1102 },
  ],
  'salvation-2': [
    { reference: 'John 3:16', book: 'John', chapter: 3, verse: 16, text: 'For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.', quoteCount: 5234 },
    { reference: 'Romans 6:23', book: 'Romans', chapter: 6, verse: 23, text: 'For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.', quoteCount: 3876 },
    { reference: 'Ephesians 2:8-9', book: 'Ephesians', chapter: 2, verse: 8, text: 'For by grace you have been saved through faith. And this is not your own doing; it is the gift of God.', quoteCount: 3456 },
    { reference: 'Isaiah 53:5', book: 'Isaiah', chapter: 53, verse: 5, text: 'But he was pierced for our transgressions; he was crushed for our iniquities.', quoteCount: 2876 },
    { reference: '1 Peter 2:24', book: '1 Peter', chapter: 2, verse: 24, text: 'He himself bore our sins in his body on the tree, that we might die to sin and live to righteousness.', quoteCount: 1987 },
  ],
  'salvation-3': [
    { reference: '1 Corinthians 15:4', book: '1 Corinthians', chapter: 15, verse: 4, text: 'He was buried and raised on the third day in accordance with the Scriptures.', quoteCount: 2654 },
    { reference: 'Romans 6:9', book: 'Romans', chapter: 6, verse: 9, text: 'We know that Christ, being raised from the dead, will never die again; death no longer has dominion over him.', quoteCount: 2134 },
    { reference: '1 Peter 1:3', book: '1 Peter', chapter: 1, verse: 3, text: 'He has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead.', quoteCount: 1876 },
    { reference: 'John 11:25', book: 'John', chapter: 11, verse: 25, text: 'I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live.', quoteCount: 3210 },
    { reference: 'Philippians 3:10', book: 'Philippians', chapter: 3, verse: 10, text: 'That I may know him and the power of his resurrection.', quoteCount: 1432 },
  ],
  'grace-1': [
    { reference: 'Ephesians 2:8-9', book: 'Ephesians', chapter: 2, verse: 8, text: 'For by grace you have been saved through faith. And this is not your own doing; it is the gift of God.', quoteCount: 3456 },
    { reference: 'John 1:16', book: 'John', chapter: 1, verse: 16, text: 'For from his fullness we have all received, grace upon grace.', quoteCount: 2654 },
    { reference: '2 Corinthians 12:9', book: '2 Corinthians', chapter: 12, verse: 9, text: 'My grace is sufficient for you, for my power is made perfect in weakness.', quoteCount: 2876 },
    { reference: 'Romans 3:24', book: 'Romans', chapter: 3, verse: 24, text: 'Being justified freely by his grace through the redemption that is in Christ Jesus.', quoteCount: 1876 },
    { reference: 'Titus 2:11', book: 'Titus', chapter: 2, verse: 11, text: 'For the grace of God has appeared, bringing salvation for all people.', quoteCount: 1432 },
  ],
  'grace-2': [
    { reference: 'Luke 15:20', book: 'Luke', chapter: 15, verse: 20, text: 'His father saw him and felt compassion, and ran and embraced him and kissed him.', quoteCount: 2345 },
    { reference: 'Luke 15:24', book: 'Luke', chapter: 15, verse: 24, text: 'For this my son was dead, and is alive again; he was lost, and is found.', quoteCount: 2876 },
    { reference: 'Ephesians 1:7', book: 'Ephesians', chapter: 1, verse: 7, text: 'In him we have redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace.', quoteCount: 1987 },
    { reference: 'Psalm 103:12', book: 'Psalms', chapter: 103, verse: 12, text: 'As far as the east is from the west, so far does he remove our transgressions from us.', quoteCount: 1654 },
    { reference: 'Micah 7:19', book: 'Micah', chapter: 7, verse: 19, text: 'He will again have compassion on us; he will tread our iniquities underfoot.', quoteCount: 1234 },
  ],
  'grace-3': [
    { reference: '1 Timothy 1:15', book: '1 Timothy', chapter: 1, verse: 15, text: 'Christ Jesus came into the world to save sinners, of whom I am the foremost.', quoteCount: 2654 },
    { reference: 'Acts 9:15', book: 'Acts', chapter: 9, verse: 15, text: 'He is a chosen instrument of mine to carry my name before the Gentiles and kings.', quoteCount: 1876 },
    { reference: '1 Corinthians 15:10', book: '1 Corinthians', chapter: 15, verse: 10, text: 'But by the grace of God I am what I am, and his grace toward me was not in vain.', quoteCount: 2345 },
    { reference: 'Galatians 1:15', book: 'Galatians', chapter: 1, verse: 15, text: 'But when he who had set me apart before I was born, and who called me by his grace.', quoteCount: 1432 },
    { reference: '2 Corinthians 5:17', book: '2 Corinthians', chapter: 5, verse: 17, text: 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.', quoteCount: 1987 },
  ],
};
